// @generated by packages/reducer-contract/scripts/generate-kotlin.mjs
// DO NOT EDIT BY HAND. Edit schema/reducer-runtime*.json and rerun
// `pnpm --filter=@dreamboard-games/reducer-contract generate`.

@file:Suppress("ktlint:standard:filename", "MaximumLineLength", "MaxLineLength")

package com.dreamboard.reducer.contract

import kotlinx.serialization.SerialName
import kotlinx.serialization.SerializationStrategy
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator
import kotlinx.serialization.json.JsonElement

@Serializable
data class ContinuationToken(
    @SerialName("id")
    val id: String,
    @SerialName("data")
    val data: JsonElement,
)

@Serializable
data class ReducerSetupSelection(
    @SerialName("profileId")
    val profileId: String,
    @SerialName("optionValues")
    val optionValues: Map<String, String?>,
)

@Serializable
data class RngState(
    @SerialName("seed")
    val seed: Long?,
    @SerialName("cursor")
    val cursor: Int,
    @SerialName("trace")
    val trace: List<String>,
)

@Serializable
data class ReducerFlowState(
    @SerialName("currentPhase")
    val currentPhase: String,
    @SerialName("turn")
    val turn: Int,
    @SerialName("round")
    val round: Int,
    @SerialName("activePlayers")
    val activePlayers: List<String>,
)

@Serializable
data class RuntimeSimultaneousSubmission(
    @SerialName("interactionId")
    val interactionId: String,
    @SerialName("params")
    val params: JsonElement,
)

@Serializable
data class RuntimeSimultaneousCurrent(
    @SerialName("phaseName")
    val phaseName: String,
    @SerialName("actors")
    val actors: List<String>,
    @SerialName("submissions")
    val submissions: Map<String, RuntimeSimultaneousSubmission>,
)

@Serializable
data class RuntimeSimultaneousState(
    @SerialName("current")
    val current: RuntimeSimultaneousCurrent?,
)

@Serializable
data class TransitionRecord(
    @SerialName("from")
    val from: String,
    @SerialName("to")
    val to: String,
)

@Serializable
data class ReducerRuntimeState(
    @SerialName("rng")
    val rng: RngState,
    @SerialName("setup")
    val setup: ReducerSetupSelection?,
    @SerialName("simultaneous")
    val simultaneous: RuntimeSimultaneousState,
    @SerialName("lastTransition")
    val lastTransition: TransitionRecord?,
)

@Serializable
data class ReducerDomainState(
    @SerialName("table")
    val table: JsonElement,
    @SerialName("publicState")
    val publicState: JsonElement,
    @SerialName("privateState")
    val privateState: Map<String, JsonElement>,
    @SerialName("hiddenState")
    val hiddenState: JsonElement,
    @SerialName("flow")
    val flow: ReducerFlowState,
    @SerialName("phase")
    val phase: JsonElement,
)

@Serializable
data class ReducerSessionState(
    @SerialName("domain")
    val domain: ReducerDomainState,
    @SerialName("runtime")
    val runtime: ReducerRuntimeState,
)

@Serializable
@JsonClassDiscriminator("kind")
sealed interface GameInput {
    @Serializable
    @SerialName("interaction")
    data class Interaction(
        @SerialName("playerId")
        val playerId: String,
        @SerialName("interactionId")
        val interactionId: String,
        @SerialName("params")
        val params: JsonElement,
    ) : GameInput
}

@Serializable
@JsonClassDiscriminator("type")
sealed interface Effect {
    @Serializable
    @SerialName("transition")
    data class Transition(
        @SerialName("effectId")
        val effectId: String,
        @SerialName("to")
        val to: String,
    ) : Effect

    @Serializable
    @SerialName("rollDie")
    data class RollDie(
        @SerialName("effectId")
        val effectId: String,
        @SerialName("dieId")
        val dieId: String,
    ) : Effect

    @Serializable
    @SerialName("shuffleSharedZone")
    data class ShuffleSharedZone(
        @SerialName("effectId")
        val effectId: String,
        @SerialName("zoneId")
        val zoneId: String,
    ) : Effect

    @Serializable
    @SerialName("shufflePlayerZone")
    data class ShufflePlayerZone(
        @SerialName("effectId")
        val effectId: String,
        @SerialName("zoneId")
        val zoneId: String,
        @SerialName("playerId")
        val playerId: String,
    ) : Effect
}

@Serializable
data class ReducerInputValidationResult(
    @SerialName("valid")
    val valid: Boolean,
    @SerialName("errorCode")
    val errorCode: String? = null,
    @SerialName("message")
    val message: String? = null,
)

@Serializable
data class InitializeRequest(
    @SerialName("table")
    val table: JsonElement,
    @SerialName("playerIds")
    val playerIds: List<String>,
    @SerialName("rngSeed")
    val rngSeed: Long? = null,
    @SerialName("setup")
    val setup: ReducerSetupSelection? = null,
)

@Serializable
data class InitializePhaseRequest(
    @SerialName("state")
    val state: ReducerSessionState,
    @SerialName("to")
    val to: String,
)

@Serializable
data class ValidateInputRequest(
    @SerialName("state")
    val state: ReducerSessionState,
    @SerialName("input")
    val input: GameInput,
)

@Serializable
data class ReduceRequest(
    @SerialName("state")
    val state: ReducerSessionState,
    @SerialName("input")
    val input: GameInput,
)

@Serializable
data class DispatchRequest(
    @SerialName("state")
    val state: ReducerSessionState,
    @SerialName("input")
    val input: GameInput,
)

@Serializable
@JsonClassDiscriminator("kind")
sealed interface ReduceResult {
    @Serializable
    @SerialName("reject")
    data class Reject(
        @SerialName("errorCode")
        val errorCode: String,
        @SerialName("message")
        val message: String? = null,
    ) : ReduceResult

    @Serializable
    @SerialName("accept")
    data class Accept(
        @SerialName("state")
        val state: ReducerSessionState,
        @SerialName("effects")
        val effects: List<Effect>,
        @SerialName("continuations")
        val continuations: Map<String, ContinuationToken>,
    ) : ReduceResult
}

@Serializable
@JsonClassDiscriminator("kind")
sealed interface DispatchTrace {
    @Serializable
    @SerialName("acceptedClientInput")
    data class AcceptedClientInput(
        @SerialName("input")
        val input: GameInput,
    ) : DispatchTrace

    @Serializable
    @SerialName("appliedEffect")
    data class AppliedEffect(
        @SerialName("effect")
        val effect: Effect,
        @SerialName("continuation")
        val continuation: ContinuationToken? = null,
    ) : DispatchTrace

    @Serializable
    @SerialName("rngConsumption")
    data class RngConsumption(
        @SerialName("operation")
        val operation: String,
        @SerialName("traceEntry")
        val traceEntry: String,
    ) : DispatchTrace
}

@Serializable
@JsonClassDiscriminator("kind")
sealed interface DispatchResult {
    @Serializable
    @SerialName("reject")
    data class Reject(
        @SerialName("errorCode")
        val errorCode: String,
        @SerialName("message")
        val message: String? = null,
    ) : DispatchResult

    @Serializable
    @SerialName("accept")
    data class Accept(
        @SerialName("state")
        val state: ReducerSessionState,
        @SerialName("trace")
        val trace: List<DispatchTrace>,
    ) : DispatchResult
}

@Serializable
@JsonClassDiscriminator("kind")
sealed interface ReducerRuntimeLogEntry {
    @Serializable
    @SerialName("acceptedClientInput")
    data class AcceptedClientInput(
        @SerialName("version")
        val version: Int,
        @SerialName("input")
        val input: GameInput,
    ) : ReducerRuntimeLogEntry

    @Serializable
    @SerialName("appliedEffect")
    data class AppliedEffect(
        @SerialName("version")
        val version: Int,
        @SerialName("effect")
        val effect: Effect,
        @SerialName("continuation")
        val continuation: ContinuationToken?,
    ) : ReducerRuntimeLogEntry

    @Serializable
    @SerialName("rngConsumption")
    data class RngConsumption(
        @SerialName("version")
        val version: Int,
        @SerialName("operation")
        val operation: String,
        @SerialName("traceEntry")
        val traceEntry: String,
    ) : ReducerRuntimeLogEntry

    @Serializable
    @SerialName("stateCommit")
    data class StateCommit(
        @SerialName("version")
        val version: Int,
        @SerialName("state")
        val state: ReducerSessionState,
    ) : ReducerRuntimeLogEntry
}

@Serializable
data class SeatProjection(
    @SerialName("view")
    val view: JsonElement? = null,
    @SerialName("availableInteractionRefs")
    val availableInteractionRefs: JsonElement? = null,
    @SerialName("zones")
    val zones: JsonElement? = null,
)

@Serializable
data class SimultaneousPhaseProjection(
    @SerialName("phaseName")
    val phaseName: String,
    @SerialName("interactionId")
    val interactionId: String,
    @SerialName("actorIds")
    val actorIds: List<String>,
    @SerialName("sealedPlayerIds")
    val sealedPlayerIds: List<String>,
    @SerialName("pendingPlayerIds")
    val pendingPlayerIds: List<String>,
)

@Serializable
data class SeatProjectionBundle(
    @SerialName("currentStage")
    val currentStage: String? = null,
    @SerialName("stageSeats")
    val stageSeats: List<String> = emptyList(),
    @SerialName("simultaneousPhase")
    val simultaneousPhase: SimultaneousPhaseProjection? = null,
    @SerialName("interactionsByRef")
    val interactionsByRef: JsonElement? = null,
    @SerialName("seats")
    val seats: Map<String, SeatProjection>,
)

@Serializable
data class ProjectSeatsDynamicRequest(
    @SerialName("state")
    val state: ReducerSessionState,
    @SerialName("playerIds")
    val playerIds: List<String>,
    @SerialName("viewId")
    val viewId: String? = null,
    @SerialName("projectionMode")
    val projectionMode: String? = null,
)

@Serializable
data class ReducerWorkerRuntimeBundleRef(
    @SerialName("artifactKeyPrefix")
    val artifactKeyPrefix: String,
    @SerialName("entryPoint")
    val entryPoint: String? = null,
)

@Serializable
data class ReducerWorkerBundleRef(
    @SerialName("runtimeBundle")
    val runtimeBundle: ReducerWorkerRuntimeBundleRef? = null,
    @SerialName("cacheKey")
    val cacheKey: String? = null,
)

@Serializable
data class ReducerWorkerSubmitActionRequest(
    @SerialName("sessionId")
    val sessionId: String,
    @SerialName("gameId")
    val gameId: String,
    @SerialName("buildId")
    val buildId: String? = null,
    @SerialName("bundleRef")
    val bundleRef: ReducerWorkerBundleRef? = null,
    @SerialName("state")
    val state: ReducerSessionState? = null,
    @SerialName("actorUserId")
    val actorUserId: String,
    @SerialName("input")
    val input: GameInput,
    @SerialName("expectedVersion")
    val expectedVersion: Int,
    @SerialName("ownerWorkerId")
    val ownerWorkerId: String,
    @SerialName("epoch")
    val epoch: Int,
    @SerialName("clientActionId")
    val clientActionId: String,
    @SerialName("actionFingerprint")
    val actionFingerprint: String,
    @SerialName("runtimeContractVersion")
    val runtimeContractVersion: String,
    @SerialName("bundleCacheKey")
    val bundleCacheKey: String? = null,
    @SerialName("inlineBudgetMs")
    val inlineBudgetMs: Int? = null,
    @SerialName("projectionPlayerIds")
    val projectionPlayerIds: List<String> = emptyList(),
    @SerialName("includeStaticProjection")
    val includeStaticProjection: Boolean? = null,
    @SerialName("viewId")
    val viewId: String? = null,
    @SerialName("projectionMode")
    val projectionMode: String? = null,
)

@Serializable
@JsonClassDiscriminator("kind")
sealed interface ReducerWorkerSubmitActionResponse {
    @Serializable
    @SerialName("rejected")
    data class Rejected(
        @SerialName("version")
        val version: Int? = null,
        @SerialName("errorCode")
        val errorCode: String,
        @SerialName("message")
        val message: String? = null,
        @SerialName("projection")
        val projection: SeatProjectionBundle? = null,
        @SerialName("staticProjection")
        val staticProjection: BoardStaticProjection? = null,
    ) : ReducerWorkerSubmitActionResponse

    @Serializable
    @SerialName("deferred")
    data class Deferred(
        @SerialName("reason")
        val reason: String,
        @SerialName("retryAfterMs")
        val retryAfterMs: Int? = null,
        @SerialName("workJobId")
        val workJobId: String? = null,
    ) : ReducerWorkerSubmitActionResponse

    @Serializable
    @SerialName("redirect")
    data class Redirect(
        @SerialName("ownerWorkerId")
        val ownerWorkerId: String,
        @SerialName("endpoint")
        val endpoint: String? = null,
        @SerialName("epoch")
        val epoch: Int? = null,
    ) : ReducerWorkerSubmitActionResponse
}

@Serializable
data class ReducerWorkerProjectSessionRequest(
    @SerialName("sessionId")
    val sessionId: String,
    @SerialName("bundleRef")
    val bundleRef: ReducerWorkerBundleRef? = null,
    @SerialName("state")
    val state: ReducerSessionState? = null,
    @SerialName("stateVersion")
    val stateVersion: Int? = null,
    @SerialName("playerIds")
    val playerIds: List<String>,
    @SerialName("includeStaticProjection")
    val includeStaticProjection: Boolean? = null,
    @SerialName("viewId")
    val viewId: String? = null,
    @SerialName("projectionMode")
    val projectionMode: String? = null,
)

@Serializable
@JsonClassDiscriminator("kind")
sealed interface ReducerWorkerProjectSessionResponse {
    @Serializable
    @SerialName("projected")
    data class Projected(
        @SerialName("version")
        val version: Int,
        @SerialName("currentPhase")
        val currentPhase: String,
        @SerialName("activePlayers")
        val activePlayers: List<String>,
        @SerialName("projection")
        val projection: SeatProjectionBundle,
        @SerialName("staticProjection")
        val staticProjection: BoardStaticProjection? = null,
    ) : ReducerWorkerProjectSessionResponse

    @Serializable
    @SerialName("deferred")
    data class Deferred(
        @SerialName("reason")
        val reason: String,
        @SerialName("retryAfterMs")
        val retryAfterMs: Int? = null,
        @SerialName("workJobId")
        val workJobId: String? = null,
    ) : ReducerWorkerProjectSessionResponse

    @Serializable
    @SerialName("redirect")
    data class Redirect(
        @SerialName("ownerWorkerId")
        val ownerWorkerId: String,
        @SerialName("endpoint")
        val endpoint: String? = null,
        @SerialName("epoch")
        val epoch: Int? = null,
    ) : ReducerWorkerProjectSessionResponse
}

@Serializable
data class ReducerWorkerInitializeSessionRequest(
    @SerialName("sessionId")
    val sessionId: String,
    @SerialName("gameId")
    val gameId: String,
    @SerialName("buildId")
    val buildId: String? = null,
    @SerialName("bundleRef")
    val bundleRef: ReducerWorkerBundleRef,
    @SerialName("manifest")
    val manifest: JsonElement,
    @SerialName("playerIds")
    val playerIds: List<String>,
    @SerialName("rngSeed")
    val rngSeed: Long? = null,
    @SerialName("setup")
    val setup: ReducerSetupSelection? = null,
    @SerialName("projectionPlayerIds")
    val projectionPlayerIds: List<String> = emptyList(),
    @SerialName("includeStaticProjection")
    val includeStaticProjection: Boolean? = null,
    @SerialName("viewId")
    val viewId: String? = null,
    @SerialName("projectionMode")
    val projectionMode: String? = null,
)

@Serializable
@JsonClassDiscriminator("kind")
sealed interface ReducerWorkerInitializeSessionResponse {
    @Serializable
    @SerialName("initialized")
    data class Initialized(
        @SerialName("version")
        val version: Int,
        @SerialName("state")
        val state: ReducerSessionState,
        @SerialName("projection")
        val projection: SeatProjectionBundle? = null,
        @SerialName("staticProjection")
        val staticProjection: BoardStaticProjection? = null,
    ) : ReducerWorkerInitializeSessionResponse

    @Serializable
    @SerialName("deferred")
    data class Deferred(
        @SerialName("reason")
        val reason: String,
        @SerialName("retryAfterMs")
        val retryAfterMs: Int? = null,
        @SerialName("workJobId")
        val workJobId: String? = null,
    ) : ReducerWorkerInitializeSessionResponse

    @Serializable
    @SerialName("redirect")
    data class Redirect(
        @SerialName("ownerWorkerId")
        val ownerWorkerId: String,
        @SerialName("endpoint")
        val endpoint: String? = null,
        @SerialName("epoch")
        val epoch: Int? = null,
    ) : ReducerWorkerInitializeSessionResponse
}

@Serializable
data class ReducerWorkerRecoverSessionRequest(
    @SerialName("sessionId")
    val sessionId: String,
    @SerialName("gameId")
    val gameId: String,
    @SerialName("buildId")
    val buildId: String? = null,
    @SerialName("bundleRef")
    val bundleRef: ReducerWorkerBundleRef? = null,
    @SerialName("state")
    val state: ReducerSessionState? = null,
    @SerialName("targetVersion")
    val targetVersion: Int? = null,
    @SerialName("inlineBudgetMs")
    val inlineBudgetMs: Int? = null,
    @SerialName("projectionPlayerIds")
    val projectionPlayerIds: List<String> = emptyList(),
    @SerialName("includeStaticProjection")
    val includeStaticProjection: Boolean? = null,
    @SerialName("viewId")
    val viewId: String? = null,
    @SerialName("projectionMode")
    val projectionMode: String? = null,
)

@Serializable
@JsonClassDiscriminator("kind")
sealed interface ReducerWorkerRecoverSessionResponse {
    @Serializable
    @SerialName("recovered")
    data class Recovered(
        @SerialName("version")
        val version: Int,
        @SerialName("state")
        val state: ReducerSessionState,
        @SerialName("projection")
        val projection: SeatProjectionBundle? = null,
        @SerialName("staticProjection")
        val staticProjection: BoardStaticProjection? = null,
    ) : ReducerWorkerRecoverSessionResponse

    @Serializable
    @SerialName("deferred")
    data class Deferred(
        @SerialName("reason")
        val reason: String,
        @SerialName("retryAfterMs")
        val retryAfterMs: Int? = null,
        @SerialName("workJobId")
        val workJobId: String? = null,
    ) : ReducerWorkerRecoverSessionResponse

    @Serializable
    @SerialName("redirect")
    data class Redirect(
        @SerialName("ownerWorkerId")
        val ownerWorkerId: String,
        @SerialName("endpoint")
        val endpoint: String? = null,
        @SerialName("epoch")
        val epoch: Int? = null,
    ) : ReducerWorkerRecoverSessionResponse
}

@Serializable
data class ReducerWorkerErrorResponse(
    @SerialName("code")
    val code: String,
    @SerialName("message")
    val message: String,
    @SerialName("retryable")
    val retryable: Boolean? = null,
)

@Serializable
data class BoardStaticProjection(
    @SerialName("view")
    val view: JsonElement,
    @SerialName("hash")
    val hash: String,
    @SerialName("manifestVersion")
    val manifestVersion: String,
)

/** Generated metadata for the callable reducer bundle boundary. */
enum class ReducerBundlePayloadMeasurement {
    NONE,
    JSON_BYTES,
}

data class ReducerBundleRequestOperation<I>(
    val methodName: String,
    val requestSerializer: SerializationStrategy<I>,
    val requestPayloadMeasurement: ReducerBundlePayloadMeasurement,
    val responsePayloadMeasurement: ReducerBundlePayloadMeasurement,
)

data class ReducerBundleNoInputOperation(
    val methodName: String,
    val requestPayloadMeasurement: ReducerBundlePayloadMeasurement,
    val responsePayloadMeasurement: ReducerBundlePayloadMeasurement,
)

object ReducerBundleOperations {
    const val VERSION_PROPERTY: String = "reducerContractVersion"
    const val INITIALIZE_METHOD: String = "initialize"
    const val INITIALIZE_PHASE_METHOD: String = "initializePhase"
    const val VALIDATE_INPUT_METHOD: String = "validateInput"
    const val REDUCE_METHOD: String = "reduce"
    const val DISPATCH_METHOD: String = "dispatch"
    const val PROJECT_STATIC_METHOD: String = "projectStatic"
    const val PROJECT_SEATS_DYNAMIC_METHOD: String = "projectSeatsDynamic"

    val REQUIRED_METHOD_NAMES: List<String> = listOf(
        INITIALIZE_METHOD,
        INITIALIZE_PHASE_METHOD,
        VALIDATE_INPUT_METHOD,
        REDUCE_METHOD,
        DISPATCH_METHOD,
        PROJECT_STATIC_METHOD,
        PROJECT_SEATS_DYNAMIC_METHOD,
    )

    val INITIALIZE: ReducerBundleRequestOperation<InitializeRequest> = ReducerBundleRequestOperation(
        methodName = INITIALIZE_METHOD,
        requestSerializer = InitializeRequest.serializer(),
        requestPayloadMeasurement = ReducerBundlePayloadMeasurement.JSON_BYTES,
        responsePayloadMeasurement = ReducerBundlePayloadMeasurement.JSON_BYTES,
    )

    val INITIALIZE_PHASE: ReducerBundleRequestOperation<InitializePhaseRequest> = ReducerBundleRequestOperation(
        methodName = INITIALIZE_PHASE_METHOD,
        requestSerializer = InitializePhaseRequest.serializer(),
        requestPayloadMeasurement = ReducerBundlePayloadMeasurement.JSON_BYTES,
        responsePayloadMeasurement = ReducerBundlePayloadMeasurement.JSON_BYTES,
    )

    val VALIDATE_INPUT: ReducerBundleRequestOperation<ValidateInputRequest> = ReducerBundleRequestOperation(
        methodName = VALIDATE_INPUT_METHOD,
        requestSerializer = ValidateInputRequest.serializer(),
        requestPayloadMeasurement = ReducerBundlePayloadMeasurement.JSON_BYTES,
        responsePayloadMeasurement = ReducerBundlePayloadMeasurement.JSON_BYTES,
    )

    val REDUCE: ReducerBundleRequestOperation<ReduceRequest> = ReducerBundleRequestOperation(
        methodName = REDUCE_METHOD,
        requestSerializer = ReduceRequest.serializer(),
        requestPayloadMeasurement = ReducerBundlePayloadMeasurement.JSON_BYTES,
        responsePayloadMeasurement = ReducerBundlePayloadMeasurement.JSON_BYTES,
    )

    val DISPATCH: ReducerBundleRequestOperation<DispatchRequest> = ReducerBundleRequestOperation(
        methodName = DISPATCH_METHOD,
        requestSerializer = DispatchRequest.serializer(),
        requestPayloadMeasurement = ReducerBundlePayloadMeasurement.JSON_BYTES,
        responsePayloadMeasurement = ReducerBundlePayloadMeasurement.JSON_BYTES,
    )

    val PROJECT_STATIC: ReducerBundleNoInputOperation = ReducerBundleNoInputOperation(
        methodName = PROJECT_STATIC_METHOD,
        requestPayloadMeasurement = ReducerBundlePayloadMeasurement.NONE,
        responsePayloadMeasurement = ReducerBundlePayloadMeasurement.JSON_BYTES,
    )

    val PROJECT_SEATS_DYNAMIC: ReducerBundleRequestOperation<ProjectSeatsDynamicRequest> = ReducerBundleRequestOperation(
        methodName = PROJECT_SEATS_DYNAMIC_METHOD,
        requestSerializer = ProjectSeatsDynamicRequest.serializer(),
        requestPayloadMeasurement = ReducerBundlePayloadMeasurement.JSON_BYTES,
        responsePayloadMeasurement = ReducerBundlePayloadMeasurement.JSON_BYTES,
    )
}

/**
 * Wire-protocol version implemented by this generated code. Must match
 * the JS bundle's REDUCER_CONTRACT_VERSION at load time.
 */
public const val REDUCER_CONTRACT_VERSION: String = "0.2.0"
