export type {
  ActionInteractionDescriptor,
  GameEvent,
  GameEventDetail,
  GameOutcome,
  GameplayBasis,
  InteractionAvailability,
  InteractionChoiceOption,
  InteractionCommitPolicy,
  InteractionDescriptor,
  InteractionDiagnosticReason,
  InteractionInputDescriptor,
  InputDomain,
  InputSelection,
  OutcomeResult,
  OutcomeScoreComponent,
  OutcomeStanding,
  OutcomeTieBreak,
  PlayerId,
  PluginGameplayFrame,
  PluginPlayerSummary,
  PluginSessionDescriptor,
  ReducerBoardStaticProjection,
  ReducerSeatProjectionBundle,
  SimultaneousPhaseSnapshot,
  SystemActionEvent,
  ZoneHandlesSnapshot,
} from "./frame.js";
export type { CanonicalJson, RuntimeJson } from "./json.js";
export type {
  ActionSetVersionInput,
  HostToPluginEnvelope,
  HostToPluginPayload,
  InteractionResult,
  PluginProtocolEnvelope,
  PluginProtocolFrame,
  PluginProtocolStep,
  PluginProtocolTape,
  PluginToHostEnvelope,
  PluginToHostPayload,
  SubmitInteractionCommand,
  CancelInteractionCommand,
} from "./protocol.js";
export {
  DREAMBOARD_PLUGIN_PROTOCOL,
  DREAMBOARD_PLUGIN_PROTOCOL_VERSION,
} from "./protocol.js";
export {
  canonicalizePluginRuntimeJson,
  computePluginActionSetVersion,
  digestPluginCommandRequest,
  digestPluginGameplayFrame,
  digestPluginRuntimeJson,
  encodeCanonicalPluginRuntimeJson,
} from "./digest.js";
export {
  type MaterializePluginGameplayFrameInput,
  materializePluginGameplayFrame,
} from "./projection.js";
export {
  BoardStaticProjectionSchema,
  GameEventDetailSchema,
  GameEventSchema,
  GameOutcomeSchema,
  GameplayBasisSchema,
  HostToPluginEnvelopeSchema,
  HostToPluginPayloadSchema,
  InputDomainSchema,
  InteractionAvailabilitySchema,
  InteractionCommitPolicySchema,
  InteractionDescriptorSchema,
  InteractionInputDescriptorSchema,
  PluginGameplayFrameSchema,
  PluginPlayerSummarySchema,
  PluginProtocolFrameSchema,
  PluginProtocolStepSchema,
  PluginProtocolTapeSchema,
  PluginSessionDescriptorSchema,
  PluginToHostEnvelopeSchema,
  PluginToHostPayloadSchema,
  RuntimeJsonSchema,
  SeatProjectionBundleSchema,
  SimultaneousPhaseSnapshotSchema,
  InteractionResultSchema,
  SystemActionEventSchema,
  SubmitInteractionCommandSchema,
  CancelInteractionCommandSchema,
  ZoneHandlesSnapshotSchema,
  createPluginProtocolEnvelopeSchema,
  parseHostToPluginEnvelope,
  parsePluginGameplayFrame,
  parsePluginSessionDescriptor,
  parsePluginToHostEnvelope,
} from "./schema.js";
