export type {
  ActionInteractionDescriptor,
  GameEvent,
  GameEventDetail,
  InteractionAvailability,
  InteractionChoiceOption,
  InteractionCommitPolicy,
  InteractionContext,
  InteractionContextOption,
  InteractionDescriptor,
  InteractionDiagnosticReason,
  InteractionInputDescriptor,
  InputDomain,
  InputDomainDependencies,
  InputDomainDependencyCase,
  InputSelection,
  PlayerId,
  PluginGameplayFrame,
  PluginPlayerSummary,
  ProjectedGameEvent,
  PluginSessionDescriptor,
  PromptInteractionDescriptor,
  ReducerBoardStaticProjection,
  ReducerSeatProjectionBundle,
  SimultaneousPhaseSnapshot,
  SystemActionEvent,
  ZoneHandlesSnapshot,
} from "./frame.js";
export type { CanonicalJson, RuntimeJson } from "./json.js";
export type {
  ActionSetVersionInput,
  HostToPluginEnvelope,
  HostToPluginPayload,
  PluginInteractionBasis,
  PluginProtocolEnvelope,
  PluginProtocolFrame,
  PluginProtocolStep,
  PluginProtocolTape,
  PluginToHostEnvelope,
  PluginToHostPayload,
  SubmissionResult,
  SubmitInteractionCommand,
  ValidateInteractionCommand,
  ValidationResult,
} from "./protocol.js";
export {
  DREAMBOARD_PLUGIN_PROTOCOL,
  DREAMBOARD_PLUGIN_PROTOCOL_VERSION,
} from "./protocol.js";
export {
  canonicalizePluginRuntimeJson,
  computePluginActionSetVersion,
  digestPluginCommandRequest,
  digestPluginGameplayFrame,
  digestPluginRuntimeJson,
  encodeCanonicalPluginRuntimeJson,
} from "./digest.js";
export {
  type MaterializePluginGameplayFrameInput,
  materializePluginGameplayFrame,
} from "./projection.js";
export {
  BoardStaticProjectionSchema,
  GameEventDetailSchema,
  GameEventSchema,
  HostToPluginEnvelopeSchema,
  HostToPluginPayloadSchema,
  InputDomainDependenciesSchema,
  InputDomainSchema,
  InteractionAvailabilitySchema,
  InteractionCommitPolicySchema,
  InteractionContextSchema,
  InteractionDescriptorSchema,
  InteractionInputDescriptorSchema,
  PluginGameplayFrameSchema,
  PluginInteractionBasisSchema,
  PluginPlayerSummarySchema,
  PluginProtocolFrameSchema,
  PluginProtocolStepSchema,
  PluginProtocolTapeSchema,
  PluginSessionDescriptorSchema,
  PluginToHostEnvelopeSchema,
  PluginToHostPayloadSchema,
  ProjectedGameEventSchema,
  RuntimeJsonSchema,
  SeatProjectionBundleSchema,
  SimultaneousPhaseSnapshotSchema,
  SubmissionResultSchema,
  SystemActionEventSchema,
  SubmitInteractionCommandSchema,
  ValidateInteractionCommandSchema,
  ValidationResultSchema,
  ZoneHandlesSnapshotSchema,
  createPluginProtocolEnvelopeSchema,
  parseHostToPluginEnvelope,
  parsePluginGameplayFrame,
  parsePluginSessionDescriptor,
  parsePluginToHostEnvelope,
} from "./schema.js";
