/**
 * Generated file.
 * Do not edit directly.
 */

export const literals = {
  playerIds: ["player-1", "player-2", "player-3", "player-4"] as const,
  phaseNames: [] as readonly string[],
  boardLayouts: ["generic", "hex", "square"] as const,
  setupOptionIds: [] as const,
  setupProfileIds: ["default"] as const,
  cardSetIds: ["playing-cards"] as const,
  cardTypes: ["clubs-10", "clubs-2", "clubs-3", "clubs-4", "clubs-5", "clubs-6", "clubs-7", "clubs-8", "clubs-9", "clubs-A", "clubs-J", "clubs-K", "clubs-Q", "diamonds-10", "diamonds-2", "diamonds-3", "diamonds-4", "diamonds-5", "diamonds-6", "diamonds-7", "diamonds-8", "diamonds-9", "diamonds-A", "diamonds-J", "diamonds-K", "diamonds-Q", "hearts-10", "hearts-2", "hearts-3", "hearts-4", "hearts-5", "hearts-6", "hearts-7", "hearts-8", "hearts-9", "hearts-A", "hearts-J", "hearts-K", "hearts-Q", "spades-10", "spades-2", "spades-3", "spades-4", "spades-5", "spades-6", "spades-7", "spades-8", "spades-9", "spades-A", "spades-J", "spades-K", "spades-Q"] as const,
  cardIds: ["clubs-10", "clubs-2", "clubs-3", "clubs-4", "clubs-5", "clubs-6", "clubs-7", "clubs-8", "clubs-9", "clubs-A", "clubs-J", "clubs-K", "clubs-Q", "diamonds-10", "diamonds-2", "diamonds-3", "diamonds-4", "diamonds-5", "diamonds-6", "diamonds-7", "diamonds-8", "diamonds-9", "diamonds-A", "diamonds-J", "diamonds-K", "diamonds-Q", "hearts-10", "hearts-2", "hearts-3", "hearts-4", "hearts-5", "hearts-6", "hearts-7", "hearts-8", "hearts-9", "hearts-A", "hearts-J", "hearts-K", "hearts-Q", "spades-10", "spades-2", "spades-3", "spades-4", "spades-5", "spades-6", "spades-7", "spades-8", "spades-9", "spades-A", "spades-J", "spades-K", "spades-Q"] as const,
  deckIds: ["current-trick", "discard", "draw-pile"] as const,
  handIds: ["hand"] as const,
  sharedZoneIds: ["current-trick", "discard", "draw-pile"] as const,
  playerZoneIds: ["hand"] as const,
  zoneIds: ["current-trick", "discard", "draw-pile", "hand"] as const,
  resourceIds: [] as const,
  resourcePresentationById: {} as const,
  pieceTypeIds: [] as const,
  pieceIds: [] as const,
  dieTypeIds: [] as const,
  dieIds: [] as const,
  boardTemplateIds: [] as const,
  boardTypeIds: [] as const,
  boardBaseIds: [] as const,
  boardIds: [] as const,
  boardContainerIds: [] as const,
  relationTypeIds: [] as const,
  edgeIds: [] as const,
  edgeTypeIds: [] as const,
  vertexIds: [] as const,
  vertexTypeIds: [] as const,
  spaceIds: [] as const,
  spaceTypeIds: [] as const,
  handVisibilityById: {
  "hand": "ownerOnly",
} as const,
  zoneVisibilityById: {
  "current-trick": "public",
  "discard": "public",
  "draw-pile": "hidden",
  "hand": "ownerOnly",
} as const,
  cardSetIdByCardId: {
  "clubs-10": "playing-cards",
  "clubs-2": "playing-cards",
  "clubs-3": "playing-cards",
  "clubs-4": "playing-cards",
  "clubs-5": "playing-cards",
  "clubs-6": "playing-cards",
  "clubs-7": "playing-cards",
  "clubs-8": "playing-cards",
  "clubs-9": "playing-cards",
  "clubs-A": "playing-cards",
  "clubs-J": "playing-cards",
  "clubs-K": "playing-cards",
  "clubs-Q": "playing-cards",
  "diamonds-10": "playing-cards",
  "diamonds-2": "playing-cards",
  "diamonds-3": "playing-cards",
  "diamonds-4": "playing-cards",
  "diamonds-5": "playing-cards",
  "diamonds-6": "playing-cards",
  "diamonds-7": "playing-cards",
  "diamonds-8": "playing-cards",
  "diamonds-9": "playing-cards",
  "diamonds-A": "playing-cards",
  "diamonds-J": "playing-cards",
  "diamonds-K": "playing-cards",
  "diamonds-Q": "playing-cards",
  "hearts-10": "playing-cards",
  "hearts-2": "playing-cards",
  "hearts-3": "playing-cards",
  "hearts-4": "playing-cards",
  "hearts-5": "playing-cards",
  "hearts-6": "playing-cards",
  "hearts-7": "playing-cards",
  "hearts-8": "playing-cards",
  "hearts-9": "playing-cards",
  "hearts-A": "playing-cards",
  "hearts-J": "playing-cards",
  "hearts-K": "playing-cards",
  "hearts-Q": "playing-cards",
  "spades-10": "playing-cards",
  "spades-2": "playing-cards",
  "spades-3": "playing-cards",
  "spades-4": "playing-cards",
  "spades-5": "playing-cards",
  "spades-6": "playing-cards",
  "spades-7": "playing-cards",
  "spades-8": "playing-cards",
  "spades-9": "playing-cards",
  "spades-A": "playing-cards",
  "spades-J": "playing-cards",
  "spades-K": "playing-cards",
  "spades-Q": "playing-cards",
} as const,
  cardTypeByCardId: {
  "clubs-10": "clubs-10",
  "clubs-2": "clubs-2",
  "clubs-3": "clubs-3",
  "clubs-4": "clubs-4",
  "clubs-5": "clubs-5",
  "clubs-6": "clubs-6",
  "clubs-7": "clubs-7",
  "clubs-8": "clubs-8",
  "clubs-9": "clubs-9",
  "clubs-A": "clubs-A",
  "clubs-J": "clubs-J",
  "clubs-K": "clubs-K",
  "clubs-Q": "clubs-Q",
  "diamonds-10": "diamonds-10",
  "diamonds-2": "diamonds-2",
  "diamonds-3": "diamonds-3",
  "diamonds-4": "diamonds-4",
  "diamonds-5": "diamonds-5",
  "diamonds-6": "diamonds-6",
  "diamonds-7": "diamonds-7",
  "diamonds-8": "diamonds-8",
  "diamonds-9": "diamonds-9",
  "diamonds-A": "diamonds-A",
  "diamonds-J": "diamonds-J",
  "diamonds-K": "diamonds-K",
  "diamonds-Q": "diamonds-Q",
  "hearts-10": "hearts-10",
  "hearts-2": "hearts-2",
  "hearts-3": "hearts-3",
  "hearts-4": "hearts-4",
  "hearts-5": "hearts-5",
  "hearts-6": "hearts-6",
  "hearts-7": "hearts-7",
  "hearts-8": "hearts-8",
  "hearts-9": "hearts-9",
  "hearts-A": "hearts-A",
  "hearts-J": "hearts-J",
  "hearts-K": "hearts-K",
  "hearts-Q": "hearts-Q",
  "spades-10": "spades-10",
  "spades-2": "spades-2",
  "spades-3": "spades-3",
  "spades-4": "spades-4",
  "spades-5": "spades-5",
  "spades-6": "spades-6",
  "spades-7": "spades-7",
  "spades-8": "spades-8",
  "spades-9": "spades-9",
  "spades-A": "spades-A",
  "spades-J": "spades-J",
  "spades-K": "spades-K",
  "spades-Q": "spades-Q",
} as const,
  setupChoiceIdsByOptionId: {

} as const,
  cardSetIdsBySharedZoneId: {
  "current-trick": ["playing-cards"] as const,
  "discard": ["playing-cards"] as const,
  "draw-pile": ["playing-cards"] as const,
} as const,
  sharedZoneIdsByCardSetId: {
  "playing-cards": ["current-trick", "discard", "draw-pile"] as const,
} as const,
  homeSharedZoneIdsByCardType: {
  "clubs-10": [] as const,
  "clubs-2": [] as const,
  "clubs-3": [] as const,
  "clubs-4": [] as const,
  "clubs-5": [] as const,
  "clubs-6": [] as const,
  "clubs-7": [] as const,
  "clubs-8": [] as const,
  "clubs-9": [] as const,
  "clubs-A": [] as const,
  "clubs-J": [] as const,
  "clubs-K": [] as const,
  "clubs-Q": [] as const,
  "diamonds-10": [] as const,
  "diamonds-2": [] as const,
  "diamonds-3": [] as const,
  "diamonds-4": [] as const,
  "diamonds-5": [] as const,
  "diamonds-6": [] as const,
  "diamonds-7": [] as const,
  "diamonds-8": [] as const,
  "diamonds-9": [] as const,
  "diamonds-A": [] as const,
  "diamonds-J": [] as const,
  "diamonds-K": [] as const,
  "diamonds-Q": [] as const,
  "hearts-10": [] as const,
  "hearts-2": [] as const,
  "hearts-3": [] as const,
  "hearts-4": [] as const,
  "hearts-5": [] as const,
  "hearts-6": [] as const,
  "hearts-7": [] as const,
  "hearts-8": [] as const,
  "hearts-9": [] as const,
  "hearts-A": [] as const,
  "hearts-J": [] as const,
  "hearts-K": [] as const,
  "hearts-Q": [] as const,
  "spades-10": [] as const,
  "spades-2": [] as const,
  "spades-3": [] as const,
  "spades-4": [] as const,
  "spades-5": [] as const,
  "spades-6": [] as const,
  "spades-7": [] as const,
  "spades-8": [] as const,
  "spades-9": [] as const,
  "spades-A": [] as const,
  "spades-J": [] as const,
  "spades-K": [] as const,
  "spades-Q": [] as const,
} as const,
  homeSharedZoneIdByCardType: {

} as const,
  cardSetIdsByPlayerZoneId: {
  "hand": ["playing-cards"] as const,
} as const,
} as const;
