export type {
  ActionInteractionDescriptor,
  GameEvent,
  GameEventDetail,
  GameOutcome,
  GameplayBasis,
  InteractionAvailability,
  InteractionChoiceOption,
  InteractionCommitPolicy,
  InteractionDescriptor,
  InteractionDiagnosticReason,
  InteractionInputDescriptor,
  InputDomain,
  InputSelection,
  OutcomeResult,
  OutcomeScoreComponent,
  OutcomeStanding,
  OutcomeTieBreak,
  PlayerId,
  PluginGameplayFrame,
  PluginPlayerSummary,
  PluginSessionDescriptor,
  ReducerBoardStaticProjection,
  ReducerSeatProjectionBundle,
  SimultaneousPhaseSnapshot,
  SystemActionEvent,
  ZoneHandlesSnapshot,
} from "./shared/protocol/frame.js";
export type { CanonicalJson, RuntimeJson } from "./shared/runtime-json.js";
export type {
  ActionSetVersionInput,
  HostToPluginEnvelope,
  HostToPluginPayload,
  InteractionResult,
  PluginProtocolEnvelope,
  PluginProtocolFrame,
  PluginProtocolStep,
  PluginProtocolTape,
  PluginToHostEnvelope,
  PluginToHostPayload,
  SubmitInteractionCommand,
  CancelInteractionCommand,
} from "./shared/protocol/protocol.js";
export {
  DREAMBOARD_PLUGIN_PROTOCOL,
  DREAMBOARD_PLUGIN_PROTOCOL_VERSION,
} from "./shared/protocol/protocol.js";
export {
  canonicalizePluginRuntimeJson,
  computePluginActionSetVersion,
  digestPluginCommandRequest,
  digestPluginGameplayFrame,
  digestPluginRuntimeJson,
  encodeCanonicalPluginRuntimeJson,
} from "./shared/protocol/digest.js";
export {
  type MaterializePluginGameplayFrameInput,
  materializePluginGameplayFrame,
} from "./shared/protocol/projection.js";
export {
  BoardStaticProjectionSchema,
  GameEventDetailSchema,
  GameEventSchema,
  GameOutcomeSchema,
  GameplayBasisSchema,
  HostToPluginEnvelopeSchema,
  HostToPluginPayloadSchema,
  InputDomainSchema,
  InteractionAvailabilitySchema,
  InteractionCommitPolicySchema,
  InteractionDescriptorSchema,
  InteractionInputDescriptorSchema,
  PluginGameplayFrameSchema,
  PluginPlayerSummarySchema,
  PluginProtocolFrameSchema,
  PluginProtocolStepSchema,
  PluginProtocolTapeSchema,
  PluginSessionDescriptorSchema,
  PluginToHostEnvelopeSchema,
  PluginToHostPayloadSchema,
  SeatProjectionBundleSchema,
  SimultaneousPhaseSnapshotSchema,
  InteractionResultSchema,
  SystemActionEventSchema,
  SubmitInteractionCommandSchema,
  CancelInteractionCommandSchema,
  ZoneHandlesSnapshotSchema,
  createPluginProtocolEnvelopeSchema,
  parseHostToPluginEnvelope,
  parsePluginGameplayFrame,
  parsePluginSessionDescriptor,
  parsePluginToHostEnvelope,
} from "./shared/protocol/schema.js";

export { RuntimeJsonSchema } from "./shared/runtime-json.js";
