export {
  defineEffect,
  defineCardAction,
  createContractAuthoring,
  defineGame,
  defineGameContract,
  defineInteraction,
  defineInteractionRule,
  definePhase,
  definePhaseStage,
  defineStepPhase,
  defineStage,
  defineStaticView,
  defineView,
  type ReducerGameContract,
  type ReducerGameDefinition,
  type BoundInputBuilders,
  type ContractAuthoring,
  type ContractWithPhases,
  type InitialStateCallbacks,
  type PhaseAuthoring,
  type ReducerPhaseDefinition,
  type ReducerViewDefinition,
} from "./reducer/authoring";
export type { InteractionRule } from "./reducer/model";
export {
  boardInput,
  boardTarget,
  cardInput,
  cardTarget,
  choiceTarget,
  defineInputs,
  formInput,
  many,
  promptInput,
  rngInput,
  type BoardTargetBuilder,
  type BoardTargetPredicate,
  type BoardTargetRule,
  type BoundTargetRule,
  type CardTargetBuilder,
  type CardTargetPredicate,
  type CardTargetRule,
  type ChoiceOptionsFactory,
  type ChoiceTargetBuilder,
  type ChoiceTargetOption,
  type ChoiceTargetPredicate,
  type ChoiceTargetRule,
  type DependencyValues,
  type DefinedInputs,
  type InputFieldRef,
  type ManyOptions,
  type PlayerBoardSpaceTarget,
  type TargetContext,
  type TargetPredicate,
  type TargetPredicateArgs,
  type TargetRule,
  type TargetRuleBuilder,
} from "./reducer/inputs";
export {
  normalizeCommandParams,
  sparseCounts,
  sparseMap,
  type SparseCounts,
  type SparseMap,
} from "./reducer/schema-helpers";
export {
  assumeManifestSchema,
  cloneManifestDefault,
  createManifestGameStateSchema,
  createManifestRuntimeSchema,
  createManifestStringLiteralSchema,
  markManifestScopedSchema,
  resolveManifestPlayerIds,
} from "./reducer/model";
export { createReducerBundle } from "./reducer/bundle";
export {
  createClientParamSchemasByPhase,
  type ClientParamSchema,
  type ClientParamSchemasByPhase,
} from "./reducer/client-param-schemas";
export type {
  CardInputZoneIdsOfDefinition,
  InputKeysWithCollectorKindOfDefinition,
} from "./reducer/model";
export type { ReducerBundle } from "./reducer/bundle";
export { applySetupBootstrap } from "./reducer/setup-bootstrap";
export {
  dealToPlayerBoardContainer,
  dealToPlayerZone,
  seedSharedBoardContainer,
  seedSharedBoardSpace,
  shuffle,
} from "./reducer/setup-bootstrap-helpers";
export { pipe, type Op } from "./reducer/compose";
export {
  createReducerEdit,
  createReducerTransaction,
  type ReducerEdit,
  type ReducerTransaction,
  type RotatePlayerZoneArgs,
} from "./reducer/transaction";
export {
  asPlayerId,
  boardRef,
  boardRefKey,
  boardRefSchema,
  isPerPlayer,
  isPerPlayerBoardRef,
  isPlayerId,
  isSharedBoardRef,
  parseBoardRefKey,
  perPlayer,
  perPlayerBoardRef,
  perPlayerEntries,
  perPlayerGet,
  perPlayerHas,
  perPlayerKeys,
  perPlayerMap,
  perPlayerRequire,
  perPlayerSchema,
  perPlayerSet,
  perPlayerSize,
  perPlayerValues,
  sharedBoardRef,
  type BoardRef,
  type PerPlayer,
  type PerPlayerBoardRef,
  type PerPlayerSchemaOptions,
  type PlayerId,
  type SharedBoardRef,
} from "./reducer/per-player";
export {
  createReducerOps,
  type ReducerOps,
  type ReducerStateBase,
} from "./reducer/ops";
export {
  defineDerived,
  createDerivedResolver,
  type DerivedDefinition,
  type DerivedResolver,
} from "./reducer/derived";
// Flat `getX` table helpers were removed from the public surface in favour
// of the opinionated `q.*` namespace returned by `createTableQueries` /
// `createStateQueries` (also injected into every reducer callback as `q`).
export {
  assertCardAllowedInContainer,
  setActivePlayers,
} from "./reducer/table";
export {
  createTableQueries,
  createStateQueries,
} from "./reducer/table-queries";
export type {
  ActionContext,
  BoardBaseIdOfManifest,
  BoardLayoutOfManifest,
  BoardContainerIdOfTable,
  BoardContainerIdOfManifest,
  BoardIdOfManifest,
  BoardIdOfTable,
  BoardMapOfTable,
  BoardStateOfTable,
  BoardTypeIdOfManifest,
  BoardTypeIdOfTable,
  CardIdOfManifest,
  CardIdOfDeck,
  CardIdOfHand,
  CardIdOfState,
  CardIdOfTable,
  ChoiceOption,
  ContinuationInput,
  ContinuationSourceKind,
  ContinuationResponseOf,
  CompatibleCardIdForHandAndDeck,
  CompatibleHandIdForDeck,
  ComponentDataOfTable,
  ComponentLocationByTypeOfTable,
  ComponentLocationOfTable,
  ComponentIdOfTable,
  ContinuationCallable,
  ContinuationToken,
  DeckCardsOfTable,
  DeckIdOfState,
  DeckIdOfTable,
  DieIdOfManifest,
  EdgeTypeIdOfManifest,
  GameStateOf,
  HandCardsOfTable,
  HandIdOfState,
  HandIdOfTable,
  HexBoardIdOfTable,
  HexEdgeIdOfTable,
  HexEdgeTypeIdOfTable,
  HexSpaceIdOfTable,
  HexSpaceTypeIdOfTable,
  HexVertexIdOfTable,
  HexVertexTypeIdOfTable,
  InitContext,
  ManifestIdSchema,
  ManifestOf,
  PlayerIdOfManifest,
  PlayerZoneIdOfState,
  PlayerZoneIdOfManifest,
  PlayerZoneIdOfTable,
  PhaseMapOf,
  PhaseNameOf,
  PhaseNamesOfDefinition,
  PhaseDefinitionByName,
  PlayerIdOfState,
  PlayerIdOfTable,
  RelationTypeIdOfManifest,
  RelationTypeIdOfTable,
  ReducerAccept,
  ReducerReject,
  ReducerResult,
  ReducerValidationResult,
  ResolvedContainerLocation,
  RuntimeCardData,
  RuntimeCardVisibility,
  RuntimeDieData,
  RuntimeComponentLocation,
  RuntimeHandVisibilityMode,
  RuntimePayload,
  RuntimePieceData,
  RuntimeRecord,
  ResolvedDeckLocation,
  ResolvedEdgeLocation,
  ResolvedHandLocation,
  ResolvedSlotLocation,
  ResolvedSpaceLocation,
  ResolvedVertexLocation,
  ResolvedZoneLocation,
  RuntimeSetupSelection,
  RuntimeSetupSelectionInput,
  RuntimeTableRecord,
  RuntimeZoneMap,
  StaticBoards,
  PieceIdOfManifest,
  SquareBoardIdOfTable,
  SquareEdgeIdOfTable,
  SquareEdgeTypeIdOfTable,
  SquareSpaceIdOfTable,
  SquareSpaceTypeIdOfTable,
  SquareVertexIdOfTable,
  SquareVertexTypeIdOfTable,
  SetupBootstrapContainerRef,
  SetupBootstrapDestinationRef,
  SetupBootstrapPerPlayerContainerTemplateRef,
  SetupBootstrapStep,
  SetupSelectionInputOfManifest,
  SetupOptionChoiceMetadata,
  SetupOptionIdOfManifest,
  SetupOptionMetadata,
  SetupProfileDefinition,
  SetupProfileIdOfManifest,
  SetupProfileMetadata,
  SetupSelectionOfManifest,
  ReducerManifestContract,
  ResumableEffectKind,
  RollDieContinuationResponse,
  ShuffleSharedZoneContinuationResponse,
  EffectContinuationInput,
  EffectContinuationCallable,
  EffectContinuationResponse,
  SharedZoneIdOfManifest,
  SharedZoneIdOfState,
  SpaceIdOfManifest,
  SpaceIdOfTable,
  SpaceTypeIdOfManifest,
  SpaceTypeIdOfTable,
  SharedZoneIdOfTable,
  VertexTypeIdOfManifest,
  StaticViewDefinition,
  StaticViewQueries,
  ViewNamesOfDefinition,
  ViewOfDefinition,
  TiledBoardIdOfTable,
  TiledEdgeIdOfTable,
  TiledEdgeMap,
  TiledEdgeTypeIdOfTable,
  TiledSpaceIdOfTable,
  TiledSpaceMap,
  TableQueriesOfState,
  TiledVertexIdOfTable,
  TiledVertexMap,
  TiledVertexTypeIdOfTable,
  TableQueries,
  EffectDefinition,
  EffectMap,
  EffectRollDieDefinition,
  EffectShuffleDefinition,
  EffectIdsOfDefinition,
  InputCollector,
  InputCollectorKind,
  InteractionIdOfDefinition,
  InteractionIdOfDefinitionPhase,
  InteractionAvailabilityArgs,
  InteractionKind,
  InteractionMap,
  InteractionSpec,
  InteractionToArgs,
  InteractionValidateArgs,
  ClientParamsOf,
  ClientParamsOfInteractionOfDefinition,
  DefaultedClientParamKeysOfInteractionOfDefinition,
  ParamsOf,
  ParamsOfInteractionOfDefinition,
  BoardInteractionKeyOfDefinition,
  CardInteractionKeyOfDefinition,
  PlayableInteractionsOfZoneOfDefinition,
  PromptInteractionKeyOfDefinition,
  StageMap,
  StageNamesOfDefinitionPhase,
  StageSpec,
  ZoneIdsOfDefinition,
  PhaseZoneList,
} from "./reducer/model";
