export type {
  ActionDefinition,
  ActionInteractionDescriptor,
  ActionParameterDefinition,
  AvailableInteractionAvailability,
  BlockedInteractionAvailability,
  BoardCard,
  BoardContainerHostSpec,
  BoardContainerSpec,
  BoardEdgeRef,
  BoardHostSpec,
  BoardLayout,
  BoardRelationSpec,
  BoardSpaceSpec,
  BoardSpec,
  BoardTargetDomain,
  BoardTemplateSpec,
  BoardVertexRef,
  BoundedNumberDomain,
  CardPropertySchema,
  CardPropertySchemaVariants,
  CardSetDefinition,
  CardSetSourceType,
  CardTargetDomain,
  ChoiceDomain,
  ChoiceDomainOption,
  ChoiceListDomain,
  ComponentHomeSpec,
  ComponentSlotSpec,
  ComponentVisibilitySpec,
  ContainerHomeSpec,
  DetachedHomeSpec,
  DieSeedSpec,
  DieSlotHostRef,
  EdgeHomeSpec,
  GenericBoardSpec,
  GenericBoardTemplateSpec,
  HexBoardSpec,
  HexShape,
  HexCoordinate,
  HexSpaceOverride,
  HexEdgeRef,
  HexEdgeSpec,
  HexOrientation,
  HexSpaceSpec,
  HexVertexRef,
  HexVertexSpec,
  HistoryEntrySummary,
  HostActionSubmitResponse,
  HostEndedSessionSnapshot,
  HostGameplaySeatView,
  HostGameplaySessionSnapshot,
  HostGameplaySharedView,
  HostLobbySessionSnapshot,
  HostLobbyView,
  HostPlayerGameplayView,
  HostSessionContext,
  HostSessionEventCausation,
  HostSessionGameplayUpdatedEvent,
  HostSessionSnapshot,
  HostSessionStatus,
  InputDomain,
  InputSelection,
  InteractionAvailability,
  InteractionCommitPolicy,
  InteractionDescriptor,
  InteractionDescriptorBase,
  InteractionInputDescriptor,
  JsonValue,
  ManualCardSetDefinition,
  ManyInputSelection,
  NotYourTurnInteractionAvailability,
  ObjectSchema,
  ParameterType,
  PieceSeedSpec,
  PieceSlotHostRef,
  PieceTypeSpec,
  PlayerId,
  PlayersDefinition,
  PresetCardSetDefinition,
  PropertySchema,
  ResolvedBoardTargetDomain,
  ResolvedCardTargetDomain,
  ResourceDefinition,
  ResourceMapDomain,
  ResourceMapDomainEntry,
  SeatAssignment,
  SessionActor,
  SessionActorAuthUser,
  SessionActorDemoGuest,
  SessionGameSource,
  SessionGameSourceDemoRevision,
  SessionGameSourceUserCompiled,
  SessionSnapshotHistory,
  SessionSnapshotPhase,
  SimultaneousPhaseSnapshot,
  SingleInputSelection,
  SlotHomeSpec,
  SlotHostRef,
  SpaceHomeSpec,
  SpaceHostSpec,
  SquareBoardSpec,
  SquareBoardTemplateSpec,
  SquareEdgeSpec,
  SquareSpaceSpec,
  SquareVertexSpec,
  TopologyScope,
  VertexHomeSpec,
  ZoneHandles,
  ZoneHomeSpec,
  ZoneSpec,
  ZoneVisibility,
} from "./shared/domain/contracts.js";

export type {
  DieTypeSpec,
  GameTopologyManifest,
} from "./shared/domain/manifest.js";

export type { CardCollection, ViewCard } from "./shared/domain/cards.js";
export type { ViewSlotOccupant } from "./shared/domain/slots.js";
export { defineTopologyManifest } from "./reducer/manifest/authoring.js";
export type { TypedTopologyManifest } from "./reducer/manifest/authoring.js";
export {
  buildTypedRecord,
  expectTypedId,
  isTypedId,
} from "./reducer/manifest/generated-helpers.js";
export type {
  HexEdgeId,
  HexVertexId,
  HexSpaceId,
} from "./shared/domain/board-identities.js";
