import type { GameTopologyManifest } from "@dreamboard-games/sdk-types";

export const SETUP_PROFILES_SEED_MARKER =
  "Generated by dreamboard setup-profiles scaffold.";

function generateThinUiContractContent(): string {
  return `/**
 * Generated file.
 * Do not edit directly.
 */

import game from "../../app/game";
import {
  createGameUiContract,
  type GameUiBoardSurface,
  type GameUiCardCollectionSurface,
  type GameUiGameRootState,
  type GameUiHandSurface,
  type GameUiInteractionFormSurface,
  type GameUiInteractionKey,
  type GameUiInteractionRoutes,
  type GameUiMe,
  type GameUiPhaseName,
  type GameUiPlayers,
  type GameUiTurn,
  type GameUiView,
} from "@dreamboard-games/sdk/runtime/workspace-contract";
import type { DreamboardUI } from "@dreamboard-games/sdk/runtime";
import {
  literals,
  staticBoards,
  type BoardBaseId,
  type CardId,
  type CardProperties,
  type CardType,
  type EdgeId,
  type PlayerId,
  type ResourceId,
  type SpaceId,
  type VertexId,
  type ZoneId,
} from "../manifest-contract";

type GameDefinition = typeof game;
type RuntimeBoundary = DreamboardUI;
type PlayerCardZoneId = {
  [Zone in (typeof literals.playerZoneIds)[number]]:
    (typeof literals.cardSetIdsByPlayerZoneId)[Zone] extends readonly []
      ? never
      : Zone;
}[(typeof literals.playerZoneIds)[number]];
type SharedCardZoneId = {
  [Zone in (typeof literals.sharedZoneIds)[number]]:
    (typeof literals.cardSetIdsBySharedZoneId)[Zone] extends readonly []
      ? never
      : Zone;
}[(typeof literals.sharedZoneIds)[number]];
type ManifestTypes = {
  PlayerId: PlayerId & string;
  ResourceId: ResourceId & string;
  ZoneId: ZoneId & string;
  CardId: [CardId] extends [never] ? string : CardId & string;
  CardType: [CardType] extends [never] ? string : CardType & string;
  CardProperties: CardProperties extends Record<string, unknown>
    ? CardProperties
    : Record<string, unknown>;
  BoardBaseId: BoardBaseId & string;
  SpaceId: SpaceId & string;
  EdgeId: EdgeId & string;
  VertexId: VertexId & string;
  PlayerCardZoneId: PlayerCardZoneId & string;
  CardZoneId: (PlayerCardZoneId | SharedCardZoneId) & string;
};

const contract = createGameUiContract<
  GameDefinition,
  ManifestTypes,
  typeof staticBoards.hex,
  typeof staticBoards.square
>({
  game,
  resourceIds: literals.resourceIds as readonly ResourceId[],
  resourcePresentationById: literals.resourcePresentationById,
  hexStaticBoards: staticBoards.hex,
  squareStaticBoards: staticBoards.square,
});

export const uiContract = contract.uiContract;
export const UI = contract.UI;
export const clientParamSchemasByPhase = contract.clientParamSchemasByPhase;
export const Board = UI.Board;
export const Zone = UI.Zone;
export const Game = UI.Game;
export const Interaction = UI.Interaction;
export const PlayerRoster = UI.PlayerRoster;
export const Dice = UI.Dice;
export const Phase = UI.Phase;
export const ResourceCounter = UI.ResourceCounter;

export type ViewName = import("@dreamboard-games/sdk/runtime/workspace-contract").GameUiViewName<GameDefinition>;
export type GameView = GameUiView<GameDefinition>;
export type PhaseName = GameUiPhaseName<GameDefinition>;
export type GameRootState = GameUiGameRootState<GameDefinition, ManifestTypes>;
export type GamePlayers = GameUiPlayers<ManifestTypes>;
export type GameMe = GameUiMe<ManifestTypes>;
export type GameTurn = GameUiTurn<GameDefinition, ManifestTypes>;
export type InteractionKey = GameUiInteractionKey<GameDefinition>;
export type InteractionRoutes = GameUiInteractionRoutes<GameDefinition>;
export type InteractionFormSurface<Key extends InteractionKey> =
  GameUiInteractionFormSurface<GameDefinition, typeof uiContract, Key>;
export type BoardSurface<
  Board extends ManifestTypes["BoardBaseId"] = ManifestTypes["BoardBaseId"],
> = GameUiBoardSurface<ManifestTypes, Board>;
export type HandSurface<
  Zones extends readonly ManifestTypes["ZoneId"][] = readonly ManifestTypes["ZoneId"][],
> = GameUiHandSurface<ManifestTypes, Zones>;
export type CardCollectionSurface<
  Zones extends readonly ManifestTypes["ZoneId"][] = readonly ManifestTypes["ZoneId"][],
> = GameUiCardCollectionSurface<ManifestTypes, Zones>;

declare module "@dreamboard-games/sdk/runtime" {
  interface DreamboardUIRegister {
    contract: GameDefinition;
    ui: typeof uiContract;
  }
}
`;
}

function generateReducerSupportSeed(): string {
  return `import {
  createReducerEdit,
  createStateQueries,
} from "@dreamboard-games/sdk/reducer";
import type { GameState } from "./game-contract";

/**
 * Small, SDK-shaped reducer helpers belong here.
 *
 * Keep schema and contract declarations in app/game-contract.ts.
 * Keep initial state callbacks and defineGame wiring in app/game.ts.
 * Keep memoized aggregates (winner checks, VP totals, longest-road,
 * largest-army) in app/derived.ts via \`defineDerived\`.
 * Keep phase files focused on one game-flow state.
 *
 * When this file starts collecting real game rules, split them by domain
 * under app/rules/ instead, for example app/rules/board.ts,
 * app/rules/resources.ts, or app/rules/scoring.ts.
 *
 * Recommended authoring pattern inside a phase reducer:
 *
 *   const tx = edit(state);
 *   tx.setActivePlayers([q.players.order()[0]]);
 *   return accept(tx.state);
 */

export const edit = createReducerEdit<GameState>();

export function stateQueries(state: GameState) {
  return createStateQueries(state);
}
`;
}

function generateAppReadmeSeed(): string {
  return `# App organization

This directory owns the reducer: game state schemas, phases, interactions,
derived values, player views, and reducer helpers.

Use this layout while the game is small:

\`\`\`txt
app/
  game-contract.ts
  authoring.ts
  game.ts
  derived.ts
  reducer-support.ts
  phases/
    setup.ts
\`\`\`

When a phase grows beyond a single idea, make the phase directory the table of
contents and split the implementation by game concept:

\`\`\`txt
app/phases/player-turn/
  index.ts          # bound phase assembly only
  state.ts          # phase-local constants and types
  inputs.ts         # shared input and presentation helpers
  build.ts          # build interactions
  trade.ts          # trade interactions
  end-turn.ts       # end-turn interaction
\`\`\`

Split a phase when it has multiple action families, shared input helpers, card
actions, or is roughly 250-300 lines. Keep \`index.ts\` as the assembly point
that imports interactions and registers them with its bound phase object.

Do not turn \`reducer-support.ts\` into a catch-all rule module. Keep it small
for shared reducer plumbing; put real game rules under \`app/rules/*\` once
there is more than one domain.
`;
}

function generateReducerDerivedSeed(): string {
  return `// Memoized, pure projections of reducer state. Read them from reducer
// callbacks and view projections via the injected \`derived\` helper:
//
//   reduce({ state, derived, accept }) {
//     const winner = derived(winnerOf);
//     return accept({ ...state, publicState: { ...state.publicState, currentLeaderId: winner } });
//   }
//
// Do NOT mirror derived values back into \`publicState\`. Keep the raw
// inputs (component locations, zone contents, counters) in state and
// express aggregates here.
//
// Uncomment the example below once you have something to derive.

// import { defineDerived } from "@dreamboard-games/sdk/reducer";
// import type { GameContract } from "./game-contract";
//
// export const winnerOf = defineDerived<GameContract>()({
//   name: "winnerOf",
//   compute: ({ state }) => {
//     // Example: return the first player at or above the VP target.
//     return state.publicState.currentLeaderId ?? null;
//   },
// });

export {};
`;
}

function generateReducerGameContractSeed(): string {
  return `import { z } from "zod";
import { ids, manifestContract } from "../shared/manifest-contract";
import { defineGameContract, type GameStateOf } from "@dreamboard-games/sdk/reducer";

// Contract files should stay focused on schemas, phases, and exported
// state types. Put reducers in app/phases/* and pure computations in
// app/derived.ts or app/rules/*.
const publicStateSchema = z.object({
  currentPlayerId: ids.playerId.nullable(),
  notesByPlayerId: z.partialRecord(ids.playerId, z.string()).default({}),
});
const privateStateSchema = z.object({});
const hiddenStateSchema = z.object({});

export const gameContract = defineGameContract({
  manifest: manifestContract,
  state: {
    public: publicStateSchema,
    private: privateStateSchema,
    hidden: hiddenStateSchema,
  },
  phases: {
    setup: z.object({}),
  },
  errors: {},
});

export type GameContract = typeof gameContract;
export type GameState = GameStateOf<GameContract>;
`;
}

function generateReducerAuthoringSeed(): string {
  return `import { createContractAuthoring } from "@dreamboard-games/sdk/reducer";
import { gameContract } from "./game-contract";

export const authoring = createContractAuthoring(gameContract);
`;
}

function generateReducerGameSeed(): string {
  return `import { authoring } from "./authoring";
import { phases } from "./phases";
import setupProfiles from "./setup-profiles";

// Keep this file as the defineGame assembly point. Put rules in phases,
// projections in views/derived modules, and reusable domain helpers in
// app/rules/* once reducer-support.ts is no longer small.
export default authoring.game({
  initial: {
    public: ({ playerIds }) => ({
      currentPlayerId: playerIds[0] ?? null,
      notesByPlayerId: {},
    }),
    private: () => ({}),
    hidden: () => ({}),
  },
  initialPhase: "setup",
  setupProfiles,
  phases,
  views: {
    shared: authoring.emptyView(),
    player: authoring.emptyView(),
  },
});
`;
}

function generateSetupProfilesSeed(manifest: GameTopologyManifest): string {
  const setupProfiles = manifest.setupProfiles ?? [];
  const setupProfileEntries =
    setupProfiles.length === 0
      ? ""
      : `{\n${setupProfiles
          .map((profile) => `  ${JSON.stringify(profile.id)}: {},`)
          .join("\n")}\n}`;

  return `// ${SETUP_PROFILES_SEED_MARKER}
import { setupProfiles } from "../shared/manifest-contract";

export default setupProfiles(${setupProfileEntries || "{}"});
`;
}

export function isFrameworkOwnedSetupProfilesSeed(
  content: string | null | undefined,
): boolean {
  if (content === null || content === undefined) {
    return false;
  }
  const trimmed = content.trim();
  if (trimmed.length === 0) {
    return true;
  }
  if (trimmed.includes(SETUP_PROFILES_SEED_MARKER)) {
    return true;
  }
  return false;
}

function generateSetupPhaseSeed(): string {
  return `import { authoring } from "../authoring";
import { edit } from "../reducer-support";

const setup = authoring.phase("setup");

const setupMoodChoices = [
  { value: "ready", label: "Ready" },
  { value: "exploring", label: "Exploring" },
] as const;
type SetupMood = (typeof setupMoodChoices)[number]["value"];

// A single phase file is fine while the phase is small. When a phase grows
// multiple action families, move it to app/phases/<phase>/index.ts and split
// interactions into neighboring concept files.
export const setupPhase = setup.define({
  kind: "player",
  initialState: () => ({}),
  actor: ({ state }) => state.publicState.currentPlayerId,
  interactions: {
    submit: setup.interaction({
      inputs: {
        mood: setup.inputs.form.choice<SetupMood>({
          choices: setupMoodChoices,
          defaultValue: "ready",
        }),
      },
      reduce({ state, input, accept }) {
        const tx = edit(state);
        tx.patchPublicState({
          notesByPlayerId: {
            ...state.publicState.notesByPlayerId,
            [input.playerId]: input.params.mood,
          },
        });
        return accept(tx.state);
      },
    }),
  },
});
`;
}

function generatePhaseIndexSeed(): string {
  return `import { setupPhase } from "./setup";
import type { GameContract } from "../game-contract";
import type { PhaseMapOf } from "@dreamboard-games/sdk/reducer";

export const phases = {
  setup: setupPhase,
} satisfies PhaseMapOf<GameContract>;
`;
}

function generateReducerAppIndex(): string {
  return `import game from "./game";
import { createReducerBundle } from "@dreamboard-games/sdk/reducer";

export default createReducerBundle(game);
`;
}

function generateAppFrameworkTsConfig(): string {
  return `${JSON.stringify(
    {
      compilerOptions: {
        target: "ES2020",
        module: "ESNext",
        moduleResolution: "bundler",
        resolveJsonModule: true,
        strict: true,
        esModuleInterop: true,
        skipLibCheck: false,
        types: [],
        declaration: false,
        rootDir: "..",
        outDir: "./dist",
        paths: {
          "@dreamboard/manifest-contract": ["../shared/manifest-contract.ts"],
          "#dreamboard/ui-contract": ["../shared/generated/ui-contract.ts"],
          "@shared/*": ["../shared/*"],
        },
      },
      include: [
        "./**/*.ts",
        "./**/*.d.ts",
        "../shared/manifest-*.ts",
        "../shared/manifest-*.d.ts",
        "../shared/manifest-*.json",
      ],
      exclude: ["node_modules", "dist", "../shared/generated"],
    },
    null,
    2,
  )}\n`;
}

function generateUiFrameworkTsConfig(): string {
  return `${JSON.stringify(
    {
      compilerOptions: {
        target: "ES2020",
        module: "ESNext",
        moduleResolution: "bundler",
        resolveJsonModule: true,
        jsx: "react-jsx",
        strict: true,
        esModuleInterop: true,
        skipLibCheck: false,
        types: [],
        paths: {
          "@dreamboard/manifest-contract": ["../shared/manifest-contract.ts"],
          "#dreamboard/ui-contract": ["../shared/generated/ui-contract.ts"],
          "@shared/*": ["../shared/*"],
        },
      },
      include: [
        "./**/*.ts",
        "./**/*.tsx",
        "../shared/**/*.ts",
        "../shared/**/*.json",
      ],
      exclude: ["node_modules", "dist"],
    },
    null,
    2,
  )}\n`;
}

function generateReducerUiAppContent(): string {
  return `import { Game, Interaction, Phase, UI } from "#dreamboard/ui-contract";
import { SetupInteractionRoutes } from "./interaction-routes";
import { SetupScreen } from "./setup-screen";

function SetupPhase() {
  const setupForm = Interaction.useForm("setup.submit");

  return (
    <>
      <SetupScreen />
      <SetupInteractionRoutes form={setupForm} />
    </>
  );
}

export default function App() {
  return (
    <UI.Root>
      <Game.Root>
        {() => (
          <Phase.Switch
            routes={{
              setup: () => <SetupPhase />,
            }}
          />
        )}
      </Game.Root>
    </UI.Root>
  );
}
`;
}

function generateReducerUiSetupScreenContent(): string {
  return `import { PANEL_CLASS, SHELL_CLASS } from "./styles";

export function SetupScreen() {
  return (
    <main className={SHELL_CLASS}>
      <section className={PANEL_CLASS}>
        <p className="text-xs font-bold uppercase tracking-[0.14em] text-slate-500">
          Setup
        </p>
        <h1 className="text-2xl font-bold text-slate-950">Your game starts here</h1>
        <p className="max-w-prose text-sm leading-6 text-slate-600">
          Replace this screen with your board, hands, mats, and table state.
          Keep interaction wiring in the route file so visual components stay
          focused on layout and styling.
        </p>
      </section>
    </main>
  );
}
`;
}

function generateReducerUiInteractionRoutesContent(): string {
  return `import {
  Interaction,
  type InteractionFormSurface,
} from "#dreamboard/ui-contract";
import { ACTION_BUTTON_CLASS, PANEL_CLASS } from "./styles";

export function SetupInteractionRoutes({
  form,
}: {
  form: InteractionFormSurface<"setup.submit">;
}) {
  return (
    <>
      <Interaction.Routes
        routes={{
          "setup.submit": {
            collect: {
              mood: form.slot.mood,
            },
          },
        }}
      />
      <aside className={PANEL_CLASS}>
        <div className="grid gap-2">
          <p className="text-sm font-bold text-slate-950">Ready check</p>
          <form.slot.mood.Field />
          <form.Submit className={ACTION_BUTTON_CLASS}>
            Start building
          </form.Submit>
        </div>
      </aside>
    </>
  );
}
`;
}

function generateReducerUiStylesContent(): string {
  return `export const SHELL_CLASS =
  "min-h-screen bg-[#f8fafc] p-6 text-slate-950";

export const PANEL_CLASS =
  "mx-auto grid max-w-3xl gap-4 rounded-lg border border-slate-200 bg-white p-5 shadow-sm";

export const ACTION_BUTTON_CLASS =
  "rounded-md bg-slate-950 px-4 py-2 text-sm font-bold text-white disabled:cursor-not-allowed disabled:opacity-50";
`;
}

function generateReducerUiContractTypingSmokeContent(): string {
  return `import { Interaction } from "#dreamboard/ui-contract";

export function UiContractTypingSmoke() {
  const form = Interaction.useForm("setup.submit");

  return (
    <Interaction.Routes
      routes={{
        "setup.submit": {
          collect: {
            mood: form.slot.mood,
          },
        },
      }}
    />
  );
}

// @ts-expect-error generated contracts hide legacy interaction roots.
Interaction.Root({ interaction: "setup.submit", children: null });
`;
}

export function generateSeedFiles(
  manifest: GameTopologyManifest,
): Record<string, string> {
  return {
    "app/README.md": generateAppReadmeSeed(),
    "ui/App.tsx": generateReducerUiAppContent(),
    "ui/interaction-routes.tsx": generateReducerUiInteractionRoutesContent(),
    "ui/setup-screen.tsx": generateReducerUiSetupScreenContent(),
    "ui/styles.ts": generateReducerUiStylesContent(),
    "ui/ui-contract-typing-smoke.tsx":
      generateReducerUiContractTypingSmokeContent(),
    "app/game-contract.ts": generateReducerGameContractSeed(),
    "app/authoring.ts": generateReducerAuthoringSeed(),
    "app/game.ts": generateReducerGameSeed(),
    "app/setup-profiles.ts": generateSetupProfilesSeed(manifest),
    "app/reducer-support.ts": generateReducerSupportSeed(),
    "app/derived.ts": generateReducerDerivedSeed(),
    "app/phases/setup.ts": generateSetupPhaseSeed(),
    "app/phases/index.ts": generatePhaseIndexSeed(),
  };
}

export function generateAuthoritativeIndexFile(
  _manifest: GameTopologyManifest,
): string {
  return generateReducerAppIndex();
}

export function generateFrameworkFiles(
  manifest: GameTopologyManifest,
): Record<string, string> {
  return {
    "app/tsconfig.framework.json": generateAppFrameworkTsConfig(),
    "ui/tsconfig.framework.json": generateUiFrameworkTsConfig(),
    "shared/generated/ui-contract.ts": generateThinUiContractContent(),
    "app/index.ts": generateAuthoritativeIndexFile(manifest),
  };
}
