export {
  canonicalUIFixtureJson,
  canonicalizeUIFixtureJson,
  canonicalizeUIScenarioFixture,
  digestUIFixtureJson,
  digestUIFixtureRequest,
  digestUIFixtureTransportRequest,
  digestPluginProtocolTape,
  digestUIScenarioFixture,
  isSha256Digest,
  serializeUIScenarioFixture,
} from "./canonical.js";
export {
  compareUIParityObservations,
  createUIParityObservationFromFixture,
  parseUIParityObservation,
  parseUIParityRealHostReceipt,
  parseUIParityRunInput,
  type CreateUIParityObservationFromFixtureOptions,
  type UIParityArtifactReference,
  type UIParityComparisonFailure,
  type UIParityComparisonResult,
  type UIParityDiagnostic,
  type UIParityFailureCode,
  type UIParityObservation,
  type UIParityObservationCheckpoint,
  type UIParityObservationEnvironment,
  type UIParityObservationProvenance,
  type UIParityRealHostReceipt,
  type UIParityReceiptComparison,
  type UIParityRunInput,
  type UIParityRunScenario,
  type UIParityViewport,
} from "./parity.js";
export {
  createFixtureHostHarness,
  type CreateFixtureHostHarnessOptions,
  type FixtureHostEvent,
  type FixtureHostHarness,
} from "./create-fixture-host-harness.js";
export { FixturePluginRuntime } from "./FixturePluginRuntime.js";
export {
  compilePluginProtocolTape,
  type CompilePluginProtocolTapeOptions,
} from "./compile-plugin-protocol-tape.js";
export {
  createDeterministicIdFactory,
  defaultFixtureEnvironmentInit,
  fixtureEnvironmentInitFor,
  type DeterministicIdFactory,
  type FixtureEnvironmentInit,
} from "./deterministic-environment.js";
export {
  assertDeterministicUIScenarioFixture,
  assertUIStepExpectationSatisfied,
  assertUniqueReplayIdentity,
  compileUIScenarioFixture,
  type CompileUIScenarioFixtureOptions,
  type UIReplayIdentityCandidate,
} from "./compiler.js";
export {
  UI_SCENARIO_FIXTURE_BUNDLE_SCHEMA_VERSION,
  UI_SCENARIO_FIXTURE_PLUGIN_RUNTIME_PROTOCOL,
  UI_SCENARIO_FIXTURE_SCHEMA_VERSION,
  UI_SCENARIO_FIXTURE_SUPPORTED_BROWSER_PROTOCOL_MAJOR,
  assertSupportedBrowserInteractionProtocol,
  parseUIScenarioFixture,
  parseUIScenarioFixtureBundleIndex,
  pluginProtocolTapeSchema,
  portableSemanticReplayStepSchema,
  uiFixtureFrameSchema,
  uiFixtureProtocolStepSchema,
  uiReplayExecutionSchema,
  uiReplayRequestSchema,
  uiResolvedReplayIdentitySchema,
  uiScenarioFixtureBundleIndexSchema,
  uiScenarioFixtureSchema,
  uiScenarioReplayStepSchema,
  uiStepExpectationSchema,
  type PluginProtocolTape,
  type PortableSemanticReplayStep,
  type UIFixtureFrame,
  type UIFixtureProtocolStep,
  type UIReplayExecution,
  type UIReplayRequest,
  type UIResolvedReplayIdentity,
  type UIScenarioFixture,
  type UIScenarioFixtureBundleIndex,
  type UIScenarioReplayStep,
  type UIStepExpectation,
} from "./schema.js";
