export {
  canonicalUIFixtureJson,
  canonicalizeUIFixtureJson,
  canonicalizeUIScenarioFixture,
  digestUIFixtureJson,
  digestUIFixtureRequest,
  digestUIFixtureTransportRequest,
  digestUIScenarioFixture,
  isSha256Digest,
  serializeUIScenarioFixture,
} from "./canonical.js";
export {
  createFixtureRuntime,
  type CreateFixtureRuntimeOptions,
  type FixtureRuntimeEvent,
  type FixtureRuntimeHarness,
} from "./create-fixture-runtime.js";
export { FixturePluginRuntime } from "./FixturePluginRuntime.js";
export {
  createDeterministicIdFactory,
  defaultFixtureEnvironmentInit,
  fixtureEnvironmentInitFor,
  type DeterministicIdFactory,
  type FixtureEnvironmentInit,
} from "./deterministic-environment.js";
export {
  assertDeterministicUIScenarioFixture,
  assertUIStepExpectationSatisfied,
  assertUniqueReplayIdentity,
  compileUIScenarioFixture,
  type CompileUIScenarioFixtureOptions,
  type UIReplayIdentityCandidate,
} from "./compiler.js";
export {
  UI_SCENARIO_FIXTURE_BUNDLE_SCHEMA_VERSION,
  UI_SCENARIO_FIXTURE_SCHEMA_VERSION,
  UI_SCENARIO_FIXTURE_SUPPORTED_BROWSER_PROTOCOL_MAJOR,
  assertSupportedBrowserInteractionProtocol,
  parseUIScenarioFixture,
  parseUIScenarioFixtureBundleIndex,
  portableSemanticReplayStepSchema,
  uiFixtureFrameSchema,
  uiFixturePluginStateSnapshotSchema,
  uiFixtureTransportExchangeSchema,
  uiReplayExecutionSchema,
  uiReplayRequestSchema,
  uiResolvedReplayIdentitySchema,
  uiScenarioFixtureBundleIndexSchema,
  uiScenarioFixtureSchema,
  uiScenarioReplayStepSchema,
  uiStepExpectationSchema,
  type PortableSemanticReplayStep,
  type UIFixtureFrame,
  type UIFixtureTransportExchange,
  type UIReplayExecution,
  type UIReplayRequest,
  type UIResolvedReplayIdentity,
  type UIScenarioFixture,
  type UIScenarioFixtureBundleIndex,
  type UIScenarioReplayStep,
  type UIStepExpectation,
} from "./schema.js";
