/**
 * Generated file.
 * Do not edit directly.
 */

export const literals = {
  playerIds: ["player-1", "player-2", "player-3", "player-4", "player-5"] as const,
  phaseNames: [] as readonly string[],
  boardLayouts: ["generic", "hex", "square"] as const,
  setupOptionIds: [] as const,
  setupProfileIds: ["standard"] as const,
  cardSetIds: ["market-cards"] as const,
  cardTypes: ["festival-banner", "lantern", "tea-cup"] as const,
  cardIds: ["festival-banner-1", "festival-banner-10", "festival-banner-11", "festival-banner-12", "festival-banner-13", "festival-banner-14", "festival-banner-15", "festival-banner-16", "festival-banner-17", "festival-banner-18", "festival-banner-19", "festival-banner-2", "festival-banner-20", "festival-banner-3", "festival-banner-4", "festival-banner-5", "festival-banner-6", "festival-banner-7", "festival-banner-8", "festival-banner-9", "lantern-1", "lantern-10", "lantern-11", "lantern-12", "lantern-13", "lantern-14", "lantern-15", "lantern-16", "lantern-17", "lantern-18", "lantern-19", "lantern-2", "lantern-20", "lantern-3", "lantern-4", "lantern-5", "lantern-6", "lantern-7", "lantern-8", "lantern-9", "tea-cup-1", "tea-cup-10", "tea-cup-11", "tea-cup-12", "tea-cup-13", "tea-cup-14", "tea-cup-15", "tea-cup-16", "tea-cup-17", "tea-cup-18", "tea-cup-19", "tea-cup-2", "tea-cup-20", "tea-cup-3", "tea-cup-4", "tea-cup-5", "tea-cup-6", "tea-cup-7", "tea-cup-8", "tea-cup-9"] as const,
  deckIds: ["market-deck"] as const,
  handIds: ["hand", "scored-history", "stall"] as const,
  sharedZoneIds: ["market-deck"] as const,
  playerZoneIds: ["hand", "scored-history", "stall"] as const,
  zoneIds: ["hand", "market-deck", "scored-history", "stall"] as const,
  resourceIds: [] as const,
  resourcePresentationById: {} as const,
  pieceTypeIds: [] as const,
  pieceIds: [] as const,
  dieTypeIds: [] as const,
  dieIds: [] as const,
  boardTemplateIds: [] as const,
  boardTypeIds: [] as const,
  boardBaseIds: [] as const,
  boardIds: [] as const,
  boardContainerIds: [] as const,
  relationTypeIds: [] as const,
  edgeIds: [] as const,
  edgeTypeIds: [] as const,
  vertexIds: [] as const,
  vertexTypeIds: [] as const,
  spaceIds: [] as const,
  spaceTypeIds: [] as const,
  handVisibilityById: {
  "hand": "ownerOnly",
  "scored-history": "public",
  "stall": "public",
} as const,
  zoneVisibilityById: {
  "hand": "ownerOnly",
  "market-deck": "hidden",
  "scored-history": "public",
  "stall": "public",
} as const,
  cardSetIdByCardId: {
  "festival-banner-1": "market-cards",
  "festival-banner-10": "market-cards",
  "festival-banner-11": "market-cards",
  "festival-banner-12": "market-cards",
  "festival-banner-13": "market-cards",
  "festival-banner-14": "market-cards",
  "festival-banner-15": "market-cards",
  "festival-banner-16": "market-cards",
  "festival-banner-17": "market-cards",
  "festival-banner-18": "market-cards",
  "festival-banner-19": "market-cards",
  "festival-banner-2": "market-cards",
  "festival-banner-20": "market-cards",
  "festival-banner-3": "market-cards",
  "festival-banner-4": "market-cards",
  "festival-banner-5": "market-cards",
  "festival-banner-6": "market-cards",
  "festival-banner-7": "market-cards",
  "festival-banner-8": "market-cards",
  "festival-banner-9": "market-cards",
  "lantern-1": "market-cards",
  "lantern-10": "market-cards",
  "lantern-11": "market-cards",
  "lantern-12": "market-cards",
  "lantern-13": "market-cards",
  "lantern-14": "market-cards",
  "lantern-15": "market-cards",
  "lantern-16": "market-cards",
  "lantern-17": "market-cards",
  "lantern-18": "market-cards",
  "lantern-19": "market-cards",
  "lantern-2": "market-cards",
  "lantern-20": "market-cards",
  "lantern-3": "market-cards",
  "lantern-4": "market-cards",
  "lantern-5": "market-cards",
  "lantern-6": "market-cards",
  "lantern-7": "market-cards",
  "lantern-8": "market-cards",
  "lantern-9": "market-cards",
  "tea-cup-1": "market-cards",
  "tea-cup-10": "market-cards",
  "tea-cup-11": "market-cards",
  "tea-cup-12": "market-cards",
  "tea-cup-13": "market-cards",
  "tea-cup-14": "market-cards",
  "tea-cup-15": "market-cards",
  "tea-cup-16": "market-cards",
  "tea-cup-17": "market-cards",
  "tea-cup-18": "market-cards",
  "tea-cup-19": "market-cards",
  "tea-cup-2": "market-cards",
  "tea-cup-20": "market-cards",
  "tea-cup-3": "market-cards",
  "tea-cup-4": "market-cards",
  "tea-cup-5": "market-cards",
  "tea-cup-6": "market-cards",
  "tea-cup-7": "market-cards",
  "tea-cup-8": "market-cards",
  "tea-cup-9": "market-cards",
} as const,
  cardTypeByCardId: {
  "festival-banner-1": "festival-banner",
  "festival-banner-10": "festival-banner",
  "festival-banner-11": "festival-banner",
  "festival-banner-12": "festival-banner",
  "festival-banner-13": "festival-banner",
  "festival-banner-14": "festival-banner",
  "festival-banner-15": "festival-banner",
  "festival-banner-16": "festival-banner",
  "festival-banner-17": "festival-banner",
  "festival-banner-18": "festival-banner",
  "festival-banner-19": "festival-banner",
  "festival-banner-2": "festival-banner",
  "festival-banner-20": "festival-banner",
  "festival-banner-3": "festival-banner",
  "festival-banner-4": "festival-banner",
  "festival-banner-5": "festival-banner",
  "festival-banner-6": "festival-banner",
  "festival-banner-7": "festival-banner",
  "festival-banner-8": "festival-banner",
  "festival-banner-9": "festival-banner",
  "lantern-1": "lantern",
  "lantern-10": "lantern",
  "lantern-11": "lantern",
  "lantern-12": "lantern",
  "lantern-13": "lantern",
  "lantern-14": "lantern",
  "lantern-15": "lantern",
  "lantern-16": "lantern",
  "lantern-17": "lantern",
  "lantern-18": "lantern",
  "lantern-19": "lantern",
  "lantern-2": "lantern",
  "lantern-20": "lantern",
  "lantern-3": "lantern",
  "lantern-4": "lantern",
  "lantern-5": "lantern",
  "lantern-6": "lantern",
  "lantern-7": "lantern",
  "lantern-8": "lantern",
  "lantern-9": "lantern",
  "tea-cup-1": "tea-cup",
  "tea-cup-10": "tea-cup",
  "tea-cup-11": "tea-cup",
  "tea-cup-12": "tea-cup",
  "tea-cup-13": "tea-cup",
  "tea-cup-14": "tea-cup",
  "tea-cup-15": "tea-cup",
  "tea-cup-16": "tea-cup",
  "tea-cup-17": "tea-cup",
  "tea-cup-18": "tea-cup",
  "tea-cup-19": "tea-cup",
  "tea-cup-2": "tea-cup",
  "tea-cup-20": "tea-cup",
  "tea-cup-3": "tea-cup",
  "tea-cup-4": "tea-cup",
  "tea-cup-5": "tea-cup",
  "tea-cup-6": "tea-cup",
  "tea-cup-7": "tea-cup",
  "tea-cup-8": "tea-cup",
  "tea-cup-9": "tea-cup",
} as const,
  setupChoiceIdsByOptionId: {

} as const,
  cardSetIdsBySharedZoneId: {
  "market-deck": ["market-cards"] as const,
} as const,
  sharedZoneIdsByCardSetId: {
  "market-cards": ["market-deck"] as const,
} as const,
  homeSharedZoneIdsByCardType: {
  "festival-banner": [] as const,
  "lantern": [] as const,
  "tea-cup": [] as const,
} as const,
  homeSharedZoneIdByCardType: {

} as const,
  cardSetIdsByPlayerZoneId: {
  "hand": ["market-cards"] as const,
  "scored-history": ["market-cards"] as const,
  "stall": ["market-cards"] as const,
} as const,
} as const;
