import { defineConfig } from "tsup";

export default defineConfig({
  entry: [
    "src/index.ts",
    "src/package-set.ts",
    "src/types.ts",
    "src/reducer.ts",
    "src/ui.ts",
    "src/ui/components.ts",
    "src/ui/defaults.ts",
    "src/ui/types/player-state.ts",
    "src/testing.ts",
    "src/runtime.ts",
    "src/runtime/primitives.ts",
    "src/runtime/workspace-contract.ts",
    "src/runtime/types/runtime-api.ts",
    "src/generated/runtime.ts",
    "src/generated/runtime-api.ts",
    "src/generated/runtime/primitives.ts",
    "src/generated/workspace-contract.ts",
    "src/infrastructure/reducer-bundle-abi.ts",
    "src/infrastructure/workspace-codegen.ts",
  ],
  format: ["esm"],
  platform: "neutral",
  target: "node24",
  outDir: "dist",
  dts: true,
  clean: true,
  sourcemap: true,
  splitting: false,
  external: [
    "@radix-ui/react-dialog",
    "@radix-ui/react-accordion",
    "@radix-ui/react-label",
    "@radix-ui/react-select",
    "@radix-ui/react-slot",
    "@radix-ui/react-tooltip",
    "@use-gesture/react",
    "clsx",
    "framer-motion",
    "lucide-react",
    "react",
    "react-dom",
    "vaul",
    "zod",
    "zustand",
    "zustand/shallow",
    "zustand/vanilla",
  ],
});
