import { defineUIContract, type UIContractDefinition } from "./ui-contract.js";

export type {
  UIContractCapability,
  UIContractDefinition,
  UIContractKind,
} from "./ui-contract.js";

export const UI_CONTRACTS = [
  defineUIContract({
    id: "ActionButton",
    kind: "component",
    owner: "sdk-ui",
    publicExport: "ActionButton",
    sourceFiles: [
      "packages/sdk/src/ui/components/ActionButton.tsx",
      "packages/sdk/src/ui/stories/Buttons.stories.tsx",
    ],
    storyIds: ["buttons--action-button-states", "panels--compact-panel"],
    requiredCapabilities: ["click", "keyboard"],
  }),
  defineUIContract({
    id: "ActionPanel",
    kind: "component",
    owner: "sdk-ui",
    publicExport: "ActionPanel",
    sourceFiles: [
      "packages/sdk/src/ui/components/ActionPanel.tsx",
      "packages/sdk/src/ui/stories/Panels.stories.tsx",
    ],
    storyIds: ["panels--compact-panel", "panels--focus-order"],
    requiredCapabilities: ["click", "keyboard", "responsive-layout"],
  }),
  defineUIContract({
    id: "CardDragSurface",
    kind: "component",
    owner: "sdk-ui",
    publicExport: "CardDragSurface",
    sourceFiles: [
      "packages/sdk/src/ui/components/card-drag/CardDragSurface.tsx",
      "packages/sdk/src/runtime/primitives/hand-surface.tsx",
      "packages/sdk/src/ui/stories/HandView.stories.tsx",
    ],
    storyIds: [
      "hands-handview--drag-to-target-surface-layout",
      "hands-handview--drag-to-target-pointer-drop",
    ],
    requiredCapabilities: ["pointer-drag", "touch-drag", "keyboard"],
  }),
  defineUIContract({
    id: "CardDropTargetView",
    kind: "component",
    owner: "sdk-ui",
    publicExport: "CardDropTargetView",
    sourceFiles: [
      "packages/sdk/src/ui/components/card-drag/CardDropTargetView.tsx",
      "packages/sdk/src/runtime/primitives/hand-surface.tsx",
      "packages/sdk/src/ui/stories/HandView.stories.tsx",
    ],
    storyIds: [
      "hands-handview--drag-to-target-surface-layout",
      "hands-handview--drag-to-target-keyboard-drop",
    ],
    requiredCapabilities: ["pointer-drag", "keyboard", "runtime-draft"],
  }),
  defineUIContract({
    id: "CardFace",
    kind: "component",
    owner: "sdk-ui",
    publicExport: "CardFace",
    sourceFiles: [
      "packages/sdk/src/ui/components/Card.tsx",
      "packages/sdk/src/ui/stories/CardFace.stories.tsx",
    ],
    storyIds: [
      "cards-cardface--default-content",
      "cards-cardface--interactive-controlled",
      "cards-cardface--state-attributes-present",
    ],
    requiredCapabilities: ["click", "keyboard", "responsive-layout"],
  }),
  defineUIContract({
    id: "Card",
    kind: "component",
    owner: "sdk-runtime",
    sourceFiles: [
      "packages/sdk/src/runtime/workspace-contract/index.ts",
      "packages/sdk/src/ui/components/Card.tsx",
    ],
    requiredCapabilities: ["click", "keyboard", "runtime-draft"],
  }),
  defineUIContract({
    id: "CardCollection",
    kind: "component",
    owner: "sdk-runtime",
    sourceFiles: [
      "packages/sdk/src/runtime/workspace-contract/index.ts",
      "packages/sdk/src/runtime/primitives/zone.tsx",
    ],
    requiredCapabilities: ["click", "keyboard", "runtime-submit"],
  }),
  defineUIContract({
    id: "CostDisplay",
    kind: "component",
    owner: "sdk-ui",
    publicExport: "CostDisplay",
    sourceFiles: [
      "packages/sdk/src/ui/components/CostDisplay.tsx",
      "packages/sdk/src/ui/stories/ResourceStatusPlayer.stories.tsx",
    ],
    storyIds: ["resource-status--cost"],
    requiredCapabilities: ["responsive-layout"],
  }),
  defineUIContract({
    id: "GuidancePanel",
    kind: "component",
    owner: "sdk-ui",
    publicExport: "GuidancePanel",
    sourceFiles: [
      "packages/sdk/src/ui/components/Guidance.tsx",
      "packages/sdk/src/ui/stories/ResourceStatusPlayer.stories.tsx",
    ],
    storyIds: [
      "resource-status--guidance-overview",
      "resource-status--guidance-phone-stack",
    ],
    requiredCapabilities: ["responsive-layout"],
  }),
  defineUIContract({
    id: "GameEventLog",
    kind: "component",
    owner: "sdk-ui",
    publicExport: "GameEventLog",
    sourceFiles: ["packages/sdk/src/ui/components/GameEventLog.tsx"],
    requiredCapabilities: ["responsive-layout"],
  }),
  defineUIContract({
    id: "SetupChecklist",
    kind: "component",
    owner: "sdk-ui",
    publicExport: "SetupChecklist",
    sourceFiles: [
      "packages/sdk/src/ui/components/Guidance.tsx",
      "packages/sdk/src/ui/stories/ResourceStatusPlayer.stories.tsx",
    ],
    storyIds: [
      "resource-status--setup-checklist-controlled",
      "resource-status--guidance-phone-stack",
    ],
    requiredCapabilities: ["responsive-layout"],
  }),
  defineUIContract({
    id: "ActionHelp",
    kind: "component",
    owner: "sdk-ui",
    publicExport: "ActionHelp",
    sourceFiles: [
      "packages/sdk/src/ui/components/Guidance.tsx",
      "packages/sdk/src/ui/stories/ResourceStatusPlayer.stories.tsx",
    ],
    storyIds: [
      "resource-status--action-help-blocked",
      "resource-status--guidance-overview",
    ],
    requiredCapabilities: ["responsive-layout"],
  }),
  defineUIContract({
    id: "Dialog",
    kind: "component",
    owner: "sdk-ui",
    publicExport: "Dialog",
    sourceFiles: [
      "packages/sdk/src/ui/internal/ui/dialog.tsx",
      "packages/sdk/src/ui/stories/Panels.stories.tsx",
    ],
    storyIds: ["panels--dialog-standard"],
    requiredCapabilities: ["click", "keyboard"],
  }),
  defineUIContract({
    id: "Drawer",
    kind: "component",
    owner: "sdk-ui",
    publicExport: "Drawer",
    sourceFiles: [
      "packages/sdk/src/ui/components/Drawer.tsx",
      "packages/sdk/src/ui/stories/Panels.stories.tsx",
    ],
    storyIds: ["panels--mobile-bottom-sheet"],
    requiredCapabilities: [
      "click",
      "keyboard",
      "touch-drag",
      "responsive-layout",
    ],
  }),
  defineUIContract({
    id: "HandView",
    kind: "component",
    owner: "sdk-ui",
    publicExport: "HandView",
    sourceFiles: [
      "packages/sdk/src/ui/components/HandView.tsx",
      "packages/sdk/src/ui/components/hand-layout-math.ts",
      "packages/sdk/src/ui/components/hand-pointer-engine.ts",
      "packages/sdk/src/ui/stories/HandView.stories.tsx",
    ],
    storyIds: [
      "hands-handview--five-card-fan",
      "hands-handview--phone-portrait-thirteen",
      "hands-handview--tap-emits-activate",
      "hands-handview--keyboard-emits-activate",
      "hands-handview--drag-to-target-selection-staging",
    ],
    requiredCapabilities: [
      "click",
      "keyboard",
      "pointer-drag",
      "touch-drag",
      "responsive-layout",
      "runtime-draft",
      "runtime-submit",
    ],
  }),
  defineUIContract({
    id: "Hand",
    kind: "component",
    owner: "sdk-runtime",
    sourceFiles: [
      "packages/sdk/src/runtime/workspace-contract/index.ts",
      "packages/sdk/src/runtime/primitives/hand-surface.tsx",
      "packages/sdk/src/ui/components/HandView.tsx",
    ],
    requiredCapabilities: [
      "click",
      "keyboard",
      "runtime-draft",
      "runtime-submit",
    ],
  }),
  defineUIContract({
    id: "Input",
    kind: "component",
    owner: "sdk-ui",
    publicExport: "Input",
    sourceFiles: [
      "packages/sdk/src/ui/internal/ui/input.tsx",
      "packages/sdk/src/ui/stories/Panels.stories.tsx",
    ],
    storyIds: ["panels--dialog-standard"],
    requiredCapabilities: ["keyboard"],
  }),
  defineUIContract({
    id: "InteractionInput",
    kind: "primitive",
    owner: "sdk-runtime",
    sourceFiles: [
      "packages/sdk/src/runtime/primitives/interaction/controls.tsx",
      "packages/sdk/src/runtime/hooks/useBoundInteractionHandle.ts",
    ],
    requiredCapabilities: ["keyboard", "runtime-draft"],
  }),
  defineUIContract({
    id: "InteractionSubmit",
    kind: "primitive",
    owner: "sdk-runtime",
    sourceFiles: [
      "packages/sdk/src/runtime/primitives/interaction/controls.tsx",
    ],
    requiredCapabilities: ["click", "keyboard", "runtime-submit"],
  }),
  defineUIContract({
    id: "MoreActions",
    kind: "component",
    owner: "sdk-ui",
    publicExport: "MoreActions",
    sourceFiles: [
      "packages/sdk/src/ui/components/MoreActions.tsx",
      "packages/sdk/src/ui/stories/Misc.stories.tsx",
    ],
    storyIds: ["misc--toast-notifications"],
    requiredCapabilities: ["click", "keyboard", "responsive-layout"],
  }),
  defineUIContract({
    id: "Panel",
    kind: "component",
    owner: "sdk-ui",
    publicExport: "Panel",
    sourceFiles: [
      "packages/sdk/src/ui/components/Panel.tsx",
      "packages/sdk/src/ui/stories/Panels.stories.tsx",
    ],
    storyIds: ["panels--compound-panel"],
    requiredCapabilities: ["click", "keyboard", "responsive-layout"],
  }),
  defineUIContract({
    id: "OutcomeDialog",
    kind: "component",
    owner: "sdk-ui",
    publicExport: "OutcomeDialog",
    sourceFiles: [
      "packages/sdk/src/ui/components/OutcomeDialog.tsx",
      "packages/sdk/src/ui/stories/ResourceStatusPlayer.stories.tsx",
    ],
    storyIds: ["resource-status--outcomedialog-winner"],
    requiredCapabilities: ["click", "runtime-submit"],
  }),
  defineUIContract({
    id: "Outcome",
    kind: "component",
    owner: "sdk-ui",
    sourceFiles: [
      "packages/sdk/src/ui/components/OutcomeDialog.tsx",
      "packages/sdk/src/ui/stories/ResourceStatusPlayer.stories.tsx",
    ],
    requiredCapabilities: ["runtime-submit"],
  }),
  defineUIContract({
    id: "PlayerScore",
    kind: "component",
    owner: "sdk-ui",
    sourceFiles: [
      "packages/sdk/src/ui/components/OutcomeDialog.tsx",
      "packages/sdk/src/ui/stories/ResourceStatusPlayer.stories.tsx",
    ],
    requiredCapabilities: ["responsive-layout"],
  }),
  defineUIContract({
    id: "PluginRuntime",
    kind: "runtime",
    owner: "sdk-runtime",
    sourceFiles: [
      "packages/sdk/src/runtime/components/PluginRuntime.tsx",
      "packages/sdk/src/runtime/components/PluginRuntimeBoundary.tsx",
      "packages/sdk/src/runtime/core/create-plugin-runtime-client.ts",
    ],
    requiredCapabilities: ["runtime-draft", "runtime-submit"],
  }),
  defineUIContract({
    id: "PrimaryActionButton",
    kind: "component",
    owner: "sdk-ui",
    publicExport: "PrimaryActionButton",
    sourceFiles: [
      "packages/sdk/src/ui/components/PrimaryActionButton.tsx",
      "packages/sdk/src/ui/stories/Buttons.stories.tsx",
    ],
    storyIds: ["buttons--primary-action-dock"],
    requiredCapabilities: ["click", "keyboard", "runtime-submit"],
  }),
  defineUIContract({
    id: "PrimaryButton",
    kind: "component",
    owner: "sdk-ui",
    publicExport: "PrimaryButton",
    sourceFiles: [
      "packages/sdk/src/ui/components/PrimaryButton.tsx",
      "packages/sdk/src/ui/stories/Buttons.stories.tsx",
    ],
    storyIds: ["buttons--themed-variants"],
    requiredCapabilities: ["click", "keyboard"],
  }),
  defineUIContract({
    id: "ResourceCounter",
    kind: "component",
    owner: "sdk-ui",
    publicExport: "ResourceCounter",
    sourceFiles: [
      "packages/sdk/src/ui/components/ResourceCounter.tsx",
      "packages/sdk/src/ui/stories/ResourceStatusPlayer.stories.tsx",
    ],
    storyIds: [
      "resource-status--resource-compact",
      "resource-status--resource-zero-hidden",
    ],
    requiredCapabilities: ["responsive-layout"],
  }),
  defineUIContract({
    id: "Resource",
    kind: "component",
    owner: "sdk-ui",
    sourceFiles: [
      "packages/sdk/src/ui/components/ResourceCounter.tsx",
      "packages/sdk/src/ui/components/CostDisplay.tsx",
      "packages/sdk/src/ui/stories/ResourceStatusPlayer.stories.tsx",
    ],
    requiredCapabilities: ["responsive-layout"],
  }),
  defineUIContract({
    id: "Select",
    kind: "component",
    owner: "sdk-ui",
    publicExport: "Select",
    sourceFiles: [
      "packages/sdk/src/ui/internal/ui/select.tsx",
      "packages/sdk/src/ui/stories/Panels.stories.tsx",
    ],
    storyIds: ["panels--dialog-standard"],
    requiredCapabilities: ["click", "keyboard"],
  }),
  defineUIContract({
    id: "StandingsTable",
    kind: "component",
    owner: "sdk-ui",
    publicExport: "StandingsTable",
    sourceFiles: [
      "packages/sdk/src/ui/components/OutcomeDialog.tsx",
      "packages/sdk/src/ui/stories/ResourceStatusPlayer.stories.tsx",
    ],
    storyIds: ["resource-status--outcomedialog-winner"],
    requiredCapabilities: ["click", "runtime-submit"],
  }),
  defineUIContract({
    id: "SlotSystem",
    kind: "component",
    owner: "sdk-ui",
    publicExport: "SlotSystem",
    sourceFiles: [
      "packages/sdk/src/ui/components/board/SlotSystem.tsx",
      "packages/sdk/src/ui/stories/BoardTarget.stories.tsx",
    ],
    storyIds: [
      "board-targets--eligible-targets",
      "board-targets--claimed-and-disabled",
    ],
    requiredCapabilities: ["click", "keyboard", "responsive-layout"],
  }),
  defineUIContract({
    id: "SquareGrid",
    kind: "component",
    owner: "sdk-ui",
    publicExport: "SquareGrid",
    sourceFiles: [
      "packages/sdk/src/ui/components/board/SquareGrid.tsx",
      "packages/sdk/src/ui/components/board/tiled-grid/interactive-layer.tsx",
      "packages/sdk/src/runtime/primitives/board.tsx",
      "packages/sdk/src/ui/stories/BoardTarget.stories.tsx",
    ],
    storyIds: ["board-targets--eligible-targets"],
    requiredCapabilities: [
      "click",
      "keyboard",
      "responsive-layout",
      "runtime-draft",
      "runtime-submit",
    ],
  }),
  defineUIContract({
    id: "Board.Space",
    kind: "primitive",
    owner: "sdk-runtime",
    sourceFiles: [
      "packages/sdk/src/runtime/primitives/board.tsx",
      "packages/sdk/src/runtime/workspace-contract/index.ts",
    ],
    requiredCapabilities: [
      "click",
      "keyboard",
      "runtime-draft",
      "runtime-submit",
    ],
  }),
  defineUIContract({
    id: "Board.HexGrid",
    kind: "component",
    owner: "sdk-runtime",
    sourceFiles: [
      "packages/sdk/src/ui/components/board/hex-board-view.ts",
      "packages/sdk/src/ui/components/board/HexGrid.tsx",
      "packages/sdk/src/runtime/primitives/board.tsx",
      "packages/sdk/src/runtime/workspace-contract/index.ts",
    ],
    requiredCapabilities: [
      "click",
      "keyboard",
      "responsive-layout",
      "runtime-draft",
      "runtime-submit",
    ],
  }),
  defineUIContract({
    id: "StagingZone",
    kind: "component",
    owner: "sdk-ui",
    publicExport: "StagingZone",
    sourceFiles: [
      "packages/sdk/src/ui/components/StagingZone.tsx",
      "packages/sdk/src/ui/stories/StagingZone.stories.tsx",
    ],
    storyIds: ["hand-stagingzone--removes-on-click"],
    requiredCapabilities: ["click", "keyboard", "runtime-draft"],
  }),
  defineUIContract({
    id: "Table",
    kind: "component",
    owner: "sdk-ui",
    sourceFiles: [
      "packages/sdk/src/ui/components/Panel.tsx",
      "packages/sdk/src/ui/stories/Panels.stories.tsx",
    ],
    requiredCapabilities: ["responsive-layout"],
  }),
  defineUIContract({
    id: "ThemedButton",
    kind: "component",
    owner: "sdk-ui",
    publicExport: "ThemedButton",
    sourceFiles: [
      "packages/sdk/src/ui/components/ThemedButton.tsx",
      "packages/sdk/src/ui/stories/Buttons.stories.tsx",
    ],
    storyIds: [
      "buttons--themed-variants",
      "buttons--themed-button-invokes-on-click",
      "buttons--disabled-themed-button-does-not-invoke",
    ],
    requiredCapabilities: ["click", "keyboard"],
  }),
] as const satisfies readonly UIContractDefinition[];
