// Generated by dreamboard — do not edit by hand.
import game from "../app/game";
import {
  contractFingerprint,
  createReducerBundle,
} from "@dreamboard-games/sdk/reducer";
import { createTestRuntime as createDreamboardTestRuntime } from "@dreamboard-games/sdk/testing";
import type { CreateTestRuntimeOptions } from "@dreamboard-games/sdk/testing";
import { literals } from "../shared/manifest-contract";
import type { PhaseName } from "../shared/generated/ui-contract";
import {
  BASE_STATES,
  BASE_STATES_CONTRACT_FINGERPRINT,
} from "./generated/base-states.generated";
import type {
  BaseDefinition,
  ScenarioDefinition,
  TestRunner,
} from "./generated/testing-contract";

export * from "./generated/testing-contract";

/**
 * Workspace-narrowed `defineBase` wrapper. Accepts the generated
 * `BaseDefinition` so `setup({ seat, game })` is typed against the
 * workspace's player ids and interaction contract.
 */
export function defineBase<const Definition extends BaseDefinition>(
  definition: Definition,
): Definition {
  return definition;
}

/**
 * Workspace-narrowed `defineScenario` wrapper. The generated
 * `ScenarioDefinition` narrows `ctx.view(playerId)` in `then` based on
 * the declared `phase`, keeps `when` union-typed, and constrains
 * `phase` / `stage` to the manifest-derived literal types.
 */
export function defineScenario<
  const Runners extends readonly TestRunner[] = readonly ["reducer"],
  const Phase extends PhaseName | undefined = undefined,
>(
  definition: ScenarioDefinition<Runners, Phase>,
): ScenarioDefinition<Runners, Phase> {
  return definition;
}

export function createTestRuntime(options: {
  baseId: keyof typeof BASE_STATES & string;
  phase?: PhaseName;
  controllingPlayerId?: (typeof literals.playerIds)[number];
  userId?: string | null;
}) {
  const reducerBundle = createReducerBundle(
    game,
  ) satisfies CreateTestRuntimeOptions["bundle"];
  const baseStates =
    BASE_STATES satisfies CreateTestRuntimeOptions["baseStates"];
  const basePlayerIds = literals.playerIds.slice(
    0,
    BASE_STATES[options.baseId]?.fingerprint.players ?? literals.playerIds.length,
  );
  const playerIds =
    options.controllingPlayerId &&
    basePlayerIds.includes(options.controllingPlayerId)
      ? [
          options.controllingPlayerId,
          ...basePlayerIds.filter(
            (playerId) => playerId !== options.controllingPlayerId,
          ),
        ]
      : basePlayerIds;
  const runtime = createDreamboardTestRuntime({
    baseId: options.baseId,
    baseStates,
    bundle: reducerBundle,
    contractFingerprint: contractFingerprint(game).value,
    expectedBaseStateFingerprint: BASE_STATES_CONTRACT_FINGERPRINT,
    phase: options.phase,
    userId: options.userId ?? "test-user",
    playerIds,
  });

  return runtime;
}
