// Generated by scripts/generate-authoring-metadata.mjs. Do not edit by hand.
import type { GeneratedAuthoringMetadataV1 } from "./types.js";

export const GENERATED_AUTHORING_METADATA = {
  sdkVersion: "0.4.0-alpha.6",
  codegenVersion: "0.3.0-alpha.0",
  manifestSchemaVersion: 2,
  generatedArtifactSchemaVersion: 1,
} as const satisfies GeneratedAuthoringMetadataV1;
