/**
 * Generated file.
 * Do not edit directly.
 */

export const literals = {
  playerIds: ["player-1", "player-2", "player-3", "player-4", "player-5"] as const,
  phaseNames: [] as readonly string[],
  boardLayouts: ["generic", "hex", "square"] as const,
  setupOptionIds: ["default-game"] as const,
  setupProfileIds: ["default-setup"] as const,
  cardSetIds: ["sushi-cards"] as const,
  cardTypes: ["chopsticks", "dumpling", "maki-1", "maki-2", "maki-3", "nigiri-egg", "nigiri-salmon", "nigiri-squid", "pudding", "sashimi", "tempura", "wasabi"] as const,
  cardIds: ["chopsticks-1", "chopsticks-2", "chopsticks-3", "chopsticks-4", "dumpling-1", "dumpling-10", "dumpling-11", "dumpling-12", "dumpling-13", "dumpling-14", "dumpling-2", "dumpling-3", "dumpling-4", "dumpling-5", "dumpling-6", "dumpling-7", "dumpling-8", "dumpling-9", "maki-1-1", "maki-1-2", "maki-1-3", "maki-1-4", "maki-1-5", "maki-1-6", "maki-2-1", "maki-2-2", "maki-2-3", "maki-2-4", "maki-2-5", "maki-2-6", "maki-3-1", "maki-3-2", "maki-3-3", "maki-3-4", "maki-3-5", "maki-3-6", "nigiri-egg-1", "nigiri-egg-2", "nigiri-egg-3", "nigiri-egg-4", "nigiri-egg-5", "nigiri-egg-6", "nigiri-salmon-1", "nigiri-salmon-10", "nigiri-salmon-2", "nigiri-salmon-3", "nigiri-salmon-4", "nigiri-salmon-5", "nigiri-salmon-6", "nigiri-salmon-7", "nigiri-salmon-8", "nigiri-salmon-9", "nigiri-squid-1", "nigiri-squid-2", "nigiri-squid-3", "nigiri-squid-4", "nigiri-squid-5", "pudding-1", "pudding-10", "pudding-2", "pudding-3", "pudding-4", "pudding-5", "pudding-6", "pudding-7", "pudding-8", "pudding-9", "sashimi-1", "sashimi-10", "sashimi-11", "sashimi-12", "sashimi-13", "sashimi-14", "sashimi-2", "sashimi-3", "sashimi-4", "sashimi-5", "sashimi-6", "sashimi-7", "sashimi-8", "sashimi-9", "tempura-1", "tempura-10", "tempura-11", "tempura-12", "tempura-13", "tempura-14", "tempura-2", "tempura-3", "tempura-4", "tempura-5", "tempura-6", "tempura-7", "tempura-8", "tempura-9", "wasabi-1", "wasabi-2", "wasabi-3", "wasabi-4", "wasabi-5", "wasabi-6"] as const,
  deckIds: ["draw-pile", "round-discard"] as const,
  handIds: ["hand", "played", "pudding"] as const,
  sharedZoneIds: ["draw-pile", "round-discard"] as const,
  playerZoneIds: ["hand", "played", "pudding"] as const,
  zoneIds: ["draw-pile", "hand", "played", "pudding", "round-discard"] as const,
  resourceIds: [] as const,
  resourcePresentationById: {} as const,
  pieceTypeIds: [] as const,
  pieceIds: [] as const,
  dieTypeIds: [] as const,
  dieIds: [] as const,
  boardTemplateIds: [] as const,
  boardTypeIds: [] as const,
  boardBaseIds: [] as const,
  boardIds: [] as const,
  boardContainerIds: [] as const,
  relationTypeIds: [] as const,
  edgeIds: [] as const,
  edgeTypeIds: [] as const,
  vertexIds: [] as const,
  vertexTypeIds: [] as const,
  spaceIds: [] as const,
  spaceTypeIds: [] as const,
  handVisibilityById: {
  "hand": "ownerOnly",
  "played": "public",
  "pudding": "public",
} as const,
  zoneVisibilityById: {
  "draw-pile": "hidden",
  "hand": "ownerOnly",
  "played": "public",
  "pudding": "public",
  "round-discard": "public",
} as const,
  cardSetIdByCardId: {
  "chopsticks-1": "sushi-cards",
  "chopsticks-2": "sushi-cards",
  "chopsticks-3": "sushi-cards",
  "chopsticks-4": "sushi-cards",
  "dumpling-1": "sushi-cards",
  "dumpling-10": "sushi-cards",
  "dumpling-11": "sushi-cards",
  "dumpling-12": "sushi-cards",
  "dumpling-13": "sushi-cards",
  "dumpling-14": "sushi-cards",
  "dumpling-2": "sushi-cards",
  "dumpling-3": "sushi-cards",
  "dumpling-4": "sushi-cards",
  "dumpling-5": "sushi-cards",
  "dumpling-6": "sushi-cards",
  "dumpling-7": "sushi-cards",
  "dumpling-8": "sushi-cards",
  "dumpling-9": "sushi-cards",
  "maki-1-1": "sushi-cards",
  "maki-1-2": "sushi-cards",
  "maki-1-3": "sushi-cards",
  "maki-1-4": "sushi-cards",
  "maki-1-5": "sushi-cards",
  "maki-1-6": "sushi-cards",
  "maki-2-1": "sushi-cards",
  "maki-2-2": "sushi-cards",
  "maki-2-3": "sushi-cards",
  "maki-2-4": "sushi-cards",
  "maki-2-5": "sushi-cards",
  "maki-2-6": "sushi-cards",
  "maki-3-1": "sushi-cards",
  "maki-3-2": "sushi-cards",
  "maki-3-3": "sushi-cards",
  "maki-3-4": "sushi-cards",
  "maki-3-5": "sushi-cards",
  "maki-3-6": "sushi-cards",
  "nigiri-egg-1": "sushi-cards",
  "nigiri-egg-2": "sushi-cards",
  "nigiri-egg-3": "sushi-cards",
  "nigiri-egg-4": "sushi-cards",
  "nigiri-egg-5": "sushi-cards",
  "nigiri-egg-6": "sushi-cards",
  "nigiri-salmon-1": "sushi-cards",
  "nigiri-salmon-10": "sushi-cards",
  "nigiri-salmon-2": "sushi-cards",
  "nigiri-salmon-3": "sushi-cards",
  "nigiri-salmon-4": "sushi-cards",
  "nigiri-salmon-5": "sushi-cards",
  "nigiri-salmon-6": "sushi-cards",
  "nigiri-salmon-7": "sushi-cards",
  "nigiri-salmon-8": "sushi-cards",
  "nigiri-salmon-9": "sushi-cards",
  "nigiri-squid-1": "sushi-cards",
  "nigiri-squid-2": "sushi-cards",
  "nigiri-squid-3": "sushi-cards",
  "nigiri-squid-4": "sushi-cards",
  "nigiri-squid-5": "sushi-cards",
  "pudding-1": "sushi-cards",
  "pudding-10": "sushi-cards",
  "pudding-2": "sushi-cards",
  "pudding-3": "sushi-cards",
  "pudding-4": "sushi-cards",
  "pudding-5": "sushi-cards",
  "pudding-6": "sushi-cards",
  "pudding-7": "sushi-cards",
  "pudding-8": "sushi-cards",
  "pudding-9": "sushi-cards",
  "sashimi-1": "sushi-cards",
  "sashimi-10": "sushi-cards",
  "sashimi-11": "sushi-cards",
  "sashimi-12": "sushi-cards",
  "sashimi-13": "sushi-cards",
  "sashimi-14": "sushi-cards",
  "sashimi-2": "sushi-cards",
  "sashimi-3": "sushi-cards",
  "sashimi-4": "sushi-cards",
  "sashimi-5": "sushi-cards",
  "sashimi-6": "sushi-cards",
  "sashimi-7": "sushi-cards",
  "sashimi-8": "sushi-cards",
  "sashimi-9": "sushi-cards",
  "tempura-1": "sushi-cards",
  "tempura-10": "sushi-cards",
  "tempura-11": "sushi-cards",
  "tempura-12": "sushi-cards",
  "tempura-13": "sushi-cards",
  "tempura-14": "sushi-cards",
  "tempura-2": "sushi-cards",
  "tempura-3": "sushi-cards",
  "tempura-4": "sushi-cards",
  "tempura-5": "sushi-cards",
  "tempura-6": "sushi-cards",
  "tempura-7": "sushi-cards",
  "tempura-8": "sushi-cards",
  "tempura-9": "sushi-cards",
  "wasabi-1": "sushi-cards",
  "wasabi-2": "sushi-cards",
  "wasabi-3": "sushi-cards",
  "wasabi-4": "sushi-cards",
  "wasabi-5": "sushi-cards",
  "wasabi-6": "sushi-cards",
} as const,
  cardTypeByCardId: {
  "chopsticks-1": "chopsticks",
  "chopsticks-2": "chopsticks",
  "chopsticks-3": "chopsticks",
  "chopsticks-4": "chopsticks",
  "dumpling-1": "dumpling",
  "dumpling-10": "dumpling",
  "dumpling-11": "dumpling",
  "dumpling-12": "dumpling",
  "dumpling-13": "dumpling",
  "dumpling-14": "dumpling",
  "dumpling-2": "dumpling",
  "dumpling-3": "dumpling",
  "dumpling-4": "dumpling",
  "dumpling-5": "dumpling",
  "dumpling-6": "dumpling",
  "dumpling-7": "dumpling",
  "dumpling-8": "dumpling",
  "dumpling-9": "dumpling",
  "maki-1-1": "maki-1",
  "maki-1-2": "maki-1",
  "maki-1-3": "maki-1",
  "maki-1-4": "maki-1",
  "maki-1-5": "maki-1",
  "maki-1-6": "maki-1",
  "maki-2-1": "maki-2",
  "maki-2-2": "maki-2",
  "maki-2-3": "maki-2",
  "maki-2-4": "maki-2",
  "maki-2-5": "maki-2",
  "maki-2-6": "maki-2",
  "maki-3-1": "maki-3",
  "maki-3-2": "maki-3",
  "maki-3-3": "maki-3",
  "maki-3-4": "maki-3",
  "maki-3-5": "maki-3",
  "maki-3-6": "maki-3",
  "nigiri-egg-1": "nigiri-egg",
  "nigiri-egg-2": "nigiri-egg",
  "nigiri-egg-3": "nigiri-egg",
  "nigiri-egg-4": "nigiri-egg",
  "nigiri-egg-5": "nigiri-egg",
  "nigiri-egg-6": "nigiri-egg",
  "nigiri-salmon-1": "nigiri-salmon",
  "nigiri-salmon-10": "nigiri-salmon",
  "nigiri-salmon-2": "nigiri-salmon",
  "nigiri-salmon-3": "nigiri-salmon",
  "nigiri-salmon-4": "nigiri-salmon",
  "nigiri-salmon-5": "nigiri-salmon",
  "nigiri-salmon-6": "nigiri-salmon",
  "nigiri-salmon-7": "nigiri-salmon",
  "nigiri-salmon-8": "nigiri-salmon",
  "nigiri-salmon-9": "nigiri-salmon",
  "nigiri-squid-1": "nigiri-squid",
  "nigiri-squid-2": "nigiri-squid",
  "nigiri-squid-3": "nigiri-squid",
  "nigiri-squid-4": "nigiri-squid",
  "nigiri-squid-5": "nigiri-squid",
  "pudding-1": "pudding",
  "pudding-10": "pudding",
  "pudding-2": "pudding",
  "pudding-3": "pudding",
  "pudding-4": "pudding",
  "pudding-5": "pudding",
  "pudding-6": "pudding",
  "pudding-7": "pudding",
  "pudding-8": "pudding",
  "pudding-9": "pudding",
  "sashimi-1": "sashimi",
  "sashimi-10": "sashimi",
  "sashimi-11": "sashimi",
  "sashimi-12": "sashimi",
  "sashimi-13": "sashimi",
  "sashimi-14": "sashimi",
  "sashimi-2": "sashimi",
  "sashimi-3": "sashimi",
  "sashimi-4": "sashimi",
  "sashimi-5": "sashimi",
  "sashimi-6": "sashimi",
  "sashimi-7": "sashimi",
  "sashimi-8": "sashimi",
  "sashimi-9": "sashimi",
  "tempura-1": "tempura",
  "tempura-10": "tempura",
  "tempura-11": "tempura",
  "tempura-12": "tempura",
  "tempura-13": "tempura",
  "tempura-14": "tempura",
  "tempura-2": "tempura",
  "tempura-3": "tempura",
  "tempura-4": "tempura",
  "tempura-5": "tempura",
  "tempura-6": "tempura",
  "tempura-7": "tempura",
  "tempura-8": "tempura",
  "tempura-9": "tempura",
  "wasabi-1": "wasabi",
  "wasabi-2": "wasabi",
  "wasabi-3": "wasabi",
  "wasabi-4": "wasabi",
  "wasabi-5": "wasabi",
  "wasabi-6": "wasabi",
} as const,
  setupChoiceIdsByOptionId: {
  "default-game": ["default-game"] as const,
} as const,
  cardSetIdsBySharedZoneId: {
  "draw-pile": ["sushi-cards"] as const,
  "round-discard": ["sushi-cards"] as const,
} as const,
  sharedZoneIdsByCardSetId: {
  "sushi-cards": ["draw-pile", "round-discard"] as const,
} as const,
  homeSharedZoneIdsByCardType: {
  "chopsticks": [] as const,
  "dumpling": [] as const,
  "maki-1": [] as const,
  "maki-2": [] as const,
  "maki-3": [] as const,
  "nigiri-egg": [] as const,
  "nigiri-salmon": [] as const,
  "nigiri-squid": [] as const,
  "pudding": [] as const,
  "sashimi": [] as const,
  "tempura": [] as const,
  "wasabi": [] as const,
} as const,
  homeSharedZoneIdByCardType: {

} as const,
  cardSetIdsByPlayerZoneId: {
  "hand": ["sushi-cards"] as const,
  "played": ["sushi-cards"] as const,
  "pudding": ["sushi-cards"] as const,
} as const,
} as const;
