// Generated by dreamboard scaffold.
import { defineScenario } from "../testing-types";

export default defineScenario({
  id: "smoke-initial-turn",
  description: "Sanity check that setup auto-enters the playable initial turn.",
  from: "initial-turn",
  when: async () => undefined,
  then: ({ expect, players, state, view, seat }) => {
    const playerIds = players();
    expect(playerIds).toHaveLength(playerIds.length);
    expect(playerIds.length).toBeGreaterThanOrEqual(1);
    expect(state()).toBe("playerTurn");
    expect(view(seat(0)).gameOver).toBe(false);
    expect(view(seat(0)).outcome).toBeNull();
  },
});
