#!/usr/bin/env node
// Emits TS types, Zod schemas, typed effect builders, and a version constant
// from schema/reducer-runtime.schema.json. Outputs to ./generated.
//
// Why a bespoke generator and not `json-schema-to-ts` + `json-schema-to-zod`?
// - The schema is small and has specific conventions (oneOf-with-const-tag as
//   our sum-type idiom). Hand-rolling ~250 lines lets us emit *exactly* the
//   shapes we want (e.g. union members as named types, builders with the
//   effectId enforced, a single `version.ts` file). It also keeps the
//   reducer-contract package free of extra third-party codegen deps whose
//   output we'd still have to post-process.
// - If the schema grows large, swap this for `json-schema-to-zod` behind the
//   same output paths; consumers won't notice.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const SCHEMA_PATH = path.join(ROOT, "schema", "reducer-runtime.schema.json");
const OPERATIONS_PATH = path.join(
  ROOT,
  "schema",
  "reducer-runtime.operations.json",
);
const OUT_DIR = path.join(ROOT, "generated");
const SRC_DIR = path.join(ROOT, "src");
const PKG_PATH = path.join(ROOT, "package.json");

const GENERATED_HEADER = `// @generated by packages/reducer-contract/scripts/generate-ts.mjs
// DO NOT EDIT BY HAND. Edit schema/reducer-runtime.schema.json and rerun \`pnpm generate\`.
`;
const BUNDLE_GENERATED_HEADER = `// @generated by packages/reducer-contract/scripts/generate-ts.mjs
// DO NOT EDIT BY HAND. Edit schema/reducer-runtime.operations.json and rerun \`pnpm generate\`.
`;

const schema = JSON.parse(fs.readFileSync(SCHEMA_PATH, "utf8"));
const operationsContract = JSON.parse(fs.readFileSync(OPERATIONS_PATH, "utf8"));
const pkg = JSON.parse(fs.readFileSync(PKG_PATH, "utf8"));
const defs = schema.$defs;

fs.mkdirSync(OUT_DIR, { recursive: true });
fs.mkdirSync(SRC_DIR, { recursive: true });

// -----------------------------------------------------------------------------
// helpers
// -----------------------------------------------------------------------------

function refName(ref) {
  const m = /^#\/\$defs\/(.+)$/.exec(ref);
  if (!m) throw new Error(`Unsupported $ref: ${ref}`);
  return m[1];
}

function isConst(prop) {
  return prop && typeof prop.const !== "undefined";
}

function tsTypeOf(def, refPrefix = "") {
  if (def.$ref) return refPrefix + refName(def.$ref);
  if (isConst(def)) return JSON.stringify(def.const);
  if (def.oneOf || def.anyOf) {
    const members = (def.oneOf || def.anyOf).map((m) => tsTypeOf(m, refPrefix));
    return members.join(" | ");
  }
  if (Array.isArray(def.type)) {
    return def.type.map((t) => tsTypeOf({ type: t }, refPrefix)).join(" | ");
  }
  switch (def.type) {
    case "string":
      if (Array.isArray(def.enum) && def.enum.length > 0) {
        return def.enum.map((value) => JSON.stringify(value)).join(" | ");
      }
      return "string";
    case "number":
      return "number";
    case "integer":
      return "number";
    case "boolean":
      return "boolean";
    case "null":
      return "null";
    case "array":
      return def.items
        ? `Array<${tsTypeOf(def.items, refPrefix)}>`
        : "Array<unknown>";
    case "object":
      if (def.additionalProperties && !def.properties) {
        return `Record<string, ${tsTypeOf(def.additionalProperties, refPrefix)}>`;
      }
      if (def.properties) {
        const required = new Set(def.required ?? []);
        const entries = Object.entries(def.properties).map(([k, v]) => {
          const opt = required.has(k) ? "" : "?";
          return `${JSON.stringify(k)}${opt}: ${tsTypeOf(v, refPrefix)}`;
        });
        return `{ ${entries.join("; ")} }`;
      }
      return "Record<string, unknown>";
    default:
      return "unknown";
  }
}

function zodExprOf(def) {
  if (def.$ref) return `${refName(def.$ref)}Schema`;
  if (isConst(def)) return `z.literal(${JSON.stringify(def.const)})`;
  if (def.oneOf) {
    const key = unionDiscriminator(def);
    const members = def.oneOf.map(zodExprOf);
    return key
      ? `z.discriminatedUnion(${JSON.stringify(key)}, [${members.join(", ")}])`
      : `z.union([${members.join(", ")}])`;
  }
  if (def.anyOf) {
    const members = def.anyOf.map(zodExprOf);
    return `z.union([${members.join(", ")}])`;
  }
  if (Array.isArray(def.type)) {
    const members = def.type.map((t) => zodExprOf({ type: t }));
    return `z.union([${members.join(", ")}])`;
  }
  switch (def.type) {
    case "string":
      if (Array.isArray(def.enum) && def.enum.length > 0) {
        return `z.enum([${def.enum.map((value) => JSON.stringify(value)).join(", ")}])`;
      }
      return def.pattern
        ? `z.string().regex(new RegExp(${JSON.stringify(def.pattern)}))`
        : def.minLength
        ? `z.string().min(${def.minLength})`
        : "z.string()";
    case "number":
      return "z.number()";
    case "integer":
      if (def.format === "int64") {
        return 'z.number().refine(Number.isInteger, { message: "Expected integer" })';
      }
      return "z.number().int()";
    case "boolean":
      return "z.boolean()";
    case "null":
      return "z.null()";
    case "array":
      return def.items
        ? `z.array(${zodExprOf(def.items)})`
        : "z.array(z.unknown())";
    case "object":
      if (def.additionalProperties && !def.properties) {
        return `z.record(z.string(), ${zodExprOf(def.additionalProperties)})`;
      }
      if (def.properties) {
        const required = new Set(def.required ?? []);
        const entries = Object.entries(def.properties).map(([k, v]) => {
          const schemaExpr = zodExprOf(v);
          return required.has(k)
            ? `${JSON.stringify(k)}: ${schemaExpr}`
            : `${JSON.stringify(k)}: ${schemaExpr}.optional()`;
        });
        const obj = `z.object({ ${entries.join(", ")} })`;
        return def.additionalProperties === false ? `${obj}.strict()` : obj;
      }
      return "z.record(z.string(), z.unknown())";
    default:
      return "z.unknown()";
  }
}

/**
 * Which discriminator key a oneOf uses, by peeking at its first member's
 * required literal properties. We support exactly two: `kind` and `type`.
 */
function unionDiscriminator(def) {
  if (!def.oneOf) return null;
  for (const member of def.oneOf) {
    const target = member.$ref ? defs[refName(member.$ref)] : member;
    if (!target?.properties) continue;
    if (target.properties.kind && isConst(target.properties.kind)) return "kind";
    if (target.properties.type && isConst(target.properties.type)) return "type";
  }
  return null;
}

function renderUnionZod(def) {
  const key = unionDiscriminator(def);
  const members = def.oneOf.map(zodExprOf);
  if (key) {
    return `z.discriminatedUnion(${JSON.stringify(key)}, [${members.join(", ")}])`;
  }
  return `z.union([${members.join(", ")}])`;
}

function assertKnownWireType(typeName, fieldName) {
  if (!defs[typeName]) {
    throw new Error(
      `Unknown reducer wire type '${typeName}' in ${fieldName}; expected a $defs entry in schema/reducer-runtime.schema.json.`,
    );
  }
}

function wireType(typeName) {
  assertKnownWireType(typeName, "operations contract");
  return `Wire.${typeName}`;
}

function operationReturnType(operation) {
  const base = wireType(operation.output);
  const output = operation.nullableOutput ? `${base} | null` : base;
  return operation.maybePromise ? `MaybePromise<${output}>` : output;
}

function renderOperationSignature(operation) {
  if (operation.input === null) {
    return `  ${operation.name}(): ${operationReturnType(operation)};`;
  }
  const inputType = wireType(operation.input);
  const returnType = operationReturnType(operation);
  const inline = `  ${operation.name}(input: ${inputType}): ${returnType};`;
  if (inline.length <= 80) return inline;
  return [
    `  ${operation.name}(`,
    `    input: ${inputType},`,
    `  ): ${returnType};`,
  ].join("\n");
}

// -----------------------------------------------------------------------------
// emit wire.ts (types)
// -----------------------------------------------------------------------------

const typeLines = [GENERATED_HEADER];
typeLines.push(`/* eslint-disable */`);
typeLines.push(``);

for (const [name, def] of Object.entries(defs)) {
  typeLines.push(`export type ${name} = ${tsTypeOf(def)};`);
  typeLines.push(``);
}

fs.writeFileSync(path.join(OUT_DIR, "wire.ts"), typeLines.join("\n"));

// -----------------------------------------------------------------------------
// emit src/bundle.ts (callable reducer bundle boundary)
// -----------------------------------------------------------------------------

if (!operationsContract.versionProperty) {
  throw new Error("Missing versionProperty in reducer-runtime.operations.json.");
}
if (!Array.isArray(operationsContract.operations)) {
  throw new Error("Missing operations[] in reducer-runtime.operations.json.");
}
assertKnownWireType(
  operationsContract.versionProperty.type,
  "versionProperty.type",
);
const seenOperationNames = new Set();
for (const operation of operationsContract.operations) {
  if (
    typeof operation.name !== "string" ||
    !/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(operation.name)
  ) {
    throw new Error(
      "Every reducer operation must have a valid TypeScript method name.",
    );
  }
  if (seenOperationNames.has(operation.name)) {
    throw new Error(`Duplicate reducer operation '${operation.name}'.`);
  }
  seenOperationNames.add(operation.name);
  if (typeof operation.input === "string") {
    assertKnownWireType(operation.input, `${operation.name}.input`);
  } else if (operation.input !== null) {
    throw new Error(
      `Operation '${operation.name}' must set input to a known wire type or null.`,
    );
  }
  if (operation.input === null && operation.name !== "projectStatic") {
    throw new Error(
      `Operation '${operation.name}' has no input; only projectStatic may be zero-argument.`,
    );
  }
  if (operation.name === "projectStatic" && operation.input !== null) {
    throw new Error("Operation 'projectStatic' must stay zero-argument.");
  }
  if (typeof operation.output !== "string") {
    throw new Error(`Operation '${operation.name}' must have a string output.`);
  }
  assertKnownWireType(operation.output, `${operation.name}.output`);
}

const bundleLines = [BUNDLE_GENERATED_HEADER];
bundleLines.push(`/* eslint-disable */`);
bundleLines.push(`import type * as Wire from "../generated/wire";`);
bundleLines.push(``);
bundleLines.push(`export type MaybePromise<T> = T | Promise<T>;`);
bundleLines.push(``);
bundleLines.push(`/**`);
bundleLines.push(` * Canonical erased reducer boundary for \`createReducerBundle(...)\`.`);
bundleLines.push(` *`);
bundleLines.push(` * The callable method list is generated from`);
bundleLines.push(` * \`schema/reducer-runtime.operations.json\`; payload DTOs come from`);
bundleLines.push(` * \`schema/reducer-runtime.schema.json\`.`);
bundleLines.push(` *`);
bundleLines.push(` * This interface models the host/guest surface only. The concrete`);
bundleLines.push(` * authored bundle stays strongly typed in \`@dreamboard-games/app-sdk/reducer\`, but every`);
bundleLines.push(` * cross-runtime caller should agree on this shape.`);
bundleLines.push(` */`);
bundleLines.push(`export interface ReducerBundleContract {`);
bundleLines.push(
  `  readonly ${operationsContract.versionProperty.name}: ${wireType(
    operationsContract.versionProperty.type,
  )};`,
);
for (const operation of operationsContract.operations) {
  bundleLines.push(renderOperationSignature(operation));
}
bundleLines.push(`}`);
bundleLines.push(``);

fs.writeFileSync(path.join(SRC_DIR, "bundle.ts"), bundleLines.join("\n"));

// -----------------------------------------------------------------------------
// emit zod.ts (schemas)
// -----------------------------------------------------------------------------

const zodLines = [GENERATED_HEADER];
zodLines.push(`/* eslint-disable */`);
zodLines.push(`import { z } from "zod";`);
zodLines.push(``);

// Emit schemas as `const` with explicit `z.ZodTypeAny` typing and a `get`
// helper so we can forward-reference within oneOf members. We do NOT need
// truly recursive schemas; a simple topological emit by alphabetical then
// override for leaves works for this contract.
//
// Strategy: emit leaf scalars first (JsonValue, strings, etc.), then compound
// types. We compute a dependency order via a lightweight topo sort.

function refsIn(def, acc = new Set()) {
  if (!def || typeof def !== "object") return acc;
  if (def.$ref) acc.add(refName(def.$ref));
  for (const key of Object.keys(def)) {
    if (key === "$ref") continue;
    const v = def[key];
    if (Array.isArray(v)) v.forEach((x) => refsIn(x, acc));
    else if (typeof v === "object" && v !== null) refsIn(v, acc);
  }
  return acc;
}

const order = [];
const seen = new Set();
const onStack = new Set();
function visit(name) {
  if (seen.has(name)) return;
  if (onStack.has(name)) {
    // Cycle: defer. Our contract has none; fail loudly if one appears.
    throw new Error(`Schema cycle detected at ${name}; add lazy handling.`);
  }
  onStack.add(name);
  const deps = refsIn(defs[name]);
  for (const d of deps) {
    if (d !== name) visit(d);
  }
  onStack.delete(name);
  seen.add(name);
  order.push(name);
}
for (const name of Object.keys(defs)) visit(name);

for (const name of order) {
  const def = defs[name];
  const expr = def.oneOf ? renderUnionZod(def) : zodExprOf(def);
  zodLines.push(`export const ${name}Schema = ${expr};`);
  zodLines.push(``);
}

fs.writeFileSync(path.join(OUT_DIR, "zod.ts"), zodLines.join("\n"));

// -----------------------------------------------------------------------------
// emit builders.ts (typed constructors for every Effect variant)
// -----------------------------------------------------------------------------

const effectVariants = defs.Effect.oneOf.map((m) => {
  const name = refName(m.$ref);
  const def = defs[name];
  const tag = def.properties.type.const;
  const required = new Set(def.required ?? []);
  const propEntries = Object.entries(def.properties)
    .filter(([k]) => k !== "type" && k !== "effectId")
    .map(([k, v]) => ({
      name: k,
      type: tsTypeOf(v, "Wire."),
      required: required.has(k),
    }));
  return { name, tag, props: propEntries };
});

const builderLines = [GENERATED_HEADER];
builderLines.push(`/* eslint-disable */`);
builderLines.push(`import type * as Wire from "./wire";`);
builderLines.push(``);
builderLines.push(
  `/**`,
  ` * Typed effect constructors. Authors MUST go through these; hand-constructing`,
  ` * Wire.Effect objects is banned by convention because it's how wire drift`,
  ` * re-enters the codebase.`,
  ` *`,
  ` * The \`effectId\` is minted by the runtime (see createEffectIdMinter below),`,
  ` * not by the author. Each builder returns a \`PendingEffect\` that carries`,
  ` * the optional continuation; the reducer bundle's accept materializer splits`,
  ` * pending effects into the wire's \`effects[]\` + \`continuations\` map.`,
  ` */`,
);
builderLines.push(``);
builderLines.push(`export type PendingEffect = Wire.Effect & {`);
builderLines.push(`  readonly __continuation?: Wire.ContinuationToken;`);
builderLines.push(`};`);
builderLines.push(``);
builderLines.push(`export type EffectIdMinter = () => Wire.EffectId;`);
builderLines.push(``);
builderLines.push(`/**`);
builderLines.push(` * Produces sequential, deterministic effect ids scoped to a single accept`);
builderLines.push(` * payload: "ef0", "ef1", ... . Uniqueness only needs to be local to the`);
builderLines.push(` * payload because the host consumes and discards them per dispatch.`);
builderLines.push(` */`);
builderLines.push(`export function createEffectIdMinter(): EffectIdMinter {`);
builderLines.push(`  let i = 0;`);
builderLines.push(`  return () => \`ef\${i++}\` as Wire.EffectId;`);
builderLines.push(`}`);
builderLines.push(``);
builderLines.push(`export type EffectBuilders = {`);
for (const v of effectVariants) {
  const args = v.props.map(
    (p) => `${p.name}${p.required ? "" : "?"}: ${p.type}`,
  );
  builderLines.push(
    `  ${v.tag}(args: { ${args.join("; ")} }, continuation?: Wire.ContinuationToken): PendingEffect;`,
  );
}
builderLines.push(`};`);
builderLines.push(``);
builderLines.push(
  `export function createEffectBuilders(mint: EffectIdMinter): EffectBuilders {`,
);
builderLines.push(`  return {`);
for (const v of effectVariants) {
  const argNames = v.props.map((p) => p.name);
  const argSpread = argNames.map((n) => `${n}: args.${n}`).join(", ");
  builderLines.push(`    ${v.tag}(args, continuation) {`);
  builderLines.push(
    `      const effect = { effectId: mint(), type: "${v.tag}" as const, ${argSpread} };`,
  );
  builderLines.push(
    `      return continuation === undefined`,
  );
  builderLines.push(
    `        ? (effect as PendingEffect)`,
  );
  builderLines.push(
    `        : Object.assign(effect, { __continuation: continuation });`,
  );
  builderLines.push(`    },`);
}
builderLines.push(`  };`);
builderLines.push(`}`);
builderLines.push(``);
builderLines.push(`/**`);
builderLines.push(` * Takes a list of PendingEffects and splits them into the canonical wire`);
builderLines.push(` * shape: \`effects[]\` (stripped of \`__continuation\`) + \`continuations\` map`);
builderLines.push(` * keyed by effectId. Use at the boundary where reduce/dispatch results leave`);
builderLines.push(` * author code and enter the wire.`);
builderLines.push(` */`);
builderLines.push(
  `export function materializeAccept(pending: ReadonlyArray<PendingEffect>): {`,
);
builderLines.push(`  effects: Wire.Effect[];`);
builderLines.push(`  continuations: Wire.ContinuationMap;`);
builderLines.push(`} {`);
builderLines.push(`  const effects: Wire.Effect[] = [];`);
builderLines.push(`  const continuations: Wire.ContinuationMap = {};`);
builderLines.push(`  for (const pe of pending) {`);
builderLines.push(`    const { __continuation, ...effect } = pe as PendingEffect & { __continuation?: Wire.ContinuationToken };`);
builderLines.push(`    effects.push(effect as Wire.Effect);`);
builderLines.push(`    if (__continuation !== undefined) {`);
builderLines.push(`      continuations[(effect as Wire.Effect).effectId] = __continuation;`);
builderLines.push(`    }`);
builderLines.push(`  }`);
builderLines.push(`  return { effects, continuations };`);
builderLines.push(`}`);
builderLines.push(``);

fs.writeFileSync(path.join(OUT_DIR, "builders.ts"), builderLines.join("\n"));

// -----------------------------------------------------------------------------
// emit version.ts
// -----------------------------------------------------------------------------

fs.writeFileSync(
  path.join(OUT_DIR, "version.ts"),
  `${GENERATED_HEADER}
/**
 * The wire-protocol version this package implements. Bumped in lockstep with
 * any breaking change to schema/reducer-runtime.schema.json. At bundle load
 * time the Kotlin adapter refuses bundles whose major version differs.
 */
export const REDUCER_CONTRACT_VERSION = ${JSON.stringify(pkg.version)} as const;
`,
);

// -----------------------------------------------------------------------------
// log
// -----------------------------------------------------------------------------

console.log(
  `✓ reducer-contract codegen: emitted wire.ts, zod.ts, builders.ts, version.ts, bundle.ts (${pkg.version})`,
);
