#!/usr/bin/env node
// Emits TS types, Zod schemas, typed effect builders, and a version constant
// from schema/reducer-runtime.schema.json. Outputs to ./generated.
//
// Why a bespoke generator and not `json-schema-to-ts` + `json-schema-to-zod`?
// - The schema is small and has specific conventions (oneOf-with-const-tag as
//   our sum-type idiom). Hand-rolling ~250 lines lets us emit *exactly* the
//   shapes we want (e.g. union members as named types, builders with the
//   effectId enforced, a single `version.ts` file). It also keeps the
//   reducer-contract package free of extra third-party codegen deps whose
//   output we'd still have to post-process.
// - If the schema grows large, swap this for `json-schema-to-zod` behind the
//   same output paths; consumers won't notice.

import fs from "node:fs";
import path from "node:path";
import { parseArgs } from "node:util";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const DEFAULT_PACKAGE_ROOT = path.resolve(__dirname, "..");

type JsonSchemaType =
  | "string"
  | "number"
  | "integer"
  | "boolean"
  | "null"
  | "array"
  | "object";

type JsonSchemaNode = {
  $ref?: string;
  const?: unknown;
  oneOf?: JsonSchemaNode[];
  anyOf?: JsonSchemaNode[];
  type?: JsonSchemaType | JsonSchemaType[];
  enum?: unknown[];
  pattern?: string;
  minLength?: number;
  minimum?: number;
  format?: string;
  items?: JsonSchemaNode;
  minItems?: number;
  maxItems?: number;
  additionalProperties?: false | JsonSchemaNode;
  properties?: Record<string, JsonSchemaNode>;
  required?: string[];
  description?: string;
  title?: string;
};

type JsonSchemaDocument = {
  $defs: Record<string, JsonSchemaNode>;
};

type VersionProperty = {
  name: string;
  type: string;
};

type ReducerOperation = {
  name: string;
  input: string | null;
  output: string;
  nullableOutput?: boolean;
  maybePromise?: boolean;
};

type OperationsContract = {
  versionProperty: VersionProperty;
  operations: ReducerOperation[];
};

type PackageManifest = {
  version: string;
};

export type GenerateMode = "write" | "check";

export type GenerateReducerContractOptions = {
  mode?: GenerateMode;
  packageRoot?: string;
  outputRoot?: string;
  schemaPath?: string;
  operationsPath?: string;
  packagePath?: string;
};

export type RenderedReducerContract = {
  version: string;
  artifacts: ReadonlyMap<string, string>;
};

export type GenerateReducerContractResult = {
  version: string;
  files: readonly string[];
};

export function renderReducerContract(
  options: Omit<GenerateReducerContractOptions, "mode" | "outputRoot"> = {},
): RenderedReducerContract {
  const packageRoot = path.resolve(options.packageRoot ?? DEFAULT_PACKAGE_ROOT);
  const SCHEMA_PATH = path.resolve(
    options.schemaPath ??
      path.join(packageRoot, "schema", "reducer-runtime.schema.json"),
  );
  const OPERATIONS_PATH = path.resolve(
    options.operationsPath ??
      path.join(packageRoot, "schema", "reducer-runtime.operations.json"),
  );
  const PKG_PATH = path.resolve(
    options.packagePath ?? path.join(packageRoot, "package.json"),
  );
  const artifacts = new Map<string, string>();

  const GENERATED_HEADER = `// @generated by packages/reducer-contract/scripts/generate.ts
// DO NOT EDIT BY HAND. Edit schema/reducer-runtime.schema.json and rerun \`pnpm generate\`.
`;
  const BUNDLE_GENERATED_HEADER = `// @generated by packages/reducer-contract/scripts/generate.ts
// DO NOT EDIT BY HAND. Edit schema/reducer-runtime.operations.json and rerun \`pnpm generate\`.
`;

  const schema = readJson(SCHEMA_PATH) as JsonSchemaDocument;
  const operationsContract = readJson(OPERATIONS_PATH) as OperationsContract;
  const pkg = readJson(PKG_PATH) as PackageManifest;
  const JSON_VALUE_TYPE =
    "string | number | boolean | null | JsonValue[] | { [key: string]: JsonValue }";

  function readJson(inputPath: string): unknown {
    try {
      return JSON.parse(fs.readFileSync(inputPath, "utf8"));
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      throw new Error(`${inputPath}: unable to read JSON: ${message}`);
    }
  }

  function inputError(
    inputPath: string,
    jsonPath: string,
    message: string,
  ): never {
    throw new Error(`${inputPath}#${jsonPath}: ${message}`);
  }

  function isRecord(value: unknown): value is Record<string, unknown> {
    return typeof value === "object" && value !== null && !Array.isArray(value);
  }

  function pointerSegment(value: string): string {
    return value.replace(/~/g, "~0").replace(/\//g, "~1");
  }

  function assertAllowedKeys(
    value: Record<string, unknown>,
    allowed: ReadonlySet<string>,
    inputPath: string,
    jsonPath: string,
  ): void {
    for (const key of Object.keys(value)) {
      if (!allowed.has(key)) {
        return inputError(
          inputPath,
          `${jsonPath}/${pointerSegment(key)}`,
          `unsupported keyword ${JSON.stringify(key)}`,
        );
      }
    }
  }

  const METADATA_KEYS = ["description", "title"] as const;

  function validateJsonValueDefinition(value: unknown, jsonPath: string): void {
    if (!isRecord(value)) {
      inputError(SCHEMA_PATH, jsonPath, "JsonValue must be an object schema");
    }
    assertAllowedKeys(
      value,
      new Set([...METADATA_KEYS, "anyOf"]),
      SCHEMA_PATH,
      jsonPath,
    );
    if (!Array.isArray(value.anyOf)) {
      inputError(
        SCHEMA_PATH,
        `${jsonPath}/anyOf`,
        "JsonValue requires anyOf[]",
      );
    }
    const actualTypes = value.anyOf.map((member, index) => {
      if (!isRecord(member)) {
        return inputError(
          SCHEMA_PATH,
          `${jsonPath}/anyOf/${index}`,
          "JsonValue union members must be object schemas",
        );
      }
      assertAllowedKeys(
        member,
        new Set(["type"]),
        SCHEMA_PATH,
        `${jsonPath}/anyOf/${index}`,
      );
      return member.type;
    });
    const expectedTypes = [
      "object",
      "array",
      "string",
      "number",
      "boolean",
      "null",
    ];
    if (
      actualTypes.length !== expectedTypes.length ||
      actualTypes.some((type, index) => type !== expectedTypes[index])
    ) {
      inputError(
        SCHEMA_PATH,
        `${jsonPath}/anyOf`,
        `JsonValue must list exactly ${expectedTypes.join(", ")}`,
      );
    }
  }

  function validateSchemaNode(
    value: unknown,
    jsonPath: string,
    definitions: Record<string, unknown>,
  ): asserts value is JsonSchemaNode {
    if (!isRecord(value)) {
      inputError(SCHEMA_PATH, jsonPath, "schema nodes must be objects");
    }
    const structuralKeys = ["$ref", "const", "oneOf", "anyOf", "type"].filter(
      (key) => Object.prototype.hasOwnProperty.call(value, key),
    );
    if (structuralKeys.length !== 1) {
      inputError(
        SCHEMA_PATH,
        jsonPath,
        "schema nodes require exactly one of $ref, const, oneOf, anyOf, or type",
      );
    }

    const structuralKey = structuralKeys[0]!;
    if (structuralKey === "$ref") {
      assertAllowedKeys(
        value,
        new Set([...METADATA_KEYS, "$ref"]),
        SCHEMA_PATH,
        jsonPath,
      );
      if (typeof value.$ref !== "string") {
        inputError(SCHEMA_PATH, `${jsonPath}/$ref`, "$ref must be a string");
      }
      const referencedName = refName(value.$ref, `${jsonPath}/$ref`);
      if (!Object.prototype.hasOwnProperty.call(definitions, referencedName)) {
        inputError(
          SCHEMA_PATH,
          `${jsonPath}/$ref`,
          `unknown definition ${JSON.stringify(referencedName)}`,
        );
      }
      return;
    }

    if (structuralKey === "const") {
      assertAllowedKeys(
        value,
        new Set([...METADATA_KEYS, "const"]),
        SCHEMA_PATH,
        jsonPath,
      );
      if (value.const === undefined) {
        inputError(
          SCHEMA_PATH,
          `${jsonPath}/const`,
          "undefined constants are unsupported",
        );
      }
      return;
    }

    if (structuralKey === "oneOf" || structuralKey === "anyOf") {
      assertAllowedKeys(
        value,
        new Set([...METADATA_KEYS, structuralKey]),
        SCHEMA_PATH,
        jsonPath,
      );
      const members = value[structuralKey];
      if (!Array.isArray(members) || members.length === 0) {
        inputError(
          SCHEMA_PATH,
          `${jsonPath}/${structuralKey}`,
          `${structuralKey} must be a non-empty array`,
        );
      }
      members.forEach((member, index) =>
        validateSchemaNode(
          member,
          `${jsonPath}/${structuralKey}/${index}`,
          definitions,
        ),
      );
      return;
    }

    const rawType = value.type;
    if (Array.isArray(rawType)) {
      assertAllowedKeys(
        value,
        new Set([...METADATA_KEYS, "type"]),
        SCHEMA_PATH,
        jsonPath,
      );
      if (rawType.length === 0 || new Set(rawType).size !== rawType.length) {
        inputError(
          SCHEMA_PATH,
          `${jsonPath}/type`,
          "type unions must be non-empty and unique",
        );
      }
      for (const [index, type] of rawType.entries()) {
        if (
          ![
            "string",
            "number",
            "integer",
            "boolean",
            "null",
            "array",
            "object",
          ].includes(String(type))
        ) {
          inputError(
            SCHEMA_PATH,
            `${jsonPath}/type/${index}`,
            `unsupported schema type ${JSON.stringify(type)}`,
          );
        }
      }
      return;
    }

    if (typeof rawType !== "string") {
      inputError(
        SCHEMA_PATH,
        `${jsonPath}/type`,
        "type must be a string or string array",
      );
    }
    const baseKeys = [...METADATA_KEYS, "type"];
    switch (rawType) {
      case "string": {
        assertAllowedKeys(
          value,
          new Set([...baseKeys, "enum", "pattern", "minLength"]),
          SCHEMA_PATH,
          jsonPath,
        );
        if (value.enum !== undefined) {
          if (
            !Array.isArray(value.enum) ||
            value.enum.length === 0 ||
            value.enum.some((entry) => typeof entry !== "string")
          ) {
            inputError(
              SCHEMA_PATH,
              `${jsonPath}/enum`,
              "string enums must contain strings",
            );
          }
        }
        if (value.pattern !== undefined && typeof value.pattern !== "string") {
          inputError(
            SCHEMA_PATH,
            `${jsonPath}/pattern`,
            "pattern must be a string",
          );
        }
        if (
          value.minLength !== undefined &&
          (typeof value.minLength !== "number" ||
            !Number.isInteger(value.minLength) ||
            value.minLength < 0)
        ) {
          inputError(
            SCHEMA_PATH,
            `${jsonPath}/minLength`,
            "minLength must be a non-negative integer",
          );
        }
        if (
          [
            value.enum !== undefined,
            value.pattern !== undefined,
            value.minLength !== undefined,
          ].filter(Boolean).length > 1
        ) {
          inputError(
            SCHEMA_PATH,
            jsonPath,
            "enum, pattern, and minLength cannot be combined by this generator",
          );
        }
        return;
      }
      case "number":
      case "integer": {
        assertAllowedKeys(
          value,
          new Set([...baseKeys, "minimum", "format"]),
          SCHEMA_PATH,
          jsonPath,
        );
        if (value.minimum !== undefined && !Number.isFinite(value.minimum)) {
          inputError(
            SCHEMA_PATH,
            `${jsonPath}/minimum`,
            "minimum must be finite",
          );
        }
        if (
          value.format !== undefined &&
          !(rawType === "integer" && value.format === "int64")
        ) {
          inputError(
            SCHEMA_PATH,
            `${jsonPath}/format`,
            `unsupported numeric format ${JSON.stringify(value.format)}`,
          );
        }
        return;
      }
      case "boolean":
      case "null":
        assertAllowedKeys(value, new Set(baseKeys), SCHEMA_PATH, jsonPath);
        return;
      case "array": {
        assertAllowedKeys(
          value,
          new Set([...baseKeys, "items", "minItems", "maxItems"]),
          SCHEMA_PATH,
          jsonPath,
        );
        if (value.items === undefined) {
          inputError(
            SCHEMA_PATH,
            `${jsonPath}/items`,
            "array schemas require items",
          );
        }
        validateSchemaNode(value.items, `${jsonPath}/items`, definitions);
        for (const key of ["minItems", "maxItems"] as const) {
          const bound = value[key];
          if (
            bound !== undefined &&
            (typeof bound !== "number" || !Number.isInteger(bound) || bound < 0)
          ) {
            inputError(
              SCHEMA_PATH,
              `${jsonPath}/${key}`,
              `${key} must be a non-negative integer`,
            );
          }
        }
        if (
          typeof value.minItems === "number" &&
          typeof value.maxItems === "number" &&
          value.minItems > value.maxItems
        ) {
          inputError(SCHEMA_PATH, jsonPath, "minItems cannot exceed maxItems");
        }
        return;
      }
      case "object": {
        assertAllowedKeys(
          value,
          new Set([
            ...baseKeys,
            "properties",
            "required",
            "additionalProperties",
          ]),
          SCHEMA_PATH,
          jsonPath,
        );
        const properties = value.properties;
        const additionalProperties = value.additionalProperties;
        if (!isRecord(properties) && !isRecord(additionalProperties)) {
          inputError(
            SCHEMA_PATH,
            jsonPath,
            "object schemas require properties or a schema-valued additionalProperties",
          );
        }
        if (properties !== undefined) {
          if (!isRecord(properties)) {
            inputError(
              SCHEMA_PATH,
              `${jsonPath}/properties`,
              "properties must be an object",
            );
          }
          for (const [name, property] of Object.entries(properties)) {
            validateSchemaNode(
              property,
              `${jsonPath}/properties/${pointerSegment(name)}`,
              definitions,
            );
          }
        }
        if (
          additionalProperties !== undefined &&
          additionalProperties !== false
        ) {
          validateSchemaNode(
            additionalProperties,
            `${jsonPath}/additionalProperties`,
            definitions,
          );
        }
        if (value.required !== undefined) {
          if (
            !Array.isArray(value.required) ||
            value.required.some((name) => typeof name !== "string") ||
            new Set(value.required).size !== value.required.length
          ) {
            inputError(
              SCHEMA_PATH,
              `${jsonPath}/required`,
              "required must contain unique strings",
            );
          }
          for (const name of value.required) {
            if (
              !properties ||
              !Object.prototype.hasOwnProperty.call(properties, name)
            ) {
              inputError(
                SCHEMA_PATH,
                `${jsonPath}/required`,
                `required property ${JSON.stringify(name)} is not declared`,
              );
            }
          }
        }
        return;
      }
      default:
        inputError(
          SCHEMA_PATH,
          `${jsonPath}/type`,
          `unsupported schema type ${JSON.stringify(rawType)}`,
        );
    }
  }

  function validateSchemaDocument(
    value: unknown,
  ): asserts value is JsonSchemaDocument {
    if (!isRecord(value)) {
      inputError(SCHEMA_PATH, "", "schema document must be an object");
    }
    assertAllowedKeys(
      value,
      new Set([
        "$schema",
        "$id",
        "title",
        "description",
        "type",
        "properties",
        "required",
        "additionalProperties",
        "$defs",
      ]),
      SCHEMA_PATH,
      "",
    );
    if (!isRecord(value.$defs) || Object.keys(value.$defs).length === 0) {
      inputError(SCHEMA_PATH, "/$defs", "$defs must be a non-empty object");
    }
    if (value.type !== "object") {
      inputError(SCHEMA_PATH, "/type", "the root schema must have type object");
    }
    if (!isRecord(value.properties)) {
      inputError(
        SCHEMA_PATH,
        "/properties",
        "root properties must be an object",
      );
    }
    for (const [name, property] of Object.entries(value.properties)) {
      validateSchemaNode(
        property,
        `/properties/${pointerSegment(name)}`,
        value.$defs,
      );
    }
    if (
      !Array.isArray(value.required) ||
      value.required.some((name) => typeof name !== "string") ||
      new Set(value.required).size !== value.required.length
    ) {
      inputError(
        SCHEMA_PATH,
        "/required",
        "root required must contain unique strings",
      );
    }
    for (const name of value.required) {
      if (!Object.prototype.hasOwnProperty.call(value.properties, name)) {
        inputError(
          SCHEMA_PATH,
          "/required",
          `required root property ${JSON.stringify(name)} is not declared`,
        );
      }
    }
    if (value.additionalProperties !== false) {
      inputError(
        SCHEMA_PATH,
        "/additionalProperties",
        "the root schema must reject additional properties",
      );
    }
    for (const [name, definition] of Object.entries(value.$defs)) {
      const definitionPath = `/$defs/${pointerSegment(name)}`;
      if (name === "JsonValue") {
        validateJsonValueDefinition(definition, definitionPath);
      } else {
        validateSchemaNode(definition, definitionPath, value.$defs);
      }
    }
  }

  function validateOperationsContract(
    value: unknown,
  ): asserts value is OperationsContract {
    if (!isRecord(value)) {
      inputError(OPERATIONS_PATH, "", "operations contract must be an object");
    }
    assertAllowedKeys(
      value,
      new Set(["$schema", "description", "versionProperty", "operations"]),
      OPERATIONS_PATH,
      "",
    );
    if (!isRecord(value.versionProperty)) {
      inputError(
        OPERATIONS_PATH,
        "/versionProperty",
        "versionProperty must be an object",
      );
    }
    assertAllowedKeys(
      value.versionProperty,
      new Set(["name", "type"]),
      OPERATIONS_PATH,
      "/versionProperty",
    );
    if (
      typeof value.versionProperty.name !== "string" ||
      !/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(value.versionProperty.name)
    ) {
      inputError(
        OPERATIONS_PATH,
        "/versionProperty/name",
        "name must be a valid TypeScript property name",
      );
    }
    if (typeof value.versionProperty.type !== "string") {
      inputError(
        OPERATIONS_PATH,
        "/versionProperty/type",
        "type must be a string",
      );
    }
    if (!Array.isArray(value.operations)) {
      inputError(OPERATIONS_PATH, "/operations", "operations must be an array");
    }
    const seenNames = new Set<string>();
    value.operations.forEach((operation, index) => {
      const operationPath = `/operations/${index}`;
      if (!isRecord(operation)) {
        inputError(
          OPERATIONS_PATH,
          operationPath,
          "operations must be objects",
        );
      }
      assertAllowedKeys(
        operation,
        new Set(["name", "input", "output", "nullableOutput", "maybePromise"]),
        OPERATIONS_PATH,
        operationPath,
      );
      if (
        typeof operation.name !== "string" ||
        !/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(operation.name)
      ) {
        inputError(
          OPERATIONS_PATH,
          `${operationPath}/name`,
          "name must be a valid TypeScript method name",
        );
      }
      if (seenNames.has(operation.name)) {
        inputError(
          OPERATIONS_PATH,
          `${operationPath}/name`,
          `duplicate operation ${JSON.stringify(operation.name)}`,
        );
      }
      seenNames.add(operation.name);
      if (!(typeof operation.input === "string" || operation.input === null)) {
        inputError(
          OPERATIONS_PATH,
          `${operationPath}/input`,
          "input must be a wire type name or null",
        );
      }
      if (typeof operation.output !== "string") {
        inputError(
          OPERATIONS_PATH,
          `${operationPath}/output`,
          "output must be a string",
        );
      }
      for (const key of ["nullableOutput", "maybePromise"] as const) {
        if (
          operation[key] !== undefined &&
          typeof operation[key] !== "boolean"
        ) {
          inputError(
            OPERATIONS_PATH,
            `${operationPath}/${key}`,
            `${key} must be boolean`,
          );
        }
      }
    });
  }

  function validatePackageManifest(
    value: unknown,
  ): asserts value is PackageManifest {
    if (
      !isRecord(value) ||
      typeof value.version !== "string" ||
      value.version.length === 0
    ) {
      inputError(
        PKG_PATH,
        "/version",
        "package version must be a non-empty string",
      );
    }
  }

  validateSchemaDocument(schema);
  validateOperationsContract(operationsContract);
  validatePackageManifest(pkg);
  const defs = schema.$defs;

  // -----------------------------------------------------------------------------
  // helpers
  // -----------------------------------------------------------------------------

  function refName(ref: string, jsonPath = "$ref"): string {
    const m = /^#\/\$defs\/(.+)$/.exec(ref);
    if (!m) {
      inputError(
        SCHEMA_PATH,
        jsonPath,
        `unsupported $ref ${JSON.stringify(ref)}`,
      );
    }
    return m[1]!;
  }

  function isConst(prop: JsonSchemaNode | undefined): boolean {
    return (
      prop !== undefined && Object.prototype.hasOwnProperty.call(prop, "const")
    );
  }

  function tsTypeOf(
    def: JsonSchemaNode,
    refPrefix = "",
    jsonPath = "$",
  ): string {
    if (def.$ref) return refPrefix + refName(def.$ref, `${jsonPath}/$ref`);
    if (isConst(def)) return JSON.stringify(def.const);
    if (def.oneOf || def.anyOf) {
      const unionKey = def.oneOf ? "oneOf" : "anyOf";
      const members = (def.oneOf ?? def.anyOf ?? []).map((member, index) =>
        tsTypeOf(member, refPrefix, `${jsonPath}/${unionKey}/${index}`),
      );
      return members.join(" | ");
    }
    if (Array.isArray(def.type)) {
      return def.type
        .map((type, index) =>
          tsTypeOf({ type }, refPrefix, `${jsonPath}/type/${index}`),
        )
        .join(" | ");
    }
    switch (def.type) {
      case "string":
        if (Array.isArray(def.enum) && def.enum.length > 0) {
          return def.enum.map((value) => JSON.stringify(value)).join(" | ");
        }
        return "string";
      case "number":
        return "number";
      case "integer":
        return "number";
      case "boolean":
        return "boolean";
      case "null":
        return "null";
      case "array":
        if (!def.items) {
          inputError(
            SCHEMA_PATH,
            `${jsonPath}/items`,
            "array schemas require items",
          );
        }
        return `Array<${tsTypeOf(def.items, refPrefix, `${jsonPath}/items`)}>`;
      case "object":
        if (def.additionalProperties && !def.properties) {
          return `Record<string, ${tsTypeOf(def.additionalProperties, refPrefix, `${jsonPath}/additionalProperties`)}>`;
        }
        if (def.properties) {
          const required = new Set(def.required ?? []);
          const entries: string[] = Object.entries(def.properties).map(
            ([k, v]) => {
              const opt = required.has(k) ? "" : "?";
              return `${JSON.stringify(k)}${opt}: ${tsTypeOf(v, refPrefix, `${jsonPath}/properties/${k}`)}`;
            },
          );
          return `{ ${entries.join("; ")} }`;
        }
        return inputError(
          SCHEMA_PATH,
          jsonPath,
          "object schemas require properties or a schema-valued additionalProperties",
        );
      default:
        inputError(
          SCHEMA_PATH,
          `${jsonPath}/type`,
          `unsupported schema type ${JSON.stringify(def.type)}`,
        );
    }
  }

  function zodExprOf(def: JsonSchemaNode, jsonPath = "$"): string {
    if (def.$ref) return `${refName(def.$ref, `${jsonPath}/$ref`)}Schema`;
    if (isConst(def)) return `z.literal(${JSON.stringify(def.const)})`;
    if (def.oneOf) {
      const key = unionDiscriminator(def);
      const members = def.oneOf.map((member, index) =>
        zodExprOf(member, `${jsonPath}/oneOf/${index}`),
      );
      return key
        ? `z.discriminatedUnion(${JSON.stringify(key)}, [${members.join(", ")}])`
        : `z.union([${members.join(", ")}])`;
    }
    if (def.anyOf) {
      const members = def.anyOf.map((member, index) =>
        zodExprOf(member, `${jsonPath}/anyOf/${index}`),
      );
      return `z.union([${members.join(", ")}])`;
    }
    if (Array.isArray(def.type)) {
      const members = def.type.map((type, index) =>
        zodExprOf({ type }, `${jsonPath}/type/${index}`),
      );
      return `z.union([${members.join(", ")}])`;
    }
    switch (def.type) {
      case "string":
        if (Array.isArray(def.enum) && def.enum.length > 0) {
          return `z.enum([${def.enum.map((value) => JSON.stringify(value)).join(", ")}])`;
        }
        return def.pattern
          ? `z.string().regex(new RegExp(${JSON.stringify(def.pattern)}))`
          : def.minLength
            ? `z.string().min(${def.minLength})`
            : "z.string()";
      case "number":
        return `z.number().finite()${typeof def.minimum === "number" ? `.gte(${def.minimum})` : ""}`;
      case "integer":
        if (def.format === "int64") {
          return 'z.number().refine(Number.isInteger, { message: "Expected integer" })';
        }
        return `z.number().int()${typeof def.minimum === "number" ? `.gte(${def.minimum})` : ""}`;
      case "boolean":
        return "z.boolean()";
      case "null":
        return "z.null()";
      case "array": {
        if (!def.items) {
          inputError(
            SCHEMA_PATH,
            `${jsonPath}/items`,
            "array schemas require items",
          );
        }
        let expr: string = `z.array(${zodExprOf(def.items, `${jsonPath}/items`)})`;
        if (typeof def.minItems === "number") {
          expr += `.min(${def.minItems})`;
        }
        if (typeof def.maxItems === "number") {
          expr += `.max(${def.maxItems})`;
        }
        return expr;
      }
      case "object":
        if (def.additionalProperties && !def.properties) {
          return `z.record(z.string(), ${zodExprOf(def.additionalProperties, `${jsonPath}/additionalProperties`)})`;
        }
        if (def.properties) {
          const required = new Set(def.required ?? []);
          const entries: string[] = Object.entries(def.properties).map(
            ([k, v]) => {
              const schemaExpr: string = zodExprOf(
                v,
                `${jsonPath}/properties/${k}`,
              );
              return required.has(k)
                ? `${JSON.stringify(k)}: ${schemaExpr}`
                : `${JSON.stringify(k)}: ${schemaExpr}.optional()`;
            },
          );
          const obj: string = `z.object({ ${entries.join(", ")} })`;
          return def.additionalProperties === false ? `${obj}.strict()` : obj;
        }
        return inputError(
          SCHEMA_PATH,
          jsonPath,
          "object schemas require properties or a schema-valued additionalProperties",
        );
      default:
        inputError(
          SCHEMA_PATH,
          `${jsonPath}/type`,
          `unsupported schema type ${JSON.stringify(def.type)}`,
        );
    }
  }

  /**
   * Which discriminator key a oneOf uses, by peeking at its first member's
   * required literal properties. We support exactly two: `kind` and `type`.
   */
  function unionDiscriminator(def: JsonSchemaNode): "kind" | "type" | null {
    if (!def.oneOf) return null;
    for (const member of def.oneOf) {
      const target = member.$ref ? defs[refName(member.$ref)] : member;
      if (!target?.properties) continue;
      if (target.properties.kind && isConst(target.properties.kind))
        return "kind";
      if (target.properties.type && isConst(target.properties.type))
        return "type";
    }
    return null;
  }

  function renderUnionZod(def: JsonSchemaNode, jsonPath = "$"): string {
    if (!def.oneOf) {
      inputError(SCHEMA_PATH, `${jsonPath}/oneOf`, "oneOf is required");
    }
    const key = unionDiscriminator(def);
    const members = def.oneOf.map((member, index) =>
      zodExprOf(member, `${jsonPath}/oneOf/${index}`),
    );
    if (key) {
      return `z.discriminatedUnion(${JSON.stringify(key)}, [${members.join(", ")}])`;
    }
    return `z.union([${members.join(", ")}])`;
  }

  function assertKnownWireType(typeName: string, fieldPath: string): void {
    if (!defs[typeName]) {
      inputError(
        OPERATIONS_PATH,
        fieldPath,
        `unknown reducer wire type ${JSON.stringify(typeName)}`,
      );
    }
  }

  function wireType(typeName: string): string {
    return `Wire.${typeName}`;
  }

  function operationReturnType(operation: ReducerOperation): string {
    const base = wireType(operation.output);
    const output = operation.nullableOutput ? `${base} | null` : base;
    return operation.maybePromise ? `MaybePromise<${output}>` : output;
  }

  function renderOperationSignature(operation: ReducerOperation): string {
    if (operation.input === null) {
      return `  ${operation.name}(): ${operationReturnType(operation)};`;
    }
    const inputType = wireType(operation.input);
    const returnType = operationReturnType(operation);
    const inline = `  ${operation.name}(input: ${inputType}): ${returnType};`;
    if (inline.length <= 80) return inline;
    return [
      `  ${operation.name}(`,
      `    input: ${inputType},`,
      `  ): ${returnType};`,
    ].join("\n");
  }

  // -----------------------------------------------------------------------------
  // emit wire.ts (types)
  // -----------------------------------------------------------------------------

  const typeLines = [GENERATED_HEADER];
  typeLines.push(`/* eslint-disable */`);
  typeLines.push(``);

  for (const [name, def] of Object.entries(defs)) {
    const typeExpr = name === "JsonValue" ? JSON_VALUE_TYPE : tsTypeOf(def);
    typeLines.push(`export type ${name} = ${typeExpr};`);
    typeLines.push(``);
  }

  artifacts.set("generated/wire.ts", typeLines.join("\n"));

  // -----------------------------------------------------------------------------
  // emit src/bundle.ts (callable reducer bundle boundary)
  // -----------------------------------------------------------------------------

  assertKnownWireType(
    operationsContract.versionProperty.type,
    "/versionProperty/type",
  );
  for (const [index, operation] of operationsContract.operations.entries()) {
    if (typeof operation.input === "string") {
      assertKnownWireType(operation.input, `/operations/${index}/input`);
    }
    if (operation.input === null && operation.name !== "projectStatic") {
      inputError(
        OPERATIONS_PATH,
        `/operations/${index}/input`,
        "only projectStatic may be zero-argument",
      );
    }
    if (operation.name === "projectStatic" && operation.input !== null) {
      inputError(
        OPERATIONS_PATH,
        `/operations/${index}/input`,
        "projectStatic must stay zero-argument",
      );
    }
    assertKnownWireType(operation.output, `/operations/${index}/output`);
  }

  function renderBundleContract({
    wireImportPath,
    authoredReducerImport,
  }: {
    wireImportPath: string;
    authoredReducerImport: string;
  }): string {
    const bundleLines = [BUNDLE_GENERATED_HEADER];
    bundleLines.push(`/* eslint-disable */`);
    bundleLines.push(
      `import type * as Wire from ${JSON.stringify(wireImportPath)};`,
    );
    bundleLines.push(
      `import { REDUCER_CONTRACT_VERSION } from "../generated/version";`,
    );
    bundleLines.push(``);
    bundleLines.push(`export type MaybePromise<T> = T | Promise<T>;`);
    bundleLines.push(``);
    bundleLines.push(`/**`);
    bundleLines.push(
      ` * Canonical erased reducer boundary for \`createReducerBundle(...)\`.`,
    );
    bundleLines.push(` *`);
    bundleLines.push(` * The callable method list is generated from`);
    bundleLines.push(
      ` * \`schema/reducer-runtime.operations.json\`; payload DTOs come from`,
    );
    bundleLines.push(` * \`schema/reducer-runtime.schema.json\`.`);
    bundleLines.push(` *`);
    bundleLines.push(
      ` * This interface models the host/guest surface only. The concrete`,
    );
    bundleLines.push(
      ` * authored bundle stays strongly typed in \`${authoredReducerImport}\`, but every`,
    );
    bundleLines.push(` * cross-runtime caller should agree on this shape.`);
    bundleLines.push(` */`);
    bundleLines.push(`export interface ReducerBundleContract {`);
    bundleLines.push(
      `  readonly ${operationsContract.versionProperty.name}: ${wireType(
        operationsContract.versionProperty.type,
      )};`,
    );
    for (const operation of operationsContract.operations) {
      bundleLines.push(renderOperationSignature(operation));
    }
    bundleLines.push(`}`);
    bundleLines.push(``);
    bundleLines.push(`/**`);
    bundleLines.push(
      ` * Validates an imported module value at the reducer host/guest boundary.`,
    );
    bundleLines.push(` *`);
    bundleLines.push(
      ` * The required callable members are generated from the same operation`,
    );
    bundleLines.push(
      ` * authority as \`ReducerBundleContract\`, so runtime admission cannot drift`,
    );
    bundleLines.push(` * from the published TypeScript interface.`);
    bundleLines.push(` */`);
    bundleLines.push(`export function assertReducerBundleContract(`);
    bundleLines.push(`  value: unknown,`);
    bundleLines.push(`  source: string,`);
    bundleLines.push(`): asserts value is ReducerBundleContract {`);
    bundleLines.push(
      `  if (!value || typeof value !== "object" || Array.isArray(value)) {`,
    );
    bundleLines.push(
      "    throw new Error(`Reducer bundle ${source} did not export an object.`);",
    );
    bundleLines.push(`  }`);
    bundleLines.push(``);
    bundleLines.push(`  const bundle = value as Record<string, unknown>;`);
    bundleLines.push(
      `  if (bundle.${operationsContract.versionProperty.name} !== REDUCER_CONTRACT_VERSION) {`,
    );
    bundleLines.push(`    throw new Error(`);
    bundleLines.push(
      '      `Reducer bundle ${source} requires contract ${REDUCER_CONTRACT_VERSION}; received ${String(bundle.reducerContractVersion ?? "missing")}.`,',
    );
    bundleLines.push(`    );`);
    bundleLines.push(`  }`);
    bundleLines.push(``);
    bundleLines.push(`  for (const method of [`);
    for (const operation of operationsContract.operations) {
      bundleLines.push(`    ${JSON.stringify(operation.name)},`);
    }
    bundleLines.push(`  ] as const) {`);
    bundleLines.push(`    if (typeof bundle[method] !== "function") {`);
    bundleLines.push(
      "      throw new Error(`Reducer bundle ${source} is missing ${method}().`);",
    );
    bundleLines.push(`    }`);
    bundleLines.push(`  }`);
    bundleLines.push(`}`);
    bundleLines.push(``);
    return bundleLines.join("\n");
  }

  artifacts.set(
    "src/bundle.ts",
    renderBundleContract({
      wireImportPath: "../generated/wire",
      authoredReducerImport: "@dreamboard-games/sdk/reducer",
    }),
  );

  // -----------------------------------------------------------------------------
  // emit zod.ts (schemas)
  // -----------------------------------------------------------------------------

  const zodLines = [GENERATED_HEADER];
  zodLines.push(`/* eslint-disable */`);
  zodLines.push(`import type * as Wire from "./wire";`);
  zodLines.push(`import { z } from "zod";`);
  zodLines.push(``);

  // Emit schemas as `const` with explicit `z.ZodTypeAny` typing and a `get`
  // helper so we can forward-reference within oneOf members. We do NOT need
  // truly recursive schemas; a simple topological emit by alphabetical then
  // override for leaves works for this contract.
  //
  // Strategy: emit leaf scalars first (JsonValue, strings, etc.), then compound
  // types. We compute a dependency order via a lightweight topo sort.

  function refsIn(
    def: JsonSchemaNode,
    acc: Set<string> = new Set<string>(),
  ): Set<string> {
    if (def.$ref) acc.add(refName(def.$ref));
    for (const member of def.oneOf ?? []) refsIn(member, acc);
    for (const member of def.anyOf ?? []) refsIn(member, acc);
    if (def.items) refsIn(def.items, acc);
    if (
      def.additionalProperties !== undefined &&
      def.additionalProperties !== false
    ) {
      refsIn(def.additionalProperties, acc);
    }
    for (const property of Object.values(def.properties ?? {})) {
      refsIn(property, acc);
    }
    return acc;
  }

  const order: string[] = [];
  const seen = new Set<string>();
  const onStack = new Set<string>();
  function visit(name: string): void {
    if (seen.has(name)) return;
    if (onStack.has(name)) {
      // Cycle: defer. Our contract has none; fail loudly if one appears.
      inputError(
        SCHEMA_PATH,
        `/$defs/${pointerSegment(name)}`,
        "schema cycles require explicit lazy handling",
      );
    }
    onStack.add(name);
    const definition = defs[name];
    if (!definition) {
      inputError(
        SCHEMA_PATH,
        `/$defs/${pointerSegment(name)}`,
        "definition is missing",
      );
    }
    const deps = refsIn(definition);
    for (const d of deps) {
      if (d !== name) visit(d);
    }
    onStack.delete(name);
    seen.add(name);
    order.push(name);
  }
  for (const name of Object.keys(defs)) visit(name);

  for (const name of order) {
    const def = defs[name]!;
    if (name === "JsonValue") {
      zodLines.push(`let JsonValueSchemaInternal: z.ZodType<Wire.JsonValue>;`);
      zodLines.push(
        `JsonValueSchemaInternal = z.lazy(() => z.union([z.record(z.string(), JsonValueSchemaInternal), z.array(JsonValueSchemaInternal), z.string(), z.number(), z.boolean(), z.null()]));`,
      );
      zodLines.push(`export const JsonValueSchema = JsonValueSchemaInternal;`);
      zodLines.push(``);
      continue;
    }
    const definitionPath = `/$defs/${pointerSegment(name)}`;
    const expr = def.oneOf
      ? renderUnionZod(def, definitionPath)
      : zodExprOf(def, definitionPath);
    zodLines.push(`export const ${name}Schema = ${expr};`);
    zodLines.push(``);
  }

  artifacts.set("generated/zod.ts", zodLines.join("\n"));

  // -----------------------------------------------------------------------------
  // emit builders.ts (typed constructors for every Effect variant)
  // -----------------------------------------------------------------------------

  type EffectVariant = {
    tag: string;
    props: Array<{ name: string; type: string; required: boolean }>;
  };

  const effectDefinition = defs.Effect;
  if (!effectDefinition?.oneOf) {
    inputError(
      SCHEMA_PATH,
      "/$defs/Effect/oneOf",
      "Effect must declare oneOf[]",
    );
  }
  const effectVariants: EffectVariant[] = effectDefinition.oneOf.map(
    (member, index) => {
      const memberPath = `/$defs/Effect/oneOf/${index}`;
      if (!member.$ref) {
        inputError(SCHEMA_PATH, memberPath, "Effect variants must use $ref");
      }
      const name = refName(member.$ref, `${memberPath}/$ref`);
      const definition = defs[name];
      if (!definition?.properties) {
        inputError(
          SCHEMA_PATH,
          `/$defs/${pointerSegment(name)}`,
          "Effect variants must be object schemas with properties",
        );
      }
      const tag = definition.properties.type?.const;
      if (typeof tag !== "string" || !/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(tag)) {
        inputError(
          SCHEMA_PATH,
          `/$defs/${pointerSegment(name)}/properties/type/const`,
          "effect type must be a valid TypeScript method name",
        );
      }
      const required = new Set(definition.required ?? []);
      if (!required.has("type") || !required.has("effectId")) {
        inputError(
          SCHEMA_PATH,
          `/$defs/${pointerSegment(name)}/required`,
          "effect variants must require type and effectId",
        );
      }
      const propEntries = Object.entries(definition.properties)
        .filter(([key]) => key !== "type" && key !== "effectId")
        .map(([key, value]) => {
          if (!/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(key)) {
            inputError(
              SCHEMA_PATH,
              `/$defs/${pointerSegment(name)}/properties/${pointerSegment(key)}`,
              "effect builder properties must be valid TypeScript identifiers",
            );
          }
          return {
            name: key,
            type: tsTypeOf(
              value,
              "Wire.",
              `/$defs/${pointerSegment(name)}/properties/${pointerSegment(key)}`,
            ),
            required: required.has(key),
          };
        });
      return { tag, props: propEntries };
    },
  );

  const builderLines = [GENERATED_HEADER];
  builderLines.push(`/* eslint-disable */`);
  builderLines.push(`import type * as Wire from "./wire";`);
  builderLines.push(``);
  builderLines.push(
    `/**`,
    ` * Typed effect constructors. Authors MUST go through these; hand-constructing`,
    ` * Wire.Effect objects is banned by convention because it's how wire drift`,
    ` * re-enters the codebase.`,
    ` *`,
    ` * The \`effectId\` is minted by the runtime (see createEffectIdMinter below),`,
    ` * not by the author. Each builder returns a \`PendingEffect\` that carries`,
    ` * the optional continuation; the reducer bundle's accept materializer splits`,
    ` * pending effects into the wire's \`effects[]\` + \`continuations\` map.`,
    ` */`,
  );
  builderLines.push(``);
  builderLines.push(`export type PendingEffect = Wire.Effect & {`);
  builderLines.push(`  readonly __continuation?: Wire.ContinuationToken;`);
  builderLines.push(`};`);
  builderLines.push(``);
  builderLines.push(`export type EffectIdMinter = () => Wire.EffectId;`);
  builderLines.push(``);
  builderLines.push(`/**`);
  builderLines.push(
    ` * Produces sequential, deterministic effect ids scoped to a single accept`,
  );
  builderLines.push(
    ` * payload: "ef0", "ef1", ... . Uniqueness only needs to be local to the`,
  );
  builderLines.push(
    ` * payload because the host consumes and discards them per dispatch.`,
  );
  builderLines.push(` */`);
  builderLines.push(`export function createEffectIdMinter(): EffectIdMinter {`);
  builderLines.push(`  let i = 0;`);
  builderLines.push(`  return () => \`ef\${i++}\` as Wire.EffectId;`);
  builderLines.push(`}`);
  builderLines.push(``);
  builderLines.push(`export type EffectBuilders = {`);
  for (const v of effectVariants) {
    const args = v.props.map(
      (p) => `${p.name}${p.required ? "" : "?"}: ${p.type}`,
    );
    builderLines.push(
      `  ${v.tag}(args: { ${args.join("; ")} }, continuation?: Wire.ContinuationToken): PendingEffect;`,
    );
  }
  builderLines.push(`};`);
  builderLines.push(``);
  builderLines.push(
    `export function createEffectBuilders(mint: EffectIdMinter): EffectBuilders {`,
  );
  builderLines.push(`  return {`);
  for (const v of effectVariants) {
    const argNames = v.props.map((p) => p.name);
    const argSpread = argNames.map((n) => `${n}: args.${n}`).join(", ");
    builderLines.push(`    ${v.tag}(args, continuation) {`);
    builderLines.push(
      `      const effect = { effectId: mint(), type: "${v.tag}" as const, ${argSpread} };`,
    );
    builderLines.push(`      return continuation === undefined`);
    builderLines.push(`        ? (effect as PendingEffect)`);
    builderLines.push(
      `        : Object.assign(effect, { __continuation: continuation });`,
    );
    builderLines.push(`    },`);
  }
  builderLines.push(`  };`);
  builderLines.push(`}`);
  builderLines.push(``);
  builderLines.push(`/**`);
  builderLines.push(
    ` * Takes a list of PendingEffects and splits them into the canonical wire`,
  );
  builderLines.push(
    ` * shape: \`effects[]\` (stripped of \`__continuation\`) + \`continuations\` map`,
  );
  builderLines.push(
    ` * keyed by effectId. Use at the boundary where reduce/dispatch results leave`,
  );
  builderLines.push(` * author code and enter the wire.`);
  builderLines.push(` */`);
  builderLines.push(
    `export function materializeAccept(pending: ReadonlyArray<PendingEffect>): {`,
  );
  builderLines.push(`  effects: Wire.Effect[];`);
  builderLines.push(`  continuations: Wire.ContinuationMap;`);
  builderLines.push(`} {`);
  builderLines.push(`  const effects: Wire.Effect[] = [];`);
  builderLines.push(`  const continuations: Wire.ContinuationMap = {};`);
  builderLines.push(`  for (const pe of pending) {`);
  builderLines.push(
    `    const { __continuation, ...effect } = pe as PendingEffect & { __continuation?: Wire.ContinuationToken };`,
  );
  builderLines.push(`    effects.push(effect as Wire.Effect);`);
  builderLines.push(`    if (__continuation !== undefined) {`);
  builderLines.push(
    `      continuations[(effect as Wire.Effect).effectId] = __continuation;`,
  );
  builderLines.push(`    }`);
  builderLines.push(`  }`);
  builderLines.push(`  return { effects, continuations };`);
  builderLines.push(`}`);
  builderLines.push(``);

  artifacts.set("generated/builders.ts", builderLines.join("\n"));

  // -----------------------------------------------------------------------------
  // emit version.ts
  // -----------------------------------------------------------------------------

  artifacts.set(
    "generated/version.ts",
    `${GENERATED_HEADER}
/**
 * The wire-protocol version this package implements. Bumped in lockstep with
 * any breaking change to schema/reducer-runtime.schema.json. At bundle load
 * time hosts refuse bundles whose major version differs.
 */
export const REDUCER_CONTRACT_VERSION = ${JSON.stringify(pkg.version)} as const;
`,
  );

  return { version: pkg.version, artifacts };
}

function renderOptions(
  options: GenerateReducerContractOptions,
): Omit<GenerateReducerContractOptions, "mode" | "outputRoot"> {
  return {
    packageRoot: options.packageRoot,
    schemaPath: options.schemaPath,
    operationsPath: options.operationsPath,
    packagePath: options.packagePath,
  };
}

function outputRoot(options: GenerateReducerContractOptions): string {
  return path.resolve(
    options.outputRoot ?? options.packageRoot ?? DEFAULT_PACKAGE_ROOT,
  );
}

function listFiles(directory: string): string[] {
  if (!fs.existsSync(directory)) return [];
  const files: string[] = [];
  const visit = (current: string): void => {
    for (const entry of fs.readdirSync(current, { withFileTypes: true })) {
      const absolute = path.join(current, entry.name);
      if (entry.isDirectory()) {
        visit(absolute);
      } else if (entry.isFile()) {
        files.push(absolute);
      }
    }
  };
  visit(directory);
  return files.sort();
}

function removeEmptyDirectories(directory: string): void {
  if (!fs.existsSync(directory)) return;
  for (const entry of fs.readdirSync(directory, { withFileTypes: true })) {
    if (entry.isDirectory()) {
      removeEmptyDirectories(path.join(directory, entry.name));
    }
  }
  if (fs.readdirSync(directory).length === 0) {
    fs.rmdirSync(directory);
  }
}

export class GeneratedArtifactDriftError extends Error {
  readonly drift: readonly string[];

  constructor(drift: readonly string[]) {
    super(
      [
        "reducer-contract generated artifacts are out of sync:",
        ...drift.map((entry) => `  - ${entry}`),
        "Run `pnpm generate` and commit the regenerated files.",
      ].join("\n"),
    );
    this.name = "GeneratedArtifactDriftError";
    this.drift = drift;
  }
}

export function writeReducerContract(
  options: Omit<GenerateReducerContractOptions, "mode"> = {},
): GenerateReducerContractResult {
  const rendered = renderReducerContract(renderOptions(options));
  const destinationRoot = outputRoot(options);
  const expectedFiles = new Set(rendered.artifacts.keys());
  const generatedDirectory = path.join(destinationRoot, "generated");

  for (const absolute of listFiles(generatedDirectory)) {
    const relative = path.relative(destinationRoot, absolute);
    if (!expectedFiles.has(relative)) {
      fs.rmSync(absolute, { force: true });
    }
  }
  removeEmptyDirectories(generatedDirectory);

  for (const [relative, contents] of rendered.artifacts) {
    const absolute = path.join(destinationRoot, relative);
    fs.mkdirSync(path.dirname(absolute), { recursive: true });
    if (
      !fs.existsSync(absolute) ||
      fs.readFileSync(absolute, "utf8") !== contents
    ) {
      fs.writeFileSync(absolute, contents);
    }
  }

  return {
    version: rendered.version,
    files: [...rendered.artifacts.keys()],
  };
}

export function checkReducerContract(
  options: Omit<GenerateReducerContractOptions, "mode"> = {},
): GenerateReducerContractResult {
  const rendered = renderReducerContract(renderOptions(options));
  const destinationRoot = outputRoot(options);
  const drift: string[] = [];

  for (const [relative, expected] of rendered.artifacts) {
    const absolute = path.join(destinationRoot, relative);
    if (!fs.existsSync(absolute)) {
      drift.push(`${relative} is missing`);
    } else if (fs.readFileSync(absolute, "utf8") !== expected) {
      drift.push(`${relative} is stale`);
    }
  }

  const expectedGeneratedFiles = new Set(
    [...rendered.artifacts.keys()].filter((relative) =>
      relative.startsWith("generated/"),
    ),
  );
  for (const absolute of listFiles(path.join(destinationRoot, "generated"))) {
    const relative = path.relative(destinationRoot, absolute);
    if (!expectedGeneratedFiles.has(relative)) {
      drift.push(`${relative} is unexpected`);
    }
  }

  if (drift.length > 0) {
    throw new GeneratedArtifactDriftError(drift);
  }

  return {
    version: rendered.version,
    files: [...rendered.artifacts.keys()],
  };
}

export function generateReducerContract(
  options: GenerateReducerContractOptions = {},
): GenerateReducerContractResult {
  return options.mode === "check"
    ? checkReducerContract(options)
    : writeReducerContract(options);
}

export function runGenerateCli(argv: readonly string[]): number {
  const { values } = parseArgs({
    args: [...argv],
    options: {
      check: { type: "boolean", default: false },
      "output-root": { type: "string" },
      "schema-path": { type: "string" },
      "operations-path": { type: "string" },
      "package-path": { type: "string" },
    },
    strict: true,
    allowPositionals: false,
  });
  const result = generateReducerContract({
    mode: values.check ? "check" : "write",
    outputRoot: values["output-root"],
    schemaPath: values["schema-path"],
    operationsPath: values["operations-path"],
    packagePath: values["package-path"],
  });
  console.log(
    values.check
      ? `✓ reducer-contract generated artifacts are clean (${result.version}).`
      : `✓ reducer-contract codegen: emitted wire.ts, zod.ts, builders.ts, version.ts, and bundle.ts (${result.version})`,
  );
  return 0;
}

const isMain =
  process.argv[1] !== undefined &&
  path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);

if (isMain) {
  try {
    process.exitCode = runGenerateCli(process.argv.slice(2));
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error));
    process.exitCode = 1;
  }
}
