// @generated by packages/reducer-contract/scripts/generate-ts.mjs
// DO NOT EDIT BY HAND. Edit schema/reducer-runtime.operations.json and rerun `pnpm generate`.

/* eslint-disable */
import type * as Wire from "../generated/wire";

export type MaybePromise<T> = T | Promise<T>;

/**
 * Canonical erased reducer boundary for `createReducerBundle(...)`.
 *
 * The callable method list is generated from
 * `schema/reducer-runtime.operations.json`; payload DTOs come from
 * `schema/reducer-runtime.schema.json`.
 *
 * This interface models the host/guest surface only. The concrete
 * authored bundle stays strongly typed in `@dreamboard-games/sdk/reducer`, but every
 * cross-runtime caller should agree on this shape.
 */
export interface ReducerBundleContract {
  readonly reducerContractVersion: Wire.ReducerContractVersion;
  initialize(
    input: Wire.InitializeRequest,
  ): MaybePromise<Wire.ReducerSessionState>;
  initializePhase(
    input: Wire.InitializePhaseRequest,
  ): MaybePromise<Wire.ReducerSessionState>;
  validateInput(
    input: Wire.ValidateInputRequest,
  ): MaybePromise<Wire.ReducerInputValidationResult>;
  reduce(input: Wire.ReduceRequest): MaybePromise<Wire.ReduceResult>;
  dispatch(input: Wire.DispatchRequest): MaybePromise<Wire.DispatchResult>;
  projectStatic(): Wire.BoardStaticProjection | null;
  projectSeatsDynamic(
    input: Wire.ProjectSeatsDynamicRequest,
  ): Wire.SeatProjectionBundle;
}
