// @generated by packages/reducer-contract/scripts/generate.ts
// DO NOT EDIT BY HAND. Edit schema/reducer-runtime.operations.json and rerun `pnpm generate`.

/* eslint-disable */
import type * as Wire from "../generated/wire";
import { REDUCER_CONTRACT_VERSION } from "../generated/version";

export type MaybePromise<T> = T | Promise<T>;

/**
 * Canonical erased reducer boundary for `createReducerBundle(...)`.
 *
 * The callable method list is generated from
 * `schema/reducer-runtime.operations.json`; payload DTOs come from
 * `schema/reducer-runtime.schema.json`.
 *
 * This interface models the host/guest surface only. The concrete
 * authored bundle stays strongly typed in `@dreamboard-games/sdk/reducer`, but every
 * cross-runtime caller should agree on this shape.
 */
export interface ReducerBundleContract {
  readonly reducerContractVersion: Wire.ReducerContractVersion;
  initialize(
    input: Wire.InitializeRequest,
  ): MaybePromise<Wire.ReducerSessionState>;
  initializePhase(
    input: Wire.InitializePhaseRequest,
  ): MaybePromise<Wire.ReducerSessionState>;
  validateInput(
    input: Wire.ValidateInputRequest,
  ): MaybePromise<Wire.ReducerInputValidationResult>;
  reduce(input: Wire.ReduceRequest): MaybePromise<Wire.ReduceResult>;
  dispatch(input: Wire.DispatchRequest): MaybePromise<Wire.DispatchResult>;
  projectStatic(): Wire.BoardStaticProjection | null;
  projectSeatsDynamic(
    input: Wire.ProjectSeatsDynamicRequest,
  ): Wire.SeatProjectionBundle;
}

/**
 * Validates an imported module value at the reducer host/guest boundary.
 *
 * The required callable members are generated from the same operation
 * authority as `ReducerBundleContract`, so runtime admission cannot drift
 * from the published TypeScript interface.
 */
export function assertReducerBundleContract(
  value: unknown,
  source: string,
): asserts value is ReducerBundleContract {
  if (!value || typeof value !== "object" || Array.isArray(value)) {
    throw new Error(`Reducer bundle ${source} did not export an object.`);
  }

  const bundle = value as Record<string, unknown>;
  if (bundle.reducerContractVersion !== REDUCER_CONTRACT_VERSION) {
    throw new Error(
      `Reducer bundle ${source} requires contract ${REDUCER_CONTRACT_VERSION}; received ${String(bundle.reducerContractVersion ?? "missing")}.`,
    );
  }

  for (const method of [
    "initialize",
    "initializePhase",
    "validateInput",
    "reduce",
    "dispatch",
    "projectStatic",
    "projectSeatsDynamic",
  ] as const) {
    if (typeof bundle[method] !== "function") {
      throw new Error(`Reducer bundle ${source} is missing ${method}().`);
    }
  }
}
