// Generated by dreamboard scaffold.
import { defineScenario } from "../testing-types";

export default defineScenario({
  id: "smoke-initial-turn",
  description:
    "Sanity check that the scaffolded workspace boots into its initial phase.",
  from: "initial-turn",
  when: async () => undefined,
  then: ({ expect, interactions, players, state }) => {
    const playerIds = players();
    expect(playerIds).toHaveLength(playerIds.length);
    expect(playerIds.length).toBeGreaterThanOrEqual(1);
    expect(state()).toBe("wakeup");
    expect(interactions(playerIds[0]!).length).toBeGreaterThanOrEqual(1);
  },
});
