/**
 * Generated file.
 * Do not edit directly.
 */

export const literals = {
  playerIds: ["player-1", "player-2"] as const,
  phaseNames: [] as readonly string[],
  boardLayouts: ["generic", "hex", "square"] as const,
  setupOptionIds: [] as const,
  setupProfileIds: ["standard", "test-end-game", "test-fixed-spaces"] as const,
  cardSetIds: ["apprentice-cards", "order-cards"] as const,
  cardTypes: ["apprentice-trial", "architects-plan", "foreman", "forge-order", "furniture-commission", "grand-atelier", "guild-scholar", "inspiration", "lumber-stash", "masters-display", "mixed-set", "patrons-favor", "quick-delivery", "reassign", "row-of-pride", "spare-hands", "stone-cache", "stone-sculpture", "tireless-master", "weavers-request"] as const,
  cardIds: ["apprentice-trial", "architects-plan", "foreman", "forge-order", "furniture-commission", "grand-atelier", "guild-scholar", "inspiration", "lumber-stash", "masters-display", "mixed-set", "patrons-favor", "quick-delivery", "reassign", "row-of-pride", "spare-hands", "stone-cache", "stone-sculpture", "tireless-master", "weavers-request"] as const,
  deckIds: ["apprentice-deck", "apprentice-discard", "order-deck", "order-discard"] as const,
  handIds: ["apprentice-hand", "apprentice-tableau", "order-hand"] as const,
  sharedZoneIds: ["apprentice-deck", "apprentice-discard", "order-deck", "order-discard"] as const,
  playerZoneIds: ["apprentice-hand", "apprentice-tableau", "order-hand"] as const,
  zoneIds: ["apprentice-deck", "apprentice-discard", "apprentice-hand", "apprentice-tableau", "order-deck", "order-discard", "order-hand"] as const,
  resourceIds: ["coin", "stone", "wood"] as const,
  resourcePresentationById: {
  "coin": {
    "label": "Coin",
    "icon": "🪙"
  },
  "stone": {
    "label": "Stone",
    "icon": "🪨"
  },
  "wood": {
    "label": "Wood",
    "icon": "🪵"
  }
} as const,
  pieceTypeIds: ["apprentice", "master"] as const,
  pieceIds: ["apprentice-p1-1", "apprentice-p1-2", "apprentice-p1-3", "apprentice-p1-4", "apprentice-p2-1", "apprentice-p2-2", "apprentice-p2-3", "apprentice-p2-4", "master-p1", "master-p2"] as const,
  dieTypeIds: [] as const,
  dieIds: [] as const,
  boardTemplateIds: ["action-board-template", "wake-up-track-template", "workshop-mat-template"] as const,
  boardTypeIds: [] as const,
  boardBaseIds: ["action-board", "wake-up-track", "workshop-mat"] as const,
  boardIds: ["action-board", "wake-up-track", "workshop-mat:player-1", "workshop-mat:player-2"] as const,
  boardContainerIds: [] as const,
  relationTypeIds: ["adjacent"] as const,
  edgeIds: ["square-edge:0,0::0,1", "square-edge:0,0::1,0", "square-edge:0,1::0,2", "square-edge:0,1::1,1", "square-edge:0,2::0,3", "square-edge:0,2::1,2", "square-edge:0,3::0,4", "square-edge:0,3::1,3", "square-edge:0,4::1,4", "square-edge:1,0::1,1", "square-edge:1,0::2,0", "square-edge:1,1::1,2", "square-edge:1,1::2,1", "square-edge:1,2::1,3", "square-edge:1,2::2,2", "square-edge:1,3::1,4", "square-edge:1,3::2,3", "square-edge:1,4::2,4", "square-edge:2,0::2,1", "square-edge:2,0::3,0", "square-edge:2,1::2,2", "square-edge:2,1::3,1", "square-edge:2,2::2,3", "square-edge:2,2::3,2", "square-edge:2,3::2,4", "square-edge:2,3::3,3", "square-edge:2,4::3,4", "square-edge:3,0::3,1", "square-edge:3,0::4,0", "square-edge:3,1::3,2", "square-edge:3,1::4,1", "square-edge:3,2::3,3", "square-edge:3,2::4,2", "square-edge:3,3::3,4", "square-edge:3,3::4,3", "square-edge:4,0::4,1", "square-edge:4,1::4,2", "square-edge:4,2::4,3"] as const,
  edgeTypeIds: [] as const,
  vertexIds: ["square-vertex:0,0", "square-vertex:0,1", "square-vertex:0,2", "square-vertex:0,3", "square-vertex:0,4", "square-vertex:1,0", "square-vertex:1,1", "square-vertex:1,2", "square-vertex:1,3", "square-vertex:1,4", "square-vertex:2,0", "square-vertex:2,1", "square-vertex:2,2", "square-vertex:2,3", "square-vertex:2,4", "square-vertex:3,0", "square-vertex:3,1", "square-vertex:3,2", "square-vertex:3,3", "square-vertex:3,4", "square-vertex:4,0", "square-vertex:4,1", "square-vertex:4,2", "square-vertex:4,3"] as const,
  vertexTypeIds: [] as const,
  spaceIds: ["apothecary", "cell-r0-c0", "cell-r0-c1", "cell-r0-c2", "cell-r0-c3", "cell-r1-c0", "cell-r1-c1", "cell-r1-c2", "cell-r1-c3", "cell-r2-c0", "cell-r2-c1", "cell-r2-c2", "cell-r2-c3", "forge", "guild-hall", "library", "lumberyard", "market", "masons-lodge", "patrons-estate", "quarry", "trade-post", "training-hall", "wake-up-1", "wake-up-2", "wake-up-3", "wake-up-4", "workshop"] as const,
  spaceTypeIds: ["cell", "fixed", "variable", "wake-up-slot"] as const,
  handVisibilityById: {
  "apprentice-hand": "ownerOnly",
  "apprentice-tableau": "public",
  "order-hand": "ownerOnly",
} as const,
  zoneVisibilityById: {
  "apprentice-deck": "hidden",
  "apprentice-discard": "public",
  "apprentice-hand": "ownerOnly",
  "apprentice-tableau": "public",
  "order-deck": "hidden",
  "order-discard": "public",
  "order-hand": "ownerOnly",
} as const,
  cardSetIdByCardId: {
  "apprentice-trial": "order-cards",
  "architects-plan": "order-cards",
  "foreman": "apprentice-cards",
  "forge-order": "order-cards",
  "furniture-commission": "order-cards",
  "grand-atelier": "order-cards",
  "guild-scholar": "apprentice-cards",
  "inspiration": "apprentice-cards",
  "lumber-stash": "apprentice-cards",
  "masters-display": "order-cards",
  "mixed-set": "order-cards",
  "patrons-favor": "apprentice-cards",
  "quick-delivery": "apprentice-cards",
  "reassign": "apprentice-cards",
  "row-of-pride": "order-cards",
  "spare-hands": "apprentice-cards",
  "stone-cache": "apprentice-cards",
  "stone-sculpture": "order-cards",
  "tireless-master": "apprentice-cards",
  "weavers-request": "order-cards",
} as const,
  cardTypeByCardId: {
  "apprentice-trial": "apprentice-trial",
  "architects-plan": "architects-plan",
  "foreman": "foreman",
  "forge-order": "forge-order",
  "furniture-commission": "furniture-commission",
  "grand-atelier": "grand-atelier",
  "guild-scholar": "guild-scholar",
  "inspiration": "inspiration",
  "lumber-stash": "lumber-stash",
  "masters-display": "masters-display",
  "mixed-set": "mixed-set",
  "patrons-favor": "patrons-favor",
  "quick-delivery": "quick-delivery",
  "reassign": "reassign",
  "row-of-pride": "row-of-pride",
  "spare-hands": "spare-hands",
  "stone-cache": "stone-cache",
  "stone-sculpture": "stone-sculpture",
  "tireless-master": "tireless-master",
  "weavers-request": "weavers-request",
} as const,
  setupChoiceIdsByOptionId: {

} as const,
  cardSetIdsBySharedZoneId: {
  "apprentice-deck": ["apprentice-cards"] as const,
  "apprentice-discard": ["apprentice-cards"] as const,
  "order-deck": ["order-cards"] as const,
  "order-discard": ["order-cards"] as const,
} as const,
  sharedZoneIdsByCardSetId: {
  "apprentice-cards": ["apprentice-deck", "apprentice-discard"] as const,
  "order-cards": ["order-deck", "order-discard"] as const,
} as const,
  homeSharedZoneIdsByCardType: {
  "apprentice-trial": [] as const,
  "architects-plan": [] as const,
  "foreman": [] as const,
  "forge-order": [] as const,
  "furniture-commission": [] as const,
  "grand-atelier": [] as const,
  "guild-scholar": [] as const,
  "inspiration": [] as const,
  "lumber-stash": [] as const,
  "masters-display": [] as const,
  "mixed-set": [] as const,
  "patrons-favor": [] as const,
  "quick-delivery": [] as const,
  "reassign": [] as const,
  "row-of-pride": [] as const,
  "spare-hands": [] as const,
  "stone-cache": [] as const,
  "stone-sculpture": [] as const,
  "tireless-master": [] as const,
  "weavers-request": [] as const,
} as const,
  homeSharedZoneIdByCardType: {

} as const,
  cardSetIdsByPlayerZoneId: {
  "apprentice-hand": ["apprentice-cards"] as const,
  "apprentice-tableau": ["apprentice-cards"] as const,
  "order-hand": ["order-cards"] as const,
} as const,
} as const;
