import type { CardId } from "../../shared/manifest-contract.ts";

export function submit(seat: number, cardId: CardId) {
  return {
    actor: { seat },
    interactionId: "submit" as const,
    params: { cardId },
  };
}

export const COMPLETE_GAME_COMMANDS = [
  submit(0, "festival-banner-18"),
  submit(1, "tea-cup-7"),
  submit(0, "festival-banner-12"),
  submit(1, "lantern-13"),
  submit(0, "lantern-19"),
  submit(1, "tea-cup-15"),
  submit(0, "lantern-5"),
  submit(1, "festival-banner-14"),
  submit(0, "lantern-1"),
  submit(1, "festival-banner-20"),
  submit(0, "tea-cup-2"),
  submit(1, "tea-cup-14"),
  submit(0, "lantern-18"),
  submit(1, "lantern-15"),
  submit(0, "lantern-12"),
  submit(1, "lantern-6"),
  submit(0, "festival-banner-17"),
  submit(1, "tea-cup-20"),
  submit(0, "festival-banner-1"),
  submit(1, "festival-banner-3"),
  submit(0, "lantern-11"),
  submit(1, "lantern-7"),
  submit(0, "festival-banner-7"),
  submit(1, "tea-cup-10"),
] as const;

export const TIED_WINNER_COMMANDS = [
  submit(0, "festival-banner-1"),
  submit(1, "tea-cup-19"),
  submit(0, "lantern-18"),
  submit(1, "tea-cup-15"),
  submit(0, "tea-cup-3"),
  submit(1, "festival-banner-6"),
  submit(0, "festival-banner-3"),
  submit(1, "tea-cup-14"),
  submit(0, "tea-cup-12"),
  submit(1, "lantern-16"),
  submit(0, "lantern-9"),
  submit(1, "festival-banner-17"),
  submit(0, "tea-cup-8"),
  submit(1, "lantern-5"),
  submit(0, "lantern-13"),
  submit(1, "festival-banner-14"),
  submit(0, "tea-cup-13"),
  submit(1, "lantern-4"),
  submit(0, "festival-banner-12"),
  submit(1, "tea-cup-11"),
  submit(0, "festival-banner-11"),
  submit(1, "tea-cup-18"),
  submit(0, "tea-cup-10"),
  submit(1, "tea-cup-7"),
] as const;

export const LOWER_PLACE_TIE_COMMANDS = [
  submit(0, "tea-cup-9"),
  submit(1, "lantern-3"),
  submit(2, "tea-cup-16"),
  submit(0, "tea-cup-11"),
  submit(1, "tea-cup-12"),
  submit(2, "tea-cup-3"),
  submit(0, "lantern-5"),
  submit(1, "lantern-10"),
  submit(2, "tea-cup-8"),
  submit(0, "lantern-11"),
  submit(1, "festival-banner-1"),
  submit(2, "tea-cup-17"),
  submit(0, "tea-cup-2"),
  submit(1, "festival-banner-13"),
  submit(2, "festival-banner-19"),
  submit(0, "lantern-2"),
  submit(1, "tea-cup-5"),
  submit(2, "tea-cup-7"),
  submit(0, "lantern-16"),
  submit(1, "lantern-18"),
  submit(2, "festival-banner-17"),
  submit(0, "lantern-17"),
  submit(1, "festival-banner-2"),
  submit(2, "lantern-13"),
  submit(0, "festival-banner-14"),
  submit(1, "festival-banner-8"),
  submit(2, "lantern-15"),
  submit(0, "tea-cup-20"),
  submit(1, "festival-banner-7"),
  submit(2, "festival-banner-12"),
  submit(0, "lantern-12"),
  submit(1, "festival-banner-10"),
  submit(2, "festival-banner-15"),
  submit(0, "tea-cup-10"),
  submit(1, "lantern-14"),
  submit(2, "lantern-19"),
] as const;

export const ROUND_SCORING_COMMANDS = [
  submit(0, "festival-banner-14"),
  submit(1, "tea-cup-1"),
  submit(2, "lantern-8"),
  submit(0, "festival-banner-1"),
  submit(1, "tea-cup-15"),
  submit(2, "festival-banner-15"),
  submit(0, "festival-banner-2"),
  submit(1, "festival-banner-5"),
  submit(2, "lantern-16"),
  submit(0, "festival-banner-11"),
  submit(1, "tea-cup-17"),
  submit(2, "lantern-4"),
  submit(0, "festival-banner-13"),
  submit(1, "tea-cup-3"),
  submit(2, "tea-cup-8"),
  submit(0, "festival-banner-18"),
  submit(1, "festival-banner-16"),
  submit(2, "tea-cup-2"),
] as const;

export const SUPPORTED_2_COMMANDS = [
  submit(0, "festival-banner-3"),
  submit(1, "lantern-18"),
  submit(0, "lantern-20"),
  submit(1, "lantern-9"),
  submit(0, "lantern-15"),
  submit(1, "festival-banner-16"),
  submit(0, "festival-banner-10"),
  submit(1, "festival-banner-14"),
  submit(0, "tea-cup-13"),
  submit(1, "lantern-6"),
  submit(0, "festival-banner-4"),
  submit(1, "festival-banner-13"),
  submit(0, "festival-banner-7"),
  submit(1, "tea-cup-3"),
  submit(0, "tea-cup-12"),
  submit(1, "lantern-19"),
  submit(0, "tea-cup-7"),
  submit(1, "tea-cup-2"),
  submit(0, "festival-banner-17"),
  submit(1, "festival-banner-20"),
  submit(0, "tea-cup-17"),
  submit(1, "lantern-14"),
  submit(0, "festival-banner-5"),
  submit(1, "festival-banner-6"),
] as const;

export const SUPPORTED_3_COMMANDS = [
  submit(0, "festival-banner-3"),
  submit(1, "lantern-18"),
  submit(2, "lantern-9"),
  submit(0, "festival-banner-16"),
  submit(1, "lantern-20"),
  submit(2, "lantern-15"),
  submit(0, "festival-banner-10"),
  submit(1, "tea-cup-13"),
  submit(2, "festival-banner-14"),
  submit(0, "lantern-6"),
  submit(1, "festival-banner-13"),
  submit(2, "festival-banner-4"),
  submit(0, "lantern-19"),
  submit(1, "festival-banner-7"),
  submit(2, "tea-cup-3"),
  submit(0, "tea-cup-7"),
  submit(1, "tea-cup-2"),
  submit(2, "tea-cup-12"),
  submit(0, "festival-banner-20"),
  submit(1, "festival-banner-17"),
  submit(2, "tea-cup-17"),
  submit(0, "festival-banner-5"),
  submit(1, "lantern-14"),
  submit(2, "festival-banner-6"),
  submit(0, "lantern-1"),
  submit(1, "festival-banner-9"),
  submit(2, "tea-cup-14"),
  submit(0, "lantern-11"),
  submit(1, "tea-cup-5"),
  submit(2, "festival-banner-11"),
  submit(0, "tea-cup-16"),
  submit(1, "tea-cup-1"),
  submit(2, "tea-cup-15"),
  submit(0, "lantern-8"),
  submit(1, "tea-cup-4"),
  submit(2, "tea-cup-9"),
] as const;

export const SUPPORTED_4_COMMANDS = [
  submit(0, "festival-banner-3"),
  submit(1, "lantern-18"),
  submit(2, "lantern-9"),
  submit(3, "lantern-20"),
  submit(0, "festival-banner-10"),
  submit(1, "lantern-15"),
  submit(2, "festival-banner-16"),
  submit(3, "festival-banner-14"),
  submit(0, "festival-banner-13"),
  submit(1, "festival-banner-4"),
  submit(2, "tea-cup-13"),
  submit(3, "lantern-6"),
  submit(0, "tea-cup-3"),
  submit(1, "lantern-19"),
  submit(2, "tea-cup-12"),
  submit(3, "festival-banner-7"),
  submit(0, "tea-cup-7"),
  submit(1, "tea-cup-2"),
  submit(2, "festival-banner-20"),
  submit(3, "festival-banner-17"),
  submit(0, "festival-banner-5"),
  submit(1, "tea-cup-17"),
  submit(2, "lantern-14"),
  submit(3, "festival-banner-6"),
  submit(0, "tea-cup-14"),
  submit(1, "lantern-1"),
  submit(2, "festival-banner-9"),
  submit(3, "lantern-11"),
  submit(0, "tea-cup-15"),
  submit(1, "tea-cup-5"),
  submit(2, "festival-banner-11"),
  submit(3, "tea-cup-1"),
  submit(0, "lantern-8"),
  submit(1, "tea-cup-4"),
  submit(2, "tea-cup-16"),
  submit(3, "tea-cup-9"),
  submit(0, "lantern-4"),
  submit(1, "festival-banner-8"),
  submit(2, "festival-banner-19"),
  submit(3, "tea-cup-6"),
  submit(0, "tea-cup-11"),
  submit(1, "festival-banner-12"),
  submit(2, "tea-cup-10"),
  submit(3, "lantern-7"),
  submit(0, "lantern-3"),
  submit(1, "festival-banner-2"),
  submit(2, "lantern-10"),
  submit(3, "festival-banner-18"),
] as const;

export const SUPPORTED_5_COMMANDS = [
  submit(0, "festival-banner-3"),
  submit(1, "lantern-18"),
  submit(2, "lantern-9"),
  submit(3, "lantern-20"),
  submit(4, "lantern-15"),
  submit(0, "lantern-6"),
  submit(1, "festival-banner-16"),
  submit(2, "festival-banner-14"),
  submit(3, "festival-banner-10"),
  submit(4, "tea-cup-13"),
  submit(0, "tea-cup-3"),
  submit(1, "lantern-19"),
  submit(2, "festival-banner-13"),
  submit(3, "festival-banner-4"),
  submit(4, "festival-banner-7"),
  submit(0, "tea-cup-2"),
  submit(1, "festival-banner-20"),
  submit(2, "festival-banner-17"),
  submit(3, "tea-cup-12"),
  submit(4, "tea-cup-7"),
  submit(0, "lantern-14"),
  submit(1, "festival-banner-6"),
  submit(2, "festival-banner-5"),
  submit(3, "tea-cup-14"),
  submit(4, "tea-cup-17"),
  submit(0, "lantern-1"),
  submit(1, "festival-banner-9"),
  submit(2, "lantern-11"),
  submit(3, "tea-cup-5"),
  submit(4, "festival-banner-11"),
  submit(0, "tea-cup-1"),
  submit(1, "tea-cup-15"),
  submit(2, "tea-cup-16"),
  submit(3, "tea-cup-9"),
  submit(4, "lantern-8"),
  submit(0, "festival-banner-19"),
  submit(1, "tea-cup-4"),
  submit(2, "tea-cup-6"),
  submit(3, "lantern-4"),
  submit(4, "festival-banner-8"),
  submit(0, "lantern-7"),
  submit(1, "festival-banner-2"),
  submit(2, "tea-cup-11"),
  submit(3, "festival-banner-12"),
  submit(4, "tea-cup-10"),
  submit(0, "lantern-3"),
  submit(1, "tea-cup-8"),
  submit(2, "tea-cup-18"),
  submit(3, "lantern-10"),
  submit(4, "festival-banner-18"),
  submit(0, "lantern-16"),
  submit(1, "lantern-2"),
  submit(2, "lantern-13"),
  submit(3, "lantern-12"),
  submit(4, "lantern-5"),
  submit(0, "festival-banner-1"),
  submit(1, "lantern-17"),
  submit(2, "tea-cup-19"),
  submit(3, "festival-banner-15"),
  submit(4, "tea-cup-20"),
] as const;
