export {
  BROWSER_INTERACTION_ACTUATOR_KINDS,
  BROWSER_INTERACTION_ATTRIBUTES,
  BROWSER_INTERACTION_CANDIDATE_STATES,
  BROWSER_INTERACTION_READINESS_VALUES,
  BROWSER_INTERACTION_RECORD_ROLES,
  DREAMBOARD_BROWSER_INTERACTION_PROTOCOL_NAME,
  DREAMBOARD_BROWSER_INTERACTION_PROTOCOL_VERSION,
  GAMEPLAY_BROWSER_INTERACTION_EFFECT_KINDS,
  GAMEPLAY_BROWSER_INTERACTION_INTENTS,
  GAMEPLAY_BROWSER_INTERACTION_SURFACE,
} from "./constants.js";
export {
  compareStableJson,
  decodeCanonicalCandidateValue,
  encodeCanonicalCandidateValue,
  type CanonicalBrowserInteractionValue,
} from "./canonical.js";
export {
  assertBrowserInteractionEffectPattern,
  browserInteractionEffectPatternMatches,
  decodeBrowserInteractionEffect,
  decodeBrowserInteractionEffectPattern,
  encodeBrowserInteractionEffect,
  encodeBrowserInteractionEffectPattern,
  gameplayAdjustResourceEffect,
  gameplayCommitEffect,
  gameplayInvokeEffect,
  gameplaySetCandidateEffect,
  gameplaySetScalarEffect,
} from "./effects.js";
export {
  createBrowserInteractionActuatorAttributes,
  createBrowserInteractionActuatorKey,
  createBrowserInteractionPointerTargetAttributes,
  createBrowserInteractionRootAttributes,
  createGameplayActuatorAttributes,
  createGameplayInteractionRootAttributes,
  createGameplayPointerTargetAttributes,
  type BrowserInteractionActuatorAttributesInput,
  type BrowserInteractionAttributeMap,
  type BrowserInteractionPointerTargetAttributesInput,
  type BrowserInteractionRootAttributesInput,
  type GameplayActuatorAttributesInput,
  type GameplayInteractionRootAttributesInput,
  type GameplayPointerTargetAttributesInput,
} from "./attributes.js";
export {
  createBrowserInteractionRegistry,
  defaultBrowserInteractionRegistry,
  defineBrowserInteractionSurface,
  gameplayBrowserInteractionSurface,
} from "./registry.js";
export {
  actuatorIdentityKey,
  isSemanticSurfaceSnapshot,
  normalizeBrowserInteractionRecords,
  pointerTargetIdentityKey,
  targetIdentityKey,
  validateBrowserInteractionSnapshot,
  type NormalizeBrowserInteractionRecordsOptions,
} from "./normalize.js";
export {
  resolveBrowserInteractionEffect,
  resolveBrowserInteractionIntent,
  resolveBrowserPointerTarget,
} from "./resolve.js";
export { readBrowserInteractionSnapshot } from "./dom.js";
export {
  browserInteractionEffectPatternSchema,
  browserInteractionEffectSchema,
  browserGameplayInteractionSchema,
  browserGameplaySurfaceSnapshotSchema,
  browserInteractionActuatorSchema,
  browserInteractionDiagnosticSchema,
  browserInteractionPointerTargetSchema,
  browserInteractionSnapshotSchema,
  browserSemanticSurfaceSnapshotSchema,
  browserUnknownSurfaceSnapshotSchema,
  gameplaySemanticEffectSchema,
} from "./schemas.js";
export type {
  BrowserGameplayInteraction,
  BrowserGameplaySurfaceSnapshot,
  BrowserInteractionActuator,
  BrowserInteractionActuatorKind,
  BrowserInteractionCandidateState,
  BrowserInteractionDiagnostic,
  BrowserInteractionEffectPattern,
  BrowserInteractionEffectRequest,
  BrowserInteractionEffectResolution,
  BrowserInteractionEffectResolutionFailure,
  BrowserInteractionEffectResolutionSuccess,
  BrowserInteractionEntity,
  BrowserInteractionIntent,
  BrowserInteractionIntentRequest,
  BrowserInteractionPreparationTarget,
  BrowserInteractionProtocolIdentity,
  BrowserInteractionPointerTarget,
  BrowserInteractionPointerTargetResolution,
  BrowserInteractionPointerTargetResolutionFailure,
  BrowserInteractionPointerTargetResolutionSuccess,
  BrowserInteractionRawRecord,
  BrowserInteractionReadiness,
  BrowserInteractionRegistry,
  BrowserInteractionResolution,
  BrowserInteractionResolutionFailure,
  BrowserInteractionResolutionSuccess,
  BrowserInteractionScalarPattern,
  BrowserInteractionSemanticSurfaceSnapshot,
  BrowserInteractionSnapshot,
  BrowserInteractionSurfaceEffect,
  BrowserInteractionSurface,
  BrowserInteractionSurfaceDefinition,
  BrowserInteractionSurfaceSnapshot,
  BrowserInteractionUnknownSurfaceSnapshot,
  GameplayBrowserInteractionEffectKind,
  GameplayBrowserInteractionEffectRequest,
  GameplayBrowserInteractionIntent,
  GameplayBrowserInteractionSurface,
  GameplaySemanticEffect,
  GameplaySemanticEffectPattern,
} from "./types.js";
