import { tileSpaceId } from "@dreamboard-games/sdk/reducer";
import { FRONTIER_GEOMETRY } from "./topology";
import type { ScenarioCommandOf } from "@dreamboard-games/sdk/testing";
import game from "../app/game.ts";
import type { EdgeId, ResourceId, SpaceId, VertexId } from "../app/manifest";
import type { ResourceCounts } from "../app/game-model.ts";

export type StormtrailCommand = ScenarioCommandOf<typeof game>;

function command(value: unknown): StormtrailCommand {
  return value as StormtrailCommand;
}

export function camp(
  seat: number,
  intersectionId: VertexId,
  interactionId: "placeStartingCamp" | "buildCamp" = "buildCamp",
) {
  return command({
    actor: { seat },
    interactionId,
    params: { intersectionId },
  });
}

export function trail(
  seat: number,
  edgeId: EdgeId,
  interactionId: "placeStartingTrail" | "buildTrail" = "buildTrail",
) {
  return command({ actor: { seat }, interactionId, params: { edgeId } });
}

export function roll(seat: number) {
  return command({ actor: { seat }, interactionId: "rollDice", params: {} });
}

export function end(seat: number) {
  return command({ actor: { seat }, interactionId: "endTurn", params: {} });
}

export function bandits(seat: number, hexId: SpaceId, targetSeat?: number) {
  return [
    command({
      actor: { seat },
      interactionId: "moveBandits",
      params: { hexId },
    }),
    command({
      actor: { seat },
      interactionId: "moveBandits",
      params: {
        targetPlayerId: targetSeat === undefined ? null : { seat: targetSeat },
      },
    }),
  ];
}

export function discard(seat: number, resources: ResourceCounts) {
  return command({
    actor: { seat },
    interactionId: "discardSupplies",
    params: { resources },
  });
}

export function depot(
  seat: number,
  giveResource: ResourceId,
  receiveResource: ResourceId,
) {
  return command({
    actor: { seat },
    interactionId: "tradeWithSupplyDepot",
    params: { giveResource, receiveResource },
  });
}

export function offer(
  seat: number,
  targetSeat: number,
  give: ResourceCounts,
  want: ResourceCounts,
) {
  return command({
    actor: { seat },
    interactionId: "offerTrade",
    params: { targetPlayerId: { seat: targetSeat }, give, want },
  });
}

export function accept(seat: number) {
  return command({ actor: { seat }, interactionId: "acceptTrade", params: {} });
}

export function reject(seat: number) {
  return command({ actor: { seat }, interactionId: "rejectTrade", params: {} });
}

export const STANDARD_SETUP_COMMANDS = [
  camp(
    0,
    FRONTIER_GEOMETRY.vertexAt(tileSpaceId("northForest", "cell"), 0),
    "placeStartingCamp",
  ),
  trail(
    0,
    FRONTIER_GEOMETRY.edgeAt(tileSpaceId("northForest", "cell"), 0),
    "placeStartingTrail",
  ),
  camp(
    1,
    FRONTIER_GEOMETRY.vertexAt(tileSpaceId("southEastFields", "cell"), 2),
    "placeStartingCamp",
  ),
  trail(
    1,
    FRONTIER_GEOMETRY.edgeAt(tileSpaceId("southEastFields", "cell"), 2),
    "placeStartingTrail",
  ),
  camp(
    2,
    FRONTIER_GEOMETRY.vertexAt(tileSpaceId("southWestClay", "cell"), 4),
    "placeStartingCamp",
  ),
  trail(
    2,
    FRONTIER_GEOMETRY.edgeAt(tileSpaceId("southWestClay", "cell"), 4),
    "placeStartingTrail",
  ),
] as const;

export const MULTI_VICTIM_SETUP_COMMANDS = [
  camp(
    0,
    FRONTIER_GEOMETRY.vertexAt(tileSpaceId("southEastFields", "cell"), 2),
    "placeStartingCamp",
  ),
  trail(
    0,
    FRONTIER_GEOMETRY.edgeAt(tileSpaceId("southEastFields", "cell"), 2),
    "placeStartingTrail",
  ),
  camp(
    1,
    FRONTIER_GEOMETRY.vertexAt(tileSpaceId("northForest", "cell"), 1),
    "placeStartingCamp",
  ),
  trail(
    1,
    FRONTIER_GEOMETRY.edgeAt(tileSpaceId("northWestFields", "cell"), 0),
    "placeStartingTrail",
  ),
  camp(
    2,
    FRONTIER_GEOMETRY.vertexAt(tileSpaceId("northForest", "cell"), 0),
    "placeStartingCamp",
  ),
  trail(
    2,
    FRONTIER_GEOMETRY.edgeAt(tileSpaceId("northForest", "cell"), 0),
    "placeStartingTrail",
  ),
] as const;

export const BANDITS_PREFIX_COMMANDS = [
  ...MULTI_VICTIM_SETUP_COMMANDS,
  roll(0),
] as const;

export const COMPLETE_GAME_COMMANDS = [
  ...STANDARD_SETUP_COMMANDS,
  roll(0),
  end(0),
  roll(1),
  offer(1, 0, { provisions: 1 }, { brick: 1 }),
  accept(0),
  camp(
    1,
    FRONTIER_GEOMETRY.vertexAt(tileSpaceId("southEastFields", "cell"), 1),
  ),
  end(1),
  roll(2),
  offer(2, 0, { provisions: 1 }, { timber: 1 }),
  accept(0),
  camp(2, FRONTIER_GEOMETRY.vertexAt(tileSpaceId("southWestClay", "cell"), 3)),
  end(2),
  roll(0),
  end(0),
  roll(1),
  end(1),
  roll(2),
  ...bandits(2, tileSpaceId("northWestFields", "cell")),
  end(2),
  roll(0),
  ...bandits(0, tileSpaceId("northEastClay", "cell")),
  end(0),
  roll(1),
  end(1),
  roll(2),
  ...bandits(2, tileSpaceId("northWestFields", "cell")),
  end(2),
  roll(0),
  end(0),
  roll(1),
  ...bandits(1, tileSpaceId("southEastFields", "cell")),
  end(1),
  roll(2),
  depot(2, "provisions", "brick"),
  offer(2, 0, { provisions: 1 }, { timber: 1 }),
  accept(0),
  trail(2, FRONTIER_GEOMETRY.edgeAt(tileSpaceId("southWestClay", "cell"), 5)),
  end(2),
  roll(0),
  depot(0, "provisions", "brick"),
  end(0),
  roll(1),
  offer(1, 0, { provisions: 1 }, { brick: 1 }),
  accept(0),
  offer(1, 0, { provisions: 1 }, { timber: 1 }),
  accept(0),
  trail(1, FRONTIER_GEOMETRY.edgeAt(tileSpaceId("southForest", "cell"), 4)),
  end(1),
  roll(2),
  end(2),
  roll(0),
  end(0),
  roll(1),
  end(1),
  roll(2),
  ...bandits(2, tileSpaceId("northWestFields", "cell")),
  depot(2, "provisions", "brick"),
  end(2),
  roll(0),
  ...bandits(0, tileSpaceId("northEastClay", "cell")),
  offer(0, 2, { provisions: 1 }, { brick: 1 }),
  accept(2),
  end(0),
  roll(1),
  offer(1, 0, { provisions: 1 }, { brick: 1 }),
  accept(0),
  end(1),
  roll(2),
  offer(2, 1, { provisions: 1 }, { brick: 1 }),
  accept(1),
  end(2),
  roll(0),
  offer(0, 2, { provisions: 1 }, { brick: 1 }),
  accept(2),
  end(0),
  roll(1),
  offer(1, 0, { provisions: 1 }, { brick: 1 }),
  accept(0),
  camp(1, FRONTIER_GEOMETRY.vertexAt(tileSpaceId("southForest", "cell"), 3)),
  end(1),
  roll(2),
  end(2),
  roll(0),
  end(0),
  roll(1),
  ...bandits(1, tileSpaceId("southEastFields", "cell")),
  end(1),
  roll(2),
  end(2),
  roll(0),
  end(0),
  roll(1),
  ...bandits(1, tileSpaceId("southForest", "cell")),
  depot(1, "timber", "brick"),
  trail(1, FRONTIER_GEOMETRY.edgeAt(tileSpaceId("southForest", "cell"), 3)),
  end(1),
  roll(2),
  end(2),
  roll(0),
  end(0),
  roll(1),
  offer(1, 0, { provisions: 1 }, { brick: 1 }),
  accept(0),
  depot(1, "provisions", "timber"),
  camp(1, FRONTIER_GEOMETRY.vertexAt(tileSpaceId("southForest", "cell"), 2)),
] as const;

/** Seed-1 legal replay ending immediately after turn 76 rolls a 7. */
export const DISCARD_BARRIER_PREFIX_COMMANDS = [
  ...STANDARD_SETUP_COMMANDS,
  roll(0),
  end(0),
  roll(1),
  end(1),
  roll(2),
  end(2),
  roll(0),
  end(0),
  roll(1),
  end(1),
  roll(2),
  ...bandits(2, tileSpaceId("northForest", "cell"), 0),
  end(2),
  roll(0),
  end(0),
  roll(1),
  ...bandits(1, tileSpaceId("centralBarrens", "cell"), 0),
  end(1),
  roll(2),
  end(2),
  roll(0),
  end(0),
  roll(1),
  end(1),
  roll(2),
  end(2),
  roll(0),
  end(0),
  roll(1),
  end(1),
  roll(2),
  end(2),
  roll(0),
  end(0),
  roll(1),
  end(1),
  roll(2),
  end(2),
  roll(0),
  discard(1, { provisions: 4 }),
  ...bandits(0, tileSpaceId("northForest", "cell")),
  end(0),
  roll(1),
  end(1),
  roll(2),
  end(2),
  roll(0),
  end(0),
  roll(1),
  ...bandits(1, tileSpaceId("centralBarrens", "cell"), 0),
  end(1),
  roll(2),
  discard(1, { provisions: 2, timber: 2 }),
  ...bandits(2, tileSpaceId("northForest", "cell"), 0),
  end(2),
  roll(0),
  end(0),
  roll(1),
  end(1),
  roll(2),
  discard(2, { brick: 2, provisions: 2 }),
  ...bandits(2, tileSpaceId("centralBarrens", "cell"), 1),
  end(2),
  roll(0),
  end(0),
  roll(1),
  end(1),
  roll(2),
  end(2),
  roll(0),
  end(0),
  roll(1),
  end(1),
  roll(2),
  end(2),
  roll(0),
  end(0),
  roll(1),
  end(1),
  roll(2),
  end(2),
  roll(0),
  ...bandits(0, tileSpaceId("northForest", "cell")),
  end(0),
  roll(1),
  end(1),
  roll(2),
  end(2),
  roll(0),
  discard(2, { brick: 3, provisions: 1 }),
  ...bandits(0, tileSpaceId("centralBarrens", "cell"), 1),
  end(0),
  roll(1),
  ...bandits(1, tileSpaceId("northForest", "cell"), 0),
  end(1),
  roll(2),
  end(2),
  roll(0),
  end(0),
  roll(1),
  end(1),
  roll(2),
  end(2),
  roll(0),
  discard(1, { brick: 1, provisions: 3 }),
  ...bandits(0, tileSpaceId("centralBarrens", "cell"), 1),
  end(0),
  roll(1),
  end(1),
  roll(2),
  end(2),
  roll(0),
  end(0),
  roll(1),
  discard(0, { brick: 3, provisions: 1 }),
  ...bandits(1, tileSpaceId("northForest", "cell"), 0),
  end(1),
  roll(2),
  end(2),
  roll(0),
  end(0),
  roll(1),
  end(1),
  roll(2),
  ...bandits(2, tileSpaceId("centralBarrens", "cell"), 0),
  end(2),
  roll(0),
  end(0),
  roll(1),
  end(1),
  roll(2),
  ...bandits(2, tileSpaceId("northForest", "cell"), 0),
  end(2),
  roll(0),
  end(0),
  roll(1),
  end(1),
  roll(2),
  end(2),
  roll(0),
  end(0),
  roll(1),
  end(1),
  roll(2),
  end(2),
  roll(0),
  end(0),
  roll(1),
  end(1),
  roll(2),
  end(2),
  roll(0),
  end(0),
  roll(1),
  end(1),
  roll(2),
  end(2),
  roll(0),
  end(0),
  roll(1),
  end(1),
  roll(2),
  end(2),
  roll(0),
  end(0),
  roll(1),
  depot(1, "timber", "brick"),
  depot(1, "timber", "brick"),
  depot(1, "timber", "brick"),
  end(1),
  roll(2),
  end(2),
  roll(0),
] as const;

export const PRODUCTION_COMMANDS = [
  ...DISCARD_BARRIER_PREFIX_COMMANDS,
  discard(0, { brick: 4 }),
  discard(1, { brick: 3, provisions: 1 }),
  ...bandits(0, tileSpaceId("centralBarrens", "cell"), 1),
  end(0),
  roll(1),
  end(1),
  roll(2),
  end(2),
  roll(0),
  discard(2, { brick: 4 }),
  ...bandits(0, tileSpaceId("northForest", "cell")),
  end(0),
  roll(1),
  end(1),
  roll(2),
  end(2),
  roll(0),
  end(0),
  roll(1),
  end(1),
  roll(2),
  end(2),
  roll(0),
  end(0),
  roll(1),
  ...bandits(1, tileSpaceId("centralBarrens", "cell"), 0),
  end(1),
  roll(2),
  end(2),
  roll(0),
  end(0),
  roll(1),
  end(1),
  roll(2),
  end(2),
  roll(0),
  end(0),
  roll(1),
  end(1),
  roll(2),
] as const;

export const NETWORK_EXHAUSTION_COMMANDS = [
  ...STANDARD_SETUP_COMMANDS,
  roll(0),
  trail(0, FRONTIER_GEOMETRY.edgeAt(tileSpaceId("northForest", "cell"), 1)),
  end(0),
  roll(1),
  end(1),
  roll(2),
  end(2),
  roll(0),
  end(0),
  roll(1),
  end(1),
  roll(2),
  ...bandits(2, tileSpaceId("southWestClay", "cell")),
  end(2),
  roll(0),
  ...bandits(0, tileSpaceId("northForest", "cell")),
  end(0),
  roll(1),
  end(1),
  roll(2),
  ...bandits(2, tileSpaceId("southWestClay", "cell")),
  end(2),
  roll(0),
  end(0),
  roll(1),
  ...bandits(1, tileSpaceId("southEastFields", "cell")),
  end(1),
  roll(2),
  end(2),
  roll(0),
  end(0),
  roll(1),
  end(1),
  roll(2),
  end(2),
  roll(0),
  end(0),
  roll(1),
  end(1),
  roll(2),
  ...bandits(2, tileSpaceId("southWestClay", "cell")),
  end(2),
  roll(0),
  ...bandits(0, tileSpaceId("northForest", "cell")),
  end(0),
  roll(1),
  end(1),
  roll(2),
  end(2),
  roll(0),
  trail(0, FRONTIER_GEOMETRY.edgeAt(tileSpaceId("northWestFields", "cell"), 0)),
  end(0),
  roll(1),
  end(1),
  roll(2),
  end(2),
  roll(0),
  trail(0, FRONTIER_GEOMETRY.edgeAt(tileSpaceId("northForest", "cell"), 2)),
  end(0),
  roll(1),
  ...bandits(1, tileSpaceId("southEastFields", "cell")),
  end(1),
  roll(2),
  end(2),
  roll(0),
  end(0),
  roll(1),
  discard(1, { provisions: 4 }),
  ...bandits(1, tileSpaceId("southForest", "cell")),
  end(1),
  roll(2),
  end(2),
  roll(0),
  end(0),
  roll(1),
  end(1),
  roll(2),
  end(2),
  roll(0),
  trail(0, FRONTIER_GEOMETRY.edgeAt(tileSpaceId("northForest", "cell"), 3)),
  end(0),
  roll(1),
  end(1),
  roll(2),
  end(2),
  roll(0),
  end(0),
  roll(1),
  end(1),
  roll(2),
  end(2),
  roll(0),
  trail(0, FRONTIER_GEOMETRY.edgeAt(tileSpaceId("northForest", "cell"), 4)),
  end(0),
  roll(1),
  discard(1, { provisions: 4 }),
  discard(2, { brick: 3, provisions: 1 }),
  ...bandits(1, tileSpaceId("southEastFields", "cell")),
  end(1),
  roll(2),
  end(2),
  roll(0),
  end(0),
  roll(1),
  ...bandits(1, tileSpaceId("southForest", "cell")),
  end(1),
  roll(2),
  ...bandits(2, tileSpaceId("southWestClay", "cell")),
  end(2),
  roll(0),
  end(0),
  roll(1),
  end(1),
  roll(2),
  ...bandits(2, tileSpaceId("northWestFields", "cell")),
  end(2),
  roll(0),
  end(0),
  roll(1),
  end(1),
  roll(2),
  end(2),
  roll(0),
  end(0),
  roll(1),
  end(1),
  roll(2),
  end(2),
  roll(0),
  ...bandits(0, tileSpaceId("northForest", "cell")),
  trail(0, FRONTIER_GEOMETRY.edgeAt(tileSpaceId("northWestFields", "cell"), 4)),
  end(0),
  roll(1),
  ...bandits(1, tileSpaceId("southEastFields", "cell")),
  end(1),
  roll(2),
  end(2),
  roll(0),
  end(0),
  roll(1),
  end(1),
  roll(2),
  discard(2, { brick: 1, provisions: 3 }),
  ...bandits(2, tileSpaceId("southWestClay", "cell")),
  end(2),
  roll(0),
  end(0),
  roll(1),
  end(1),
  roll(2),
  end(2),
  roll(0),
  trail(0, FRONTIER_GEOMETRY.edgeAt(tileSpaceId("northWestFields", "cell"), 3)),
  end(0),
  roll(1),
  end(1),
  roll(2),
  discard(1, { provisions: 3, timber: 1 }),
  ...bandits(2, tileSpaceId("northWestFields", "cell")),
  end(2),
  roll(0),
  trail(0, FRONTIER_GEOMETRY.edgeAt(tileSpaceId("northWestFields", "cell"), 2)),
  end(0),
  roll(1),
  end(1),
  roll(2),
  ...bandits(2, tileSpaceId("southWestClay", "cell")),
  end(2),
  roll(0),
  end(0),
  roll(1),
  end(1),
  roll(2),
  end(2),
  roll(0),
  end(0),
  roll(1),
  end(1),
  roll(2),
  end(2),
  roll(0),
  trail(0, FRONTIER_GEOMETRY.edgeAt(tileSpaceId("southWestClay", "cell"), 3)),
] as const;

export const INTERRUPTION_SETUP_COMMANDS = [
  camp(
    0,
    FRONTIER_GEOMETRY.vertexAt(tileSpaceId("northForest", "cell"), 0),
    "placeStartingCamp",
  ),
  trail(
    0,
    FRONTIER_GEOMETRY.edgeAt(tileSpaceId("northForest", "cell"), 0),
    "placeStartingTrail",
  ),
  camp(
    1,
    FRONTIER_GEOMETRY.vertexAt(tileSpaceId("northForest", "cell"), 5),
    "placeStartingCamp",
  ),
  trail(
    1,
    FRONTIER_GEOMETRY.edgeAt(tileSpaceId("northForest", "cell"), 5),
    "placeStartingTrail",
  ),
  camp(
    2,
    FRONTIER_GEOMETRY.vertexAt(tileSpaceId("southWestClay", "cell"), 4),
    "placeStartingCamp",
  ),
  trail(
    2,
    FRONTIER_GEOMETRY.edgeAt(tileSpaceId("southWestClay", "cell"), 4),
    "placeStartingTrail",
  ),
] as const;
