import type { CardId } from "../shared/manifest-contract";

export function submit(seat: number, cardIds: readonly CardId[]) {
  return {
    actor: { seat },
    interactionId: "submit",
    params: { cardIds },
  } as const;
}

export function play(seat: number, cardId: CardId) {
  return {
    actor: { seat },
    interactionId: "playCard",
    params: { cardId },
  } as const;
}

export const completeGamePath = [
  submit(0, ["clubs-6", "diamonds-10", "hearts-10"]),
  submit(1, ["diamonds-2", "spades-3", "diamonds-8"]),
  submit(2, ["hearts-8", "clubs-4", "spades-K"]),
  submit(3, ["diamonds-4", "clubs-7", "hearts-9"]),
  play(1, "clubs-2"),
  play(2, "clubs-A"),
  play(3, "clubs-10"),
  play(0, "clubs-3"),
  play(2, "spades-8"),
  play(3, "spades-J"),
  play(0, "spades-10"),
  play(1, "spades-9"),
  play(3, "spades-Q"),
  play(0, "spades-A"),
  play(1, "spades-5"),
  play(2, "spades-4"),
  play(0, "diamonds-9"),
  play(1, "diamonds-10"),
  play(2, "diamonds-8"),
  play(3, "diamonds-Q"),
  play(3, "spades-7"),
  play(0, "clubs-7"),
  play(1, "hearts-10"),
  play(2, "spades-6"),
  play(3, "spades-K"),
  play(0, "hearts-3"),
  play(1, "clubs-5"),
  play(2, "spades-2"),
  play(3, "clubs-4"),
  play(0, "hearts-7"),
  play(1, "clubs-K"),
  play(2, "diamonds-2"),
  play(1, "hearts-A"),
  play(2, "hearts-K"),
  play(3, "hearts-8"),
  play(0, "hearts-5"),
  play(1, "diamonds-3"),
  play(2, "diamonds-J"),
  play(3, "diamonds-7"),
  play(0, "diamonds-K"),
  play(0, "diamonds-6"),
  play(1, "diamonds-A"),
  play(2, "diamonds-5"),
  play(3, "hearts-6"),
  play(1, "clubs-6"),
  play(2, "spades-3"),
  play(3, "clubs-Q"),
  play(0, "diamonds-4"),
  play(3, "hearts-J"),
  play(0, "hearts-4"),
  play(1, "clubs-9"),
  play(2, "hearts-Q"),
  play(2, "hearts-2"),
  play(3, "clubs-J"),
  play(0, "hearts-9"),
  play(1, "clubs-8"),
] as const;

export const tiedLowestPath = [
  submit(0, ["diamonds-10", "hearts-4", "spades-A"]),
  submit(1, ["clubs-9", "spades-5", "spades-3"]),
  submit(2, ["clubs-4", "hearts-K", "diamonds-J"]),
  submit(3, ["hearts-J", "spades-Q", "clubs-10"]),
  play(1, "clubs-2"),
  play(2, "clubs-9"),
  play(3, "clubs-J"),
  play(0, "clubs-3"),
  play(3, "diamonds-7"),
  play(0, "diamonds-K"),
  play(1, "diamonds-3"),
  play(2, "diamonds-5"),
  play(0, "diamonds-6"),
  play(1, "diamonds-A"),
  play(2, "hearts-8"),
  play(3, "diamonds-Q"),
  play(1, "hearts-A"),
  play(2, "hearts-2"),
  play(3, "hearts-K"),
  play(0, "hearts-3"),
  play(1, "diamonds-2"),
  play(2, "spades-6"),
  play(3, "diamonds-4"),
  play(0, "diamonds-9"),
  play(0, "spades-Q"),
  play(1, "spades-A"),
  play(2, "spades-5"),
  play(3, "spades-J"),
  play(1, "clubs-5"),
  play(2, "clubs-A"),
  play(3, "clubs-Q"),
  play(0, "clubs-10"),
  play(2, "spades-2"),
  play(3, "spades-7"),
  play(0, "spades-10"),
  play(1, "spades-9"),
  play(0, "hearts-5"),
  play(1, "hearts-4"),
  play(2, "hearts-Q"),
  play(3, "hearts-9"),
  play(2, "spades-3"),
  play(3, "diamonds-J"),
  play(0, "hearts-J"),
  play(1, "diamonds-8"),
  play(2, "spades-4"),
  play(3, "hearts-6"),
  play(0, "hearts-10"),
  play(1, "clubs-8"),
  play(2, "spades-K"),
  play(3, "clubs-4"),
  play(0, "clubs-6"),
  play(1, "clubs-K"),
  play(2, "spades-8"),
  play(3, "clubs-7"),
  play(0, "hearts-7"),
  play(1, "diamonds-10"),
] as const;

export const shootTheMoonPath = [
  submit(0, ["clubs-3", "clubs-6", "diamonds-6"]),
  submit(1, ["spades-9", "spades-3", "clubs-K"]),
  submit(2, ["spades-K", "diamonds-5", "spades-4"]),
  submit(3, ["spades-Q", "hearts-J", "clubs-Q"]),
  play(1, "clubs-2"),
  play(2, "clubs-4"),
  play(3, "clubs-7"),
  play(0, "clubs-Q"),
  play(0, "spades-A"),
  play(1, "spades-5"),
  play(2, "spades-3"),
  play(3, "spades-4"),
  play(0, "diamonds-K"),
  play(1, "diamonds-2"),
  play(2, "diamonds-J"),
  play(3, "diamonds-5"),
  play(0, "spades-Q"),
  play(1, "hearts-A"),
  play(2, "spades-2"),
  play(3, "spades-7"),
  play(0, "hearts-J"),
  play(1, "clubs-3"),
  play(2, "hearts-2"),
  play(3, "hearts-6"),
  play(0, "hearts-10"),
  play(1, "diamonds-3"),
  play(2, "hearts-8"),
  play(3, "hearts-9"),
  play(0, "diamonds-10"),
  play(1, "diamonds-6"),
  play(2, "hearts-Q"),
  play(3, "diamonds-4"),
  play(0, "spades-10"),
  play(1, "clubs-5"),
  play(2, "spades-6"),
  play(3, "spades-J"),
  play(3, "diamonds-7"),
  play(0, "diamonds-9"),
  play(1, "diamonds-8"),
  play(2, "hearts-K"),
  play(0, "hearts-7"),
  play(1, "clubs-6"),
  play(2, "spades-9"),
  play(3, "clubs-J"),
  play(0, "hearts-5"),
  play(1, "clubs-8"),
  play(2, "spades-8"),
  play(3, "diamonds-Q"),
  play(0, "hearts-4"),
  play(1, "clubs-9"),
  play(2, "clubs-K"),
  play(3, "clubs-10"),
  play(0, "hearts-3"),
  play(1, "diamonds-A"),
  play(2, "clubs-A"),
  play(3, "spades-K"),
] as const;

export const allHeartsLeadPath = [
  submit(0, ["hearts-4", "hearts-7", "diamonds-6"]),
  submit(1, ["clubs-5", "spades-9", "diamonds-A"]),
  submit(2, ["clubs-A", "hearts-K", "diamonds-J"]),
  submit(3, ["hearts-J", "clubs-J", "diamonds-4"]),
  play(1, "clubs-2"),
  play(2, "clubs-5"),
  play(3, "clubs-7"),
  play(0, "clubs-6"),
  play(3, "clubs-10"),
  play(0, "clubs-J"),
  play(1, "clubs-9"),
  play(2, "clubs-4"),
  play(0, "diamonds-K"),
  play(1, "diamonds-8"),
  play(2, "diamonds-5"),
  play(3, "diamonds-7"),
  play(0, "diamonds-4"),
  play(1, "diamonds-6"),
  play(2, "diamonds-A"),
  play(3, "diamonds-Q"),
  play(2, "spades-2"),
  play(3, "spades-Q"),
  play(0, "spades-A"),
  play(1, "spades-3"),
  play(0, "diamonds-9"),
  play(1, "diamonds-2"),
  play(2, "spades-4"),
  play(3, "diamonds-J"),
  play(3, "clubs-Q"),
  play(0, "clubs-3"),
  play(1, "clubs-K"),
  play(2, "spades-6"),
  play(1, "spades-5"),
  play(2, "spades-8"),
  play(3, "spades-7"),
  play(0, "spades-10"),
  play(0, "diamonds-10"),
  play(1, "diamonds-3"),
  play(2, "spades-9"),
  play(3, "clubs-A"),
  play(0, "hearts-J"),
  play(1, "hearts-4"),
  play(2, "hearts-Q"),
  play(3, "hearts-K"),
  play(3, "spades-J"),
  play(0, "hearts-3"),
  play(1, "clubs-8"),
  play(2, "spades-K"),
  play(2, "hearts-2"),
  play(3, "hearts-6"),
  play(0, "hearts-10"),
  play(1, "hearts-7"),
  play(0, "hearts-5"),
  play(1, "hearts-A"),
  play(2, "hearts-8"),
  play(3, "hearts-9"),
] as const;

export const firstTrickPenaltyPasses = [
  submit(0, ["clubs-3", "clubs-6", "diamonds-9"]),
  submit(1, ["diamonds-3", "spades-5", "clubs-8"]),
  submit(2, ["spades-4", "hearts-Q", "spades-8"]),
  submit(3, ["hearts-6", "diamonds-7", "spades-Q"]),
] as const;

export const allPenaltyPasses = [
  submit(0, ["spades-6", "spades-K", "spades-8"]),
  submit(1, ["hearts-Q", "hearts-8", "hearts-3"]),
  submit(2, ["clubs-K", "diamonds-8", "clubs-3"]),
  submit(3, ["clubs-4", "diamonds-5", "clubs-6"]),
] as const;
