export { createWorkspaceUIContract } from "./workspace-contract/index.js";
export type { DreamboardUI, TypedGame, UIContract } from "./ui-contract.js";
export type {
  BoardHexGridProps,
  BoardHexViewProps,
  BoardSpaceTargetProps,
  ClientParamSchemaMap,
  GameMeState,
  GamePlayersState,
  GameRenderState,
  GameTurnState,
  ResourceCounterComponents,
  UIRootProps,
  WorkspaceBoardSurface,
  WorkspaceBoardSurfaceDescriptor,
  WorkspaceBoardTargetInputSlot,
  WorkspaceCardCollectionSurface,
  WorkspaceCardCollectionSurfaceDescriptor,
  WorkspaceCardInputSlot,
  WorkspaceFormInputSlot,
  WorkspaceHandSurface,
  WorkspaceHandSurfaceDescriptor,
  WorkspaceInteractionFormDescriptor,
  WorkspaceInteractionFormsDescriptor,
  WorkspaceInteractionSlotComponent,
  WorkspacePileSurface,
  WorkspacePileSurfaceDescriptor,
  WorkspacePilesSurfaceDescriptor,
  WorkspaceSurfaceSpec,
  ZoneCardRenderItem,
  ZoneListProps,
} from "./workspace-contract/index.js";
