import type {
  DieTypeSpec as ApiDieTypeSpec,
  GameTopologyManifest as ApiGameTopologyManifest,
} from "./contracts.js";

export type {
  ActionDefinition,
  ActionInteractionDescriptor,
  ActionParameterDefinition,
  AvailableInteractionAvailability,
  BlockedInteractionAvailability,
  BoardCard,
  BoardContainerHostSpec,
  BoardContainerSpec,
  BoardEdgeRef,
  BoardHostSpec,
  BoardLayout,
  BoardRelationSpec,
  BoardSpaceSpec,
  BoardSpec,
  BoardTargetDomain,
  BoardTemplateSpec,
  BoardVertexRef,
  BoundedNumberDomain,
  CardPropertySchema,
  CardPropertySchemaVariants,
  CardSetDefinition,
  CardSetSourceType,
  CardTargetDomain,
  ChoiceDomain,
  ChoiceDomainOption,
  ChoiceListDomain,
  ComponentHomeSpec,
  ComponentSlotSpec,
  ComponentVisibilitySpec,
  ContainerHomeSpec,
  DetachedHomeSpec,
  DieSeedSpec,
  DieSlotHostRef,
  EagerInputDomainDependencies,
  EdgeHomeSpec,
  GenericBoardSpec,
  GenericBoardTemplateSpec,
  HexBoardSpec,
  HexBoardTemplateSpec,
  HexEdgeRef,
  HexEdgeSpec,
  HexOrientation,
  HexSpaceSpec,
  HexVertexRef,
  HexVertexSpec,
  HistoryEntrySummary,
  HostActionSubmitResponse,
  HostEndedSessionSnapshot,
  HostGameplaySeatView,
  HostGameplaySessionSnapshot,
  HostGameplaySharedView,
  HostLobbySessionSnapshot,
  HostLobbyView,
  HostPlayerGameplayView,
  HostSessionContext,
  HostSessionEventCausation,
  HostSessionGameplayUpdatedEvent,
  HostSessionSnapshot,
  HostSessionStatus,
  InputDomain,
  InputDomainDependencyCase,
  InputDomainResolver,
  InputSelection,
  InsufficientResourcesInteractionAvailability,
  InteractionAvailability,
  InteractionCommitPolicy,
  InteractionContext,
  InteractionContextOption,
  InteractionDescriptor,
  InteractionDescriptorBase,
  InteractionInputDescriptor,
  JsonValue,
  LazyBoardTargetDomain,
  LazyCardTargetDomain,
  LazyInputDomainDependencies,
  ManualCardSetDefinition,
  ManyInputSelection,
  NotYourTurnInteractionAvailability,
  ObjectSchema,
  ParameterType,
  PieceSeedSpec,
  PieceSlotHostRef,
  PieceTypeSpec,
  PlayerId,
  PlayersDefinition,
  PresetCardSetDefinition,
  PromptInteractionDescriptor,
  PropertySchema,
  ResolvedBoardTargetDomain,
  ResolvedCardTargetDomain,
  ResourceDefinition,
  ResourceMapDomain,
  ResourceMapDomainEntry,
  SeatAssignment,
  SessionActor,
  SessionActorAuthUser,
  SessionActorDemoGuest,
  SessionGameSource,
  SessionGameSourceDemoRevision,
  SessionGameSourceUserCompiled,
  SessionSnapshotHistory,
  SessionSnapshotPhase,
  SetupOptionChoiceSpec,
  SetupOptionSpec,
  SetupProfileSpec,
  SimultaneousPhaseSnapshot,
  SingleInputSelection,
  SlotHomeSpec,
  SlotHostRef,
  SpaceHomeSpec,
  SpaceHostSpec,
  SquareBoardSpec,
  SquareBoardTemplateSpec,
  SquareEdgeSpec,
  SquareSpaceSpec,
  SquareVertexSpec,
  TopologyScope,
  VertexHomeSpec,
  ZoneHandles,
  ZoneHomeSpec,
  ZoneSpec,
  ZoneVisibility,
} from "./contracts.js";

export type DieTypeSpec = Omit<ApiDieTypeSpec, "sides"> & {
  sides?: ApiDieTypeSpec["sides"];
};

export type GameTopologyManifest = Omit<ApiGameTopologyManifest, "dieTypes"> & {
  dieTypes?: Array<DieTypeSpec>;
};

export type { CardCollection, ViewCard } from "./cards.js";
export type { ViewSlotOccupant } from "./slots.js";
export { defineTopologyManifest } from "./authoring.js";
export type { TypedTopologyManifest } from "./authoring.js";
export {
  buildTypedRecord,
  expectTypedId,
  isTypedId,
} from "./generated-helpers.js";
