import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { test } from "node:test";

// Minimal smoke: confirm the projection generated by `dreamboard test
// generate` is reachable from the UI test runner. The published example's
// UI tests intentionally stay light — the rich gameplay assertions live in
// the reducer-native scenarios under ../scenarios.

test("Sketchbook initial-turn projection is generated and parseable", () => {
  const projection = JSON.parse(
    readFileSync(
      new URL(
        "../generated/bases/initial-turn/player-1.projection.json",
        import.meta.url,
      ),
      "utf8",
    ),
  );
  assert.equal(typeof projection, "object");
  assert.ok(projection !== null, "projection should not be null");
  assert.equal(projection.view.gameOver, false);
  assert.equal(projection.view.outcome, null);
});

test("Sketchbook initial-turn projection includes every market pile", () => {
  const projection = JSON.parse(
    readFileSync(
      new URL(
        "../generated/bases/initial-turn/player-1.projection.json",
        import.meta.url,
      ),
      "utf8",
    ),
  );
  const marketZoneIds = Object.keys(projection.zones).filter((zoneId) =>
    zoneId.startsWith("supply-"),
  );

  assert.equal(marketZoneIds.length, 15);
  for (const zoneId of marketZoneIds) {
    assert.ok(
      projection.zones[zoneId].cardIds.length > 0,
      `${zoneId} should have market cards`,
    );
  }
});

test("Sketchbook initial-turn projection supports primitive-composed UI", () => {
  const projection = JSON.parse(
    readFileSync(
      new URL(
        "../generated/bases/initial-turn/player-1.projection.json",
        import.meta.url,
      ),
      "utf8",
    ),
  );
  const interactions = Object.fromEntries(
    projection.availableInteractions.map((descriptor) => [
      descriptor.interactionId,
      descriptor,
    ]),
  );

  assert.equal(interactions.endTurn.kind, "action");
  assert.notEqual(interactions.endTurn.availability.status, "available");
  assert.notEqual(
    interactions.playAllTreasures.availability.status,
    "available",
  );
  assert.equal(interactions.endActionPhase.availability.status, "available");
  assert.equal(projection.zones.hand.cardIds.length, 5);
  assert.equal(projection.view.deckCount, 5);
  assert.notEqual(interactions.buyCard.availability.status, "available");
});

test("Sketchbook UI uses typed collector surfaces for hand and supply cards", () => {
  const gameUiSource = readFileSync(
    new URL("../../ui/components/game-ui.tsx", import.meta.url),
    { encoding: "utf8" },
  );
  const cardSource = readFileSync(
    new URL("../../ui/components/cards.tsx", import.meta.url),
    { encoding: "utf8" },
  );
  const routeSource = readFileSync(
    new URL("../../ui/interaction-routes.tsx", import.meta.url),
    { encoding: "utf8" },
  );
  const surfaceSource = readFileSync(
    new URL("../../ui/surfaces.ts", import.meta.url),
    { encoding: "utf8" },
  );

  // No raw default form fields or manual slot construction — selection runs
  // through the canonical hand / supply card collectors.
  assert.doesNotMatch(routeSource, /createSlot/);
  assert.doesNotMatch(routeSource, /\.Field\b/);
  // Hand + supply render through the SDK CardFace and typed surfaces.
  assert.match(gameUiSource, /<hand\.Hand/);
  assert.match(gameUiSource, /<surface\.Card/);
  assert.match(gameUiSource, /CardFace/);
  assert.match(cardSource, /SketchCardContent/);
  // Routes bind the canonical hand + market collectors for play, resolve,
  // buy, and Studio Visit gain.
  assert.match(routeSource, /cardId: hand\.slot\.card/);
  assert.match(routeSource, /cardId: market\.slot\.card/);
  assert.match(routeSource, /trashedCardIds: hand\.slot\.card/);
  assert.match(routeSource, /gainCardId: market\.slot\.card/);
  // Supply uses the top-card collection so a pile renders one tile, not one
  // per card.
  assert.match(surfaceSource, /mode: "top-card"/);
});
