/**
 * Generated file.
 * Do not edit directly.
 */

export const literals = {
  playerIds: ["player-1", "player-2", "player-3", "player-4"] as const,
  phaseNames: [] as readonly string[],
  boardLayouts: ["generic", "hex", "square"] as const,
  setupOptionIds: [] as const,
  setupProfileIds: ["standard"] as const,
  cardSetIds: ["harbor-fair-cards"] as const,
  cardTypes: ["craft-p1-c1", "craft-p2-c0", "craft-p2-c1", "craft-p3-c0", "food-p1-c1", "food-p2-c0", "food-p2-c1", "food-p3-c0", "music-p1-c1", "music-p2-c0", "music-p2-c1", "music-p3-c0", "storm"] as const,
  cardIds: ["craft-p1-c1-1", "craft-p1-c1-2", "craft-p2-c0-1", "craft-p2-c0-2", "craft-p2-c0-3", "craft-p2-c0-4", "craft-p2-c1-1", "craft-p2-c1-2", "craft-p3-c0-1", "craft-p3-c0-2", "food-p1-c1-1", "food-p1-c1-2", "food-p2-c0-1", "food-p2-c0-2", "food-p2-c0-3", "food-p2-c0-4", "food-p2-c1-1", "food-p2-c1-2", "food-p3-c0-1", "food-p3-c0-2", "music-p1-c1-1", "music-p1-c1-2", "music-p2-c0-1", "music-p2-c0-2", "music-p2-c0-3", "music-p2-c0-4", "music-p2-c1-1", "music-p2-c1-2", "music-p3-c0-1", "music-p3-c0-2", "storm-1", "storm-2"] as const,
  deckIds: ["draw-pile", "market", "storm-discard"] as const,
  handIds: ["festival-row"] as const,
  sharedZoneIds: ["draw-pile", "market", "storm-discard"] as const,
  playerZoneIds: ["festival-row"] as const,
  zoneIds: ["draw-pile", "festival-row", "market", "storm-discard"] as const,
  resourceIds: [] as const,
  resourcePresentationById: {} as const,
  pieceTypeIds: [] as const,
  pieceIds: [] as const,
  dieTypeIds: [] as const,
  dieIds: [] as const,
  boardTemplateIds: [] as const,
  boardTypeIds: [] as const,
  boardBaseIds: [] as const,
  boardIds: [] as const,
  boardContainerIds: [] as const,
  relationTypeIds: [] as const,
  edgeIds: [] as const,
  edgeTypeIds: [] as const,
  vertexIds: [] as const,
  vertexTypeIds: [] as const,
  spaceIds: [] as const,
  spaceTypeIds: [] as const,
  handVisibilityById: {
  "festival-row": "public",
} as const,
  zoneVisibilityById: {
  "draw-pile": "hidden",
  "festival-row": "public",
  "market": "public",
  "storm-discard": "public",
} as const,
  cardSetIdByCardId: {
  "craft-p1-c1-1": "harbor-fair-cards",
  "craft-p1-c1-2": "harbor-fair-cards",
  "craft-p2-c0-1": "harbor-fair-cards",
  "craft-p2-c0-2": "harbor-fair-cards",
  "craft-p2-c0-3": "harbor-fair-cards",
  "craft-p2-c0-4": "harbor-fair-cards",
  "craft-p2-c1-1": "harbor-fair-cards",
  "craft-p2-c1-2": "harbor-fair-cards",
  "craft-p3-c0-1": "harbor-fair-cards",
  "craft-p3-c0-2": "harbor-fair-cards",
  "food-p1-c1-1": "harbor-fair-cards",
  "food-p1-c1-2": "harbor-fair-cards",
  "food-p2-c0-1": "harbor-fair-cards",
  "food-p2-c0-2": "harbor-fair-cards",
  "food-p2-c0-3": "harbor-fair-cards",
  "food-p2-c0-4": "harbor-fair-cards",
  "food-p2-c1-1": "harbor-fair-cards",
  "food-p2-c1-2": "harbor-fair-cards",
  "food-p3-c0-1": "harbor-fair-cards",
  "food-p3-c0-2": "harbor-fair-cards",
  "music-p1-c1-1": "harbor-fair-cards",
  "music-p1-c1-2": "harbor-fair-cards",
  "music-p2-c0-1": "harbor-fair-cards",
  "music-p2-c0-2": "harbor-fair-cards",
  "music-p2-c0-3": "harbor-fair-cards",
  "music-p2-c0-4": "harbor-fair-cards",
  "music-p2-c1-1": "harbor-fair-cards",
  "music-p2-c1-2": "harbor-fair-cards",
  "music-p3-c0-1": "harbor-fair-cards",
  "music-p3-c0-2": "harbor-fair-cards",
  "storm-1": "harbor-fair-cards",
  "storm-2": "harbor-fair-cards",
} as const,
  cardTypeByCardId: {
  "craft-p1-c1-1": "craft-p1-c1",
  "craft-p1-c1-2": "craft-p1-c1",
  "craft-p2-c0-1": "craft-p2-c0",
  "craft-p2-c0-2": "craft-p2-c0",
  "craft-p2-c0-3": "craft-p2-c0",
  "craft-p2-c0-4": "craft-p2-c0",
  "craft-p2-c1-1": "craft-p2-c1",
  "craft-p2-c1-2": "craft-p2-c1",
  "craft-p3-c0-1": "craft-p3-c0",
  "craft-p3-c0-2": "craft-p3-c0",
  "food-p1-c1-1": "food-p1-c1",
  "food-p1-c1-2": "food-p1-c1",
  "food-p2-c0-1": "food-p2-c0",
  "food-p2-c0-2": "food-p2-c0",
  "food-p2-c0-3": "food-p2-c0",
  "food-p2-c0-4": "food-p2-c0",
  "food-p2-c1-1": "food-p2-c1",
  "food-p2-c1-2": "food-p2-c1",
  "food-p3-c0-1": "food-p3-c0",
  "food-p3-c0-2": "food-p3-c0",
  "music-p1-c1-1": "music-p1-c1",
  "music-p1-c1-2": "music-p1-c1",
  "music-p2-c0-1": "music-p2-c0",
  "music-p2-c0-2": "music-p2-c0",
  "music-p2-c0-3": "music-p2-c0",
  "music-p2-c0-4": "music-p2-c0",
  "music-p2-c1-1": "music-p2-c1",
  "music-p2-c1-2": "music-p2-c1",
  "music-p3-c0-1": "music-p3-c0",
  "music-p3-c0-2": "music-p3-c0",
  "storm-1": "storm",
  "storm-2": "storm",
} as const,
  setupChoiceIdsByOptionId: {

} as const,
  cardSetIdsBySharedZoneId: {
  "draw-pile": ["harbor-fair-cards"] as const,
  "market": ["harbor-fair-cards"] as const,
  "storm-discard": ["harbor-fair-cards"] as const,
} as const,
  sharedZoneIdsByCardSetId: {
  "harbor-fair-cards": ["draw-pile", "market", "storm-discard"] as const,
} as const,
  homeSharedZoneIdsByCardType: {
  "craft-p1-c1": [] as const,
  "craft-p2-c0": [] as const,
  "craft-p2-c1": [] as const,
  "craft-p3-c0": [] as const,
  "food-p1-c1": [] as const,
  "food-p2-c0": [] as const,
  "food-p2-c1": [] as const,
  "food-p3-c0": [] as const,
  "music-p1-c1": [] as const,
  "music-p2-c0": [] as const,
  "music-p2-c1": [] as const,
  "music-p3-c0": [] as const,
  "storm": [] as const,
} as const,
  homeSharedZoneIdByCardType: {

} as const,
  cardSetIdsByPlayerZoneId: {
  "festival-row": ["harbor-fair-cards"] as const,
} as const,
} as const;
