/**
 * Generated file.
 * Do not edit directly.
 */

export const literals = {
  playerIds: ["player-1", "player-2"] as const,
  phaseNames: [] as readonly string[],
  boardLayouts: ["generic", "hex", "square"] as const,
  setupOptionIds: ["default-game"] as const,
  setupProfileIds: ["default-setup", "empty-masterpiece-regression"] as const,
  cardSetIds: ["sketchbook-cards"] as const,
  cardTypes: [
    "brainstorm",
    "concept",
    "critic",
    "doodle",
    "eraser",
    "gallery",
    "idea",
    "inkwork",
    "masterpiece",
    "open-mic",
    "sketch",
    "sketchpad",
    "smudge",
    "studio",
    "studio-visit",
  ] as const,
  cardIds: [
    "brainstorm-1",
    "brainstorm-2",
    "brainstorm-3",
    "brainstorm-4",
    "brainstorm-5",
    "brainstorm-6",
    "brainstorm-7",
    "concept-1",
    "concept-2",
    "concept-3",
    "concept-4",
    "concept-5",
    "concept-6",
    "concept-7",
    "concept-8",
    "critic-1",
    "critic-2",
    "critic-3",
    "critic-4",
    "critic-5",
    "critic-6",
    "critic-7",
    "doodle-1",
    "doodle-10",
    "doodle-11",
    "doodle-12",
    "doodle-13",
    "doodle-14",
    "doodle-15",
    "doodle-16",
    "doodle-17",
    "doodle-18",
    "doodle-19",
    "doodle-2",
    "doodle-20",
    "doodle-21",
    "doodle-22",
    "doodle-23",
    "doodle-24",
    "doodle-25",
    "doodle-26",
    "doodle-27",
    "doodle-28",
    "doodle-29",
    "doodle-3",
    "doodle-30",
    "doodle-31",
    "doodle-32",
    "doodle-33",
    "doodle-34",
    "doodle-35",
    "doodle-36",
    "doodle-37",
    "doodle-38",
    "doodle-39",
    "doodle-4",
    "doodle-40",
    "doodle-41",
    "doodle-42",
    "doodle-43",
    "doodle-44",
    "doodle-45",
    "doodle-46",
    "doodle-47",
    "doodle-48",
    "doodle-49",
    "doodle-5",
    "doodle-50",
    "doodle-51",
    "doodle-52",
    "doodle-53",
    "doodle-54",
    "doodle-55",
    "doodle-56",
    "doodle-57",
    "doodle-58",
    "doodle-59",
    "doodle-6",
    "doodle-60",
    "doodle-7",
    "doodle-8",
    "doodle-9",
    "eraser-1",
    "eraser-2",
    "eraser-3",
    "eraser-4",
    "eraser-5",
    "eraser-6",
    "eraser-7",
    "gallery-1",
    "gallery-2",
    "gallery-3",
    "gallery-4",
    "gallery-5",
    "gallery-6",
    "gallery-7",
    "idea-1",
    "idea-2",
    "idea-3",
    "idea-4",
    "idea-5",
    "idea-6",
    "idea-7",
    "idea-8",
    "inkwork-1",
    "inkwork-10",
    "inkwork-11",
    "inkwork-12",
    "inkwork-13",
    "inkwork-14",
    "inkwork-15",
    "inkwork-16",
    "inkwork-17",
    "inkwork-18",
    "inkwork-19",
    "inkwork-2",
    "inkwork-20",
    "inkwork-21",
    "inkwork-22",
    "inkwork-23",
    "inkwork-24",
    "inkwork-25",
    "inkwork-26",
    "inkwork-27",
    "inkwork-28",
    "inkwork-29",
    "inkwork-3",
    "inkwork-30",
    "inkwork-4",
    "inkwork-5",
    "inkwork-6",
    "inkwork-7",
    "inkwork-8",
    "inkwork-9",
    "masterpiece-1",
    "masterpiece-2",
    "masterpiece-3",
    "masterpiece-4",
    "masterpiece-5",
    "masterpiece-6",
    "masterpiece-7",
    "masterpiece-8",
    "open-mic-1",
    "open-mic-2",
    "open-mic-3",
    "open-mic-4",
    "open-mic-5",
    "open-mic-6",
    "open-mic-7",
    "sketch-1",
    "sketch-10",
    "sketch-11",
    "sketch-12",
    "sketch-13",
    "sketch-14",
    "sketch-15",
    "sketch-16",
    "sketch-17",
    "sketch-18",
    "sketch-19",
    "sketch-2",
    "sketch-20",
    "sketch-21",
    "sketch-22",
    "sketch-23",
    "sketch-24",
    "sketch-25",
    "sketch-26",
    "sketch-27",
    "sketch-28",
    "sketch-29",
    "sketch-3",
    "sketch-30",
    "sketch-31",
    "sketch-32",
    "sketch-33",
    "sketch-34",
    "sketch-35",
    "sketch-36",
    "sketch-37",
    "sketch-38",
    "sketch-39",
    "sketch-4",
    "sketch-40",
    "sketch-5",
    "sketch-6",
    "sketch-7",
    "sketch-8",
    "sketch-9",
    "sketchpad-1",
    "sketchpad-2",
    "sketchpad-3",
    "sketchpad-4",
    "sketchpad-5",
    "sketchpad-6",
    "sketchpad-7",
    "smudge-1",
    "smudge-10",
    "smudge-2",
    "smudge-3",
    "smudge-4",
    "smudge-5",
    "smudge-6",
    "smudge-7",
    "smudge-8",
    "smudge-9",
    "studio-1",
    "studio-2",
    "studio-3",
    "studio-4",
    "studio-5",
    "studio-6",
    "studio-7",
    "studio-visit-1",
    "studio-visit-2",
    "studio-visit-3",
    "studio-visit-4",
    "studio-visit-5",
    "studio-visit-6",
    "studio-visit-7",
  ] as const,
  deckIds: [
    "supply-brainstorm",
    "supply-concept",
    "supply-critic",
    "supply-doodle",
    "supply-eraser",
    "supply-gallery",
    "supply-idea",
    "supply-inkwork",
    "supply-masterpiece",
    "supply-open-mic",
    "supply-sketch",
    "supply-sketchpad",
    "supply-smudge",
    "supply-studio",
    "supply-studio-visit",
    "trash",
  ] as const,
  handIds: ["deck", "discard", "hand", "in-play"] as const,
  sharedZoneIds: [
    "supply-brainstorm",
    "supply-concept",
    "supply-critic",
    "supply-doodle",
    "supply-eraser",
    "supply-gallery",
    "supply-idea",
    "supply-inkwork",
    "supply-masterpiece",
    "supply-open-mic",
    "supply-sketch",
    "supply-sketchpad",
    "supply-smudge",
    "supply-studio",
    "supply-studio-visit",
    "trash",
  ] as const,
  playerZoneIds: ["deck", "discard", "hand", "in-play"] as const,
  zoneIds: [
    "deck",
    "discard",
    "hand",
    "in-play",
    "supply-brainstorm",
    "supply-concept",
    "supply-critic",
    "supply-doodle",
    "supply-eraser",
    "supply-gallery",
    "supply-idea",
    "supply-inkwork",
    "supply-masterpiece",
    "supply-open-mic",
    "supply-sketch",
    "supply-sketchpad",
    "supply-smudge",
    "supply-studio",
    "supply-studio-visit",
    "trash",
  ] as const,
  resourceIds: [] as const,
  resourcePresentationById: {} as const,
  pieceTypeIds: [] as const,
  pieceIds: [] as const,
  dieTypeIds: [] as const,
  dieIds: [] as const,
  boardTemplateIds: [] as const,
  boardTypeIds: [] as const,
  boardBaseIds: [] as const,
  boardIds: [] as const,
  boardContainerIds: [] as const,
  relationTypeIds: [] as const,
  edgeIds: [] as const,
  edgeTypeIds: [] as const,
  vertexIds: [] as const,
  vertexTypeIds: [] as const,
  spaceIds: [] as const,
  spaceTypeIds: [] as const,
  handVisibilityById: {
    deck: "ownerOnly",
    discard: "public",
    hand: "ownerOnly",
    "in-play": "public",
  } as const,
  zoneVisibilityById: {
    deck: "ownerOnly",
    discard: "public",
    hand: "ownerOnly",
    "in-play": "public",
    "supply-brainstorm": "public",
    "supply-concept": "public",
    "supply-critic": "public",
    "supply-doodle": "public",
    "supply-eraser": "public",
    "supply-gallery": "public",
    "supply-idea": "public",
    "supply-inkwork": "public",
    "supply-masterpiece": "public",
    "supply-open-mic": "public",
    "supply-sketch": "public",
    "supply-sketchpad": "public",
    "supply-smudge": "public",
    "supply-studio": "public",
    "supply-studio-visit": "public",
    trash: "public",
  } as const,
  cardSetIdByCardId: {
    "brainstorm-1": "sketchbook-cards",
    "brainstorm-2": "sketchbook-cards",
    "brainstorm-3": "sketchbook-cards",
    "brainstorm-4": "sketchbook-cards",
    "brainstorm-5": "sketchbook-cards",
    "brainstorm-6": "sketchbook-cards",
    "brainstorm-7": "sketchbook-cards",
    "concept-1": "sketchbook-cards",
    "concept-2": "sketchbook-cards",
    "concept-3": "sketchbook-cards",
    "concept-4": "sketchbook-cards",
    "concept-5": "sketchbook-cards",
    "concept-6": "sketchbook-cards",
    "concept-7": "sketchbook-cards",
    "concept-8": "sketchbook-cards",
    "critic-1": "sketchbook-cards",
    "critic-2": "sketchbook-cards",
    "critic-3": "sketchbook-cards",
    "critic-4": "sketchbook-cards",
    "critic-5": "sketchbook-cards",
    "critic-6": "sketchbook-cards",
    "critic-7": "sketchbook-cards",
    "doodle-1": "sketchbook-cards",
    "doodle-10": "sketchbook-cards",
    "doodle-11": "sketchbook-cards",
    "doodle-12": "sketchbook-cards",
    "doodle-13": "sketchbook-cards",
    "doodle-14": "sketchbook-cards",
    "doodle-15": "sketchbook-cards",
    "doodle-16": "sketchbook-cards",
    "doodle-17": "sketchbook-cards",
    "doodle-18": "sketchbook-cards",
    "doodle-19": "sketchbook-cards",
    "doodle-2": "sketchbook-cards",
    "doodle-20": "sketchbook-cards",
    "doodle-21": "sketchbook-cards",
    "doodle-22": "sketchbook-cards",
    "doodle-23": "sketchbook-cards",
    "doodle-24": "sketchbook-cards",
    "doodle-25": "sketchbook-cards",
    "doodle-26": "sketchbook-cards",
    "doodle-27": "sketchbook-cards",
    "doodle-28": "sketchbook-cards",
    "doodle-29": "sketchbook-cards",
    "doodle-3": "sketchbook-cards",
    "doodle-30": "sketchbook-cards",
    "doodle-31": "sketchbook-cards",
    "doodle-32": "sketchbook-cards",
    "doodle-33": "sketchbook-cards",
    "doodle-34": "sketchbook-cards",
    "doodle-35": "sketchbook-cards",
    "doodle-36": "sketchbook-cards",
    "doodle-37": "sketchbook-cards",
    "doodle-38": "sketchbook-cards",
    "doodle-39": "sketchbook-cards",
    "doodle-4": "sketchbook-cards",
    "doodle-40": "sketchbook-cards",
    "doodle-41": "sketchbook-cards",
    "doodle-42": "sketchbook-cards",
    "doodle-43": "sketchbook-cards",
    "doodle-44": "sketchbook-cards",
    "doodle-45": "sketchbook-cards",
    "doodle-46": "sketchbook-cards",
    "doodle-47": "sketchbook-cards",
    "doodle-48": "sketchbook-cards",
    "doodle-49": "sketchbook-cards",
    "doodle-5": "sketchbook-cards",
    "doodle-50": "sketchbook-cards",
    "doodle-51": "sketchbook-cards",
    "doodle-52": "sketchbook-cards",
    "doodle-53": "sketchbook-cards",
    "doodle-54": "sketchbook-cards",
    "doodle-55": "sketchbook-cards",
    "doodle-56": "sketchbook-cards",
    "doodle-57": "sketchbook-cards",
    "doodle-58": "sketchbook-cards",
    "doodle-59": "sketchbook-cards",
    "doodle-6": "sketchbook-cards",
    "doodle-60": "sketchbook-cards",
    "doodle-7": "sketchbook-cards",
    "doodle-8": "sketchbook-cards",
    "doodle-9": "sketchbook-cards",
    "eraser-1": "sketchbook-cards",
    "eraser-2": "sketchbook-cards",
    "eraser-3": "sketchbook-cards",
    "eraser-4": "sketchbook-cards",
    "eraser-5": "sketchbook-cards",
    "eraser-6": "sketchbook-cards",
    "eraser-7": "sketchbook-cards",
    "gallery-1": "sketchbook-cards",
    "gallery-2": "sketchbook-cards",
    "gallery-3": "sketchbook-cards",
    "gallery-4": "sketchbook-cards",
    "gallery-5": "sketchbook-cards",
    "gallery-6": "sketchbook-cards",
    "gallery-7": "sketchbook-cards",
    "idea-1": "sketchbook-cards",
    "idea-2": "sketchbook-cards",
    "idea-3": "sketchbook-cards",
    "idea-4": "sketchbook-cards",
    "idea-5": "sketchbook-cards",
    "idea-6": "sketchbook-cards",
    "idea-7": "sketchbook-cards",
    "idea-8": "sketchbook-cards",
    "inkwork-1": "sketchbook-cards",
    "inkwork-10": "sketchbook-cards",
    "inkwork-11": "sketchbook-cards",
    "inkwork-12": "sketchbook-cards",
    "inkwork-13": "sketchbook-cards",
    "inkwork-14": "sketchbook-cards",
    "inkwork-15": "sketchbook-cards",
    "inkwork-16": "sketchbook-cards",
    "inkwork-17": "sketchbook-cards",
    "inkwork-18": "sketchbook-cards",
    "inkwork-19": "sketchbook-cards",
    "inkwork-2": "sketchbook-cards",
    "inkwork-20": "sketchbook-cards",
    "inkwork-21": "sketchbook-cards",
    "inkwork-22": "sketchbook-cards",
    "inkwork-23": "sketchbook-cards",
    "inkwork-24": "sketchbook-cards",
    "inkwork-25": "sketchbook-cards",
    "inkwork-26": "sketchbook-cards",
    "inkwork-27": "sketchbook-cards",
    "inkwork-28": "sketchbook-cards",
    "inkwork-29": "sketchbook-cards",
    "inkwork-3": "sketchbook-cards",
    "inkwork-30": "sketchbook-cards",
    "inkwork-4": "sketchbook-cards",
    "inkwork-5": "sketchbook-cards",
    "inkwork-6": "sketchbook-cards",
    "inkwork-7": "sketchbook-cards",
    "inkwork-8": "sketchbook-cards",
    "inkwork-9": "sketchbook-cards",
    "masterpiece-1": "sketchbook-cards",
    "masterpiece-2": "sketchbook-cards",
    "masterpiece-3": "sketchbook-cards",
    "masterpiece-4": "sketchbook-cards",
    "masterpiece-5": "sketchbook-cards",
    "masterpiece-6": "sketchbook-cards",
    "masterpiece-7": "sketchbook-cards",
    "masterpiece-8": "sketchbook-cards",
    "open-mic-1": "sketchbook-cards",
    "open-mic-2": "sketchbook-cards",
    "open-mic-3": "sketchbook-cards",
    "open-mic-4": "sketchbook-cards",
    "open-mic-5": "sketchbook-cards",
    "open-mic-6": "sketchbook-cards",
    "open-mic-7": "sketchbook-cards",
    "sketch-1": "sketchbook-cards",
    "sketch-10": "sketchbook-cards",
    "sketch-11": "sketchbook-cards",
    "sketch-12": "sketchbook-cards",
    "sketch-13": "sketchbook-cards",
    "sketch-14": "sketchbook-cards",
    "sketch-15": "sketchbook-cards",
    "sketch-16": "sketchbook-cards",
    "sketch-17": "sketchbook-cards",
    "sketch-18": "sketchbook-cards",
    "sketch-19": "sketchbook-cards",
    "sketch-2": "sketchbook-cards",
    "sketch-20": "sketchbook-cards",
    "sketch-21": "sketchbook-cards",
    "sketch-22": "sketchbook-cards",
    "sketch-23": "sketchbook-cards",
    "sketch-24": "sketchbook-cards",
    "sketch-25": "sketchbook-cards",
    "sketch-26": "sketchbook-cards",
    "sketch-27": "sketchbook-cards",
    "sketch-28": "sketchbook-cards",
    "sketch-29": "sketchbook-cards",
    "sketch-3": "sketchbook-cards",
    "sketch-30": "sketchbook-cards",
    "sketch-31": "sketchbook-cards",
    "sketch-32": "sketchbook-cards",
    "sketch-33": "sketchbook-cards",
    "sketch-34": "sketchbook-cards",
    "sketch-35": "sketchbook-cards",
    "sketch-36": "sketchbook-cards",
    "sketch-37": "sketchbook-cards",
    "sketch-38": "sketchbook-cards",
    "sketch-39": "sketchbook-cards",
    "sketch-4": "sketchbook-cards",
    "sketch-40": "sketchbook-cards",
    "sketch-5": "sketchbook-cards",
    "sketch-6": "sketchbook-cards",
    "sketch-7": "sketchbook-cards",
    "sketch-8": "sketchbook-cards",
    "sketch-9": "sketchbook-cards",
    "sketchpad-1": "sketchbook-cards",
    "sketchpad-2": "sketchbook-cards",
    "sketchpad-3": "sketchbook-cards",
    "sketchpad-4": "sketchbook-cards",
    "sketchpad-5": "sketchbook-cards",
    "sketchpad-6": "sketchbook-cards",
    "sketchpad-7": "sketchbook-cards",
    "smudge-1": "sketchbook-cards",
    "smudge-10": "sketchbook-cards",
    "smudge-2": "sketchbook-cards",
    "smudge-3": "sketchbook-cards",
    "smudge-4": "sketchbook-cards",
    "smudge-5": "sketchbook-cards",
    "smudge-6": "sketchbook-cards",
    "smudge-7": "sketchbook-cards",
    "smudge-8": "sketchbook-cards",
    "smudge-9": "sketchbook-cards",
    "studio-1": "sketchbook-cards",
    "studio-2": "sketchbook-cards",
    "studio-3": "sketchbook-cards",
    "studio-4": "sketchbook-cards",
    "studio-5": "sketchbook-cards",
    "studio-6": "sketchbook-cards",
    "studio-7": "sketchbook-cards",
    "studio-visit-1": "sketchbook-cards",
    "studio-visit-2": "sketchbook-cards",
    "studio-visit-3": "sketchbook-cards",
    "studio-visit-4": "sketchbook-cards",
    "studio-visit-5": "sketchbook-cards",
    "studio-visit-6": "sketchbook-cards",
    "studio-visit-7": "sketchbook-cards",
  } as const,
  cardTypeByCardId: {
    "brainstorm-1": "brainstorm",
    "brainstorm-2": "brainstorm",
    "brainstorm-3": "brainstorm",
    "brainstorm-4": "brainstorm",
    "brainstorm-5": "brainstorm",
    "brainstorm-6": "brainstorm",
    "brainstorm-7": "brainstorm",
    "concept-1": "concept",
    "concept-2": "concept",
    "concept-3": "concept",
    "concept-4": "concept",
    "concept-5": "concept",
    "concept-6": "concept",
    "concept-7": "concept",
    "concept-8": "concept",
    "critic-1": "critic",
    "critic-2": "critic",
    "critic-3": "critic",
    "critic-4": "critic",
    "critic-5": "critic",
    "critic-6": "critic",
    "critic-7": "critic",
    "doodle-1": "doodle",
    "doodle-10": "doodle",
    "doodle-11": "doodle",
    "doodle-12": "doodle",
    "doodle-13": "doodle",
    "doodle-14": "doodle",
    "doodle-15": "doodle",
    "doodle-16": "doodle",
    "doodle-17": "doodle",
    "doodle-18": "doodle",
    "doodle-19": "doodle",
    "doodle-2": "doodle",
    "doodle-20": "doodle",
    "doodle-21": "doodle",
    "doodle-22": "doodle",
    "doodle-23": "doodle",
    "doodle-24": "doodle",
    "doodle-25": "doodle",
    "doodle-26": "doodle",
    "doodle-27": "doodle",
    "doodle-28": "doodle",
    "doodle-29": "doodle",
    "doodle-3": "doodle",
    "doodle-30": "doodle",
    "doodle-31": "doodle",
    "doodle-32": "doodle",
    "doodle-33": "doodle",
    "doodle-34": "doodle",
    "doodle-35": "doodle",
    "doodle-36": "doodle",
    "doodle-37": "doodle",
    "doodle-38": "doodle",
    "doodle-39": "doodle",
    "doodle-4": "doodle",
    "doodle-40": "doodle",
    "doodle-41": "doodle",
    "doodle-42": "doodle",
    "doodle-43": "doodle",
    "doodle-44": "doodle",
    "doodle-45": "doodle",
    "doodle-46": "doodle",
    "doodle-47": "doodle",
    "doodle-48": "doodle",
    "doodle-49": "doodle",
    "doodle-5": "doodle",
    "doodle-50": "doodle",
    "doodle-51": "doodle",
    "doodle-52": "doodle",
    "doodle-53": "doodle",
    "doodle-54": "doodle",
    "doodle-55": "doodle",
    "doodle-56": "doodle",
    "doodle-57": "doodle",
    "doodle-58": "doodle",
    "doodle-59": "doodle",
    "doodle-6": "doodle",
    "doodle-60": "doodle",
    "doodle-7": "doodle",
    "doodle-8": "doodle",
    "doodle-9": "doodle",
    "eraser-1": "eraser",
    "eraser-2": "eraser",
    "eraser-3": "eraser",
    "eraser-4": "eraser",
    "eraser-5": "eraser",
    "eraser-6": "eraser",
    "eraser-7": "eraser",
    "gallery-1": "gallery",
    "gallery-2": "gallery",
    "gallery-3": "gallery",
    "gallery-4": "gallery",
    "gallery-5": "gallery",
    "gallery-6": "gallery",
    "gallery-7": "gallery",
    "idea-1": "idea",
    "idea-2": "idea",
    "idea-3": "idea",
    "idea-4": "idea",
    "idea-5": "idea",
    "idea-6": "idea",
    "idea-7": "idea",
    "idea-8": "idea",
    "inkwork-1": "inkwork",
    "inkwork-10": "inkwork",
    "inkwork-11": "inkwork",
    "inkwork-12": "inkwork",
    "inkwork-13": "inkwork",
    "inkwork-14": "inkwork",
    "inkwork-15": "inkwork",
    "inkwork-16": "inkwork",
    "inkwork-17": "inkwork",
    "inkwork-18": "inkwork",
    "inkwork-19": "inkwork",
    "inkwork-2": "inkwork",
    "inkwork-20": "inkwork",
    "inkwork-21": "inkwork",
    "inkwork-22": "inkwork",
    "inkwork-23": "inkwork",
    "inkwork-24": "inkwork",
    "inkwork-25": "inkwork",
    "inkwork-26": "inkwork",
    "inkwork-27": "inkwork",
    "inkwork-28": "inkwork",
    "inkwork-29": "inkwork",
    "inkwork-3": "inkwork",
    "inkwork-30": "inkwork",
    "inkwork-4": "inkwork",
    "inkwork-5": "inkwork",
    "inkwork-6": "inkwork",
    "inkwork-7": "inkwork",
    "inkwork-8": "inkwork",
    "inkwork-9": "inkwork",
    "masterpiece-1": "masterpiece",
    "masterpiece-2": "masterpiece",
    "masterpiece-3": "masterpiece",
    "masterpiece-4": "masterpiece",
    "masterpiece-5": "masterpiece",
    "masterpiece-6": "masterpiece",
    "masterpiece-7": "masterpiece",
    "masterpiece-8": "masterpiece",
    "open-mic-1": "open-mic",
    "open-mic-2": "open-mic",
    "open-mic-3": "open-mic",
    "open-mic-4": "open-mic",
    "open-mic-5": "open-mic",
    "open-mic-6": "open-mic",
    "open-mic-7": "open-mic",
    "sketch-1": "sketch",
    "sketch-10": "sketch",
    "sketch-11": "sketch",
    "sketch-12": "sketch",
    "sketch-13": "sketch",
    "sketch-14": "sketch",
    "sketch-15": "sketch",
    "sketch-16": "sketch",
    "sketch-17": "sketch",
    "sketch-18": "sketch",
    "sketch-19": "sketch",
    "sketch-2": "sketch",
    "sketch-20": "sketch",
    "sketch-21": "sketch",
    "sketch-22": "sketch",
    "sketch-23": "sketch",
    "sketch-24": "sketch",
    "sketch-25": "sketch",
    "sketch-26": "sketch",
    "sketch-27": "sketch",
    "sketch-28": "sketch",
    "sketch-29": "sketch",
    "sketch-3": "sketch",
    "sketch-30": "sketch",
    "sketch-31": "sketch",
    "sketch-32": "sketch",
    "sketch-33": "sketch",
    "sketch-34": "sketch",
    "sketch-35": "sketch",
    "sketch-36": "sketch",
    "sketch-37": "sketch",
    "sketch-38": "sketch",
    "sketch-39": "sketch",
    "sketch-4": "sketch",
    "sketch-40": "sketch",
    "sketch-5": "sketch",
    "sketch-6": "sketch",
    "sketch-7": "sketch",
    "sketch-8": "sketch",
    "sketch-9": "sketch",
    "sketchpad-1": "sketchpad",
    "sketchpad-2": "sketchpad",
    "sketchpad-3": "sketchpad",
    "sketchpad-4": "sketchpad",
    "sketchpad-5": "sketchpad",
    "sketchpad-6": "sketchpad",
    "sketchpad-7": "sketchpad",
    "smudge-1": "smudge",
    "smudge-10": "smudge",
    "smudge-2": "smudge",
    "smudge-3": "smudge",
    "smudge-4": "smudge",
    "smudge-5": "smudge",
    "smudge-6": "smudge",
    "smudge-7": "smudge",
    "smudge-8": "smudge",
    "smudge-9": "smudge",
    "studio-1": "studio",
    "studio-2": "studio",
    "studio-3": "studio",
    "studio-4": "studio",
    "studio-5": "studio",
    "studio-6": "studio",
    "studio-7": "studio",
    "studio-visit-1": "studio-visit",
    "studio-visit-2": "studio-visit",
    "studio-visit-3": "studio-visit",
    "studio-visit-4": "studio-visit",
    "studio-visit-5": "studio-visit",
    "studio-visit-6": "studio-visit",
    "studio-visit-7": "studio-visit",
  } as const,
  setupChoiceIdsByOptionId: {
    "default-game": ["default-game"] as const,
  } as const,
  cardSetIdsBySharedZoneId: {
    "supply-brainstorm": ["sketchbook-cards"] as const,
    "supply-concept": ["sketchbook-cards"] as const,
    "supply-critic": ["sketchbook-cards"] as const,
    "supply-doodle": ["sketchbook-cards"] as const,
    "supply-eraser": ["sketchbook-cards"] as const,
    "supply-gallery": ["sketchbook-cards"] as const,
    "supply-idea": ["sketchbook-cards"] as const,
    "supply-inkwork": ["sketchbook-cards"] as const,
    "supply-masterpiece": ["sketchbook-cards"] as const,
    "supply-open-mic": ["sketchbook-cards"] as const,
    "supply-sketch": ["sketchbook-cards"] as const,
    "supply-sketchpad": ["sketchbook-cards"] as const,
    "supply-smudge": ["sketchbook-cards"] as const,
    "supply-studio": ["sketchbook-cards"] as const,
    "supply-studio-visit": ["sketchbook-cards"] as const,
    trash: ["sketchbook-cards"] as const,
  } as const,
  sharedZoneIdsByCardSetId: {
    "sketchbook-cards": [
      "supply-brainstorm",
      "supply-concept",
      "supply-critic",
      "supply-doodle",
      "supply-eraser",
      "supply-gallery",
      "supply-idea",
      "supply-inkwork",
      "supply-masterpiece",
      "supply-open-mic",
      "supply-sketch",
      "supply-sketchpad",
      "supply-smudge",
      "supply-studio",
      "supply-studio-visit",
      "trash",
    ] as const,
  } as const,
  homeSharedZoneIdsByCardType: {
    brainstorm: ["supply-brainstorm"] as const,
    concept: ["supply-concept"] as const,
    critic: ["supply-critic"] as const,
    doodle: ["supply-doodle"] as const,
    eraser: ["supply-eraser"] as const,
    gallery: ["supply-gallery"] as const,
    idea: ["supply-idea"] as const,
    inkwork: ["supply-inkwork"] as const,
    masterpiece: ["supply-masterpiece"] as const,
    "open-mic": ["supply-open-mic"] as const,
    sketch: ["supply-sketch"] as const,
    sketchpad: ["supply-sketchpad"] as const,
    smudge: ["supply-smudge"] as const,
    studio: ["supply-studio"] as const,
    "studio-visit": ["supply-studio-visit"] as const,
  } as const,
  homeSharedZoneIdByCardType: {
    brainstorm: "supply-brainstorm",
    concept: "supply-concept",
    critic: "supply-critic",
    doodle: "supply-doodle",
    eraser: "supply-eraser",
    gallery: "supply-gallery",
    idea: "supply-idea",
    inkwork: "supply-inkwork",
    masterpiece: "supply-masterpiece",
    "open-mic": "supply-open-mic",
    sketch: "supply-sketch",
    sketchpad: "supply-sketchpad",
    smudge: "supply-smudge",
    studio: "supply-studio",
    "studio-visit": "supply-studio-visit",
  } as const,
  cardSetIdsByPlayerZoneId: {
    deck: ["sketchbook-cards"] as const,
    discard: ["sketchbook-cards"] as const,
    hand: ["sketchbook-cards"] as const,
    "in-play": ["sketchbook-cards"] as const,
  } as const,
} as const;
